In [3]:
import os
import sys
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset, SubsetRandomSampler
from torchvision import transforms, models
from PIL import Image
import numpy as np
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
from tqdm import tqdm
import warnings
import pandas as pd
import pickle
warnings.filterwarnings('ignore')

def check_gpu_available():
    if not torch.cuda.is_available():
        print("Error: No available GPU device detected.")
        print("Please ensure:")
        print("1. CUDA and cuDNN are installed")
        print("2. A GPU-compatible PyTorch version is installed")
        print("3. The graphics card driver is up to date")
        print("\nProgram requires GPU for training, exiting now...")
        sys.exit(1)
    
    print(f"✓ GPU available: {torch.cuda.get_device_name(0)}")
    print(f"  Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
    print(f"  CUDA version: {torch.version.cuda}")
    return True

check_gpu_available()

def set_seed(seed=42):
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

class CustomDataset(Dataset):
    def __init__(self, image_paths, labels, transform=None):
        self.image_paths = image_paths
        self.labels = labels
        self.transform = transform
        
    def __len__(self):
        return len(self.image_paths)
    
    def __getitem__(self, idx):
        image = Image.open(self.image_paths[idx]).convert('RGB')
        label = self.labels[idx]
        
        if self.transform:
            image = self.transform(image)
            
        return image, label

def load_data(immature_dir, mature_dir):
    immature_paths = []
    mature_paths = []
    
    for img_name in os.listdir(immature_dir):
        if img_name.lower().endswith(('.jpg', '.jpeg', '.png')):
            immature_paths.append(os.path.join(immature_dir, img_name))
    
    for img_name in os.listdir(mature_dir):
        if img_name.lower().endswith(('.jpg', '.jpeg', '.png')):
            mature_paths.append(os.path.join(mature_dir, img_name))
    
    all_paths = immature_paths + mature_paths
    all_labels = [0] * len(immature_paths) + [1] * len(mature_paths)
    
    print(f"Immature images: {len(immature_paths)}")
    print(f"Mature images: {len(mature_paths)}")
    print(f"Total images: {len(all_paths)}")
    
    return all_paths, all_labels

def get_transforms():
    train_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.RandomRotation(10),
        transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                           std=[0.229, 0.224, 0.225]),
        transforms.RandomErasing(p=0.5, scale=(0.02, 0.1))
    ])
    
    val_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                           std=[0.229, 0.224, 0.225])
    ])
    
    return train_transform, val_transform

def create_mobilenetv3_model(num_classes=2):
    model = models.mobilenet_v3_large(pretrained=True)
    
    num_features = model.classifier[3].in_features
    
    model.classifier[3] = nn.Sequential(
        nn.Dropout(0.9),
        nn.Linear(num_features, 256),
        nn.ReLU(),
        nn.Dropout(0.5),
        nn.Linear(256, num_classes)
    )
    
    return model

def calculate_metrics(all_labels, all_predictions):
    accuracy = np.mean(np.array(all_labels) == np.array(all_predictions))
    
    precision = precision_score(all_labels, all_predictions, average='weighted')
    recall = recall_score(all_labels, all_predictions, average='weighted')
    f1 = f1_score(all_labels, all_predictions, average='weighted')
    
    precision_per_class = precision_score(all_labels, all_predictions, average=None)
    recall_per_class = recall_score(all_labels, all_predictions, average=None)
    f1_per_class = f1_score(all_labels, all_predictions, average=None)
    
    cm = confusion_matrix(all_labels, all_predictions)
    
    report = classification_report(all_labels, all_predictions, 
                                  target_names=['immature', 'mature'], 
                                  output_dict=True)
    
    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'precision_per_class': precision_per_class,
        'recall_per_class': recall_per_class,
        'f1_per_class': f1_per_class,
        'confusion_matrix': cm,
        'classification_report': report
    }

def train_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    all_predictions = []
    all_labels = []
    
    progress_bar = tqdm(dataloader, desc='Training')
    for images, labels in progress_bar:
        images, labels = images.to(device), labels.to(device)
        
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        
        all_predictions.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
        
        batch_acc = (predicted == labels).sum().item() / labels.size(0)
        progress_bar.set_postfix({'Loss': running_loss/len(dataloader), 'Acc': batch_acc})
    
    epoch_loss = running_loss / len(dataloader)
    
    metrics = calculate_metrics(all_labels, all_predictions)
    metrics['loss'] = epoch_loss
    
    return epoch_loss, metrics

def evaluate_model(model, dataloader, criterion, device, dataset_name="Dataset"):
    model.eval()
    running_loss = 0.0
    all_predictions = []
    all_labels = []
    
    with torch.no_grad():
        for images, labels in dataloader:
            images, labels = images.to(device), labels.to(device)
            
            outputs = model(images)
            loss = criterion(outputs, labels)
            
            running_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            
            all_predictions.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    
    epoch_loss = running_loss / len(dataloader)
    
    metrics = calculate_metrics(all_labels, all_predictions)
    metrics['loss'] = epoch_loss
    
    return epoch_loss, metrics

def print_detailed_metrics(metrics, dataset_name="Dataset"):
    print(f"\n{dataset_name} Detailed Metrics:")
    print("-" * 50)
    print(f"Loss: {metrics['loss']:.4f}")
    print(f"Accuracy: {metrics['accuracy']:.4f}")
    print(f"Precision: {metrics['precision']:.4f}")
    print(f"Recall: {metrics['recall']:.4f}")
    print(f"F1-Score: {metrics['f1']:.4f}")
    
    print(f"\nPer-class Metrics:")
    print(f"  Immature (0): Precision={metrics['precision_per_class'][0]:.4f}, "
          f"Recall={metrics['recall_per_class'][0]:.4f}, F1={metrics['f1_per_class'][0]:.4f}")
    print(f"  Mature (1): Precision={metrics['precision_per_class'][1]:.4f}, "
          f"Recall={metrics['recall_per_class'][1]:.4f}, F1={metrics['f1_per_class'][1]:.4f}")
    
    print(f"\nConfusion Matrix:")
    print(metrics['confusion_matrix'])

def export_results_to_excel(fold_results, test_results, final_train_results, filename='training_results.xlsx'):
    all_results = []
    
    for fold_result in fold_results:
        fold_data = {
            'Fold': fold_result['fold'],
            'Dataset': 'Validation',
            'Loss': fold_result['val_loss'],
            'Accuracy': fold_result['val_accuracy'],
            'Precision': fold_result['val_precision'],
            'Recall': fold_result['val_recall'],
            'F1_Score': fold_result['val_f1'],
            'Precision_Class0': fold_result['val_precision_per_class'][0],
            'Precision_Class1': fold_result['val_precision_per_class'][1],
            'Recall_Class0': fold_result['val_recall_per_class'][0],
            'Recall_Class1': fold_result['val_recall_per_class'][1],
            'F1_Class0': fold_result['val_f1_per_class'][0],
            'F1_Class1': fold_result['val_f1_per_class'][1],
            'Train_Loss': fold_result['train_loss'],
            'Train_Accuracy': fold_result['train_accuracy'],
            'Train_Precision': fold_result['train_precision'],
            'Train_Recall': fold_result['train_recall'],
            'Train_F1_Score': fold_result['train_f1']
        }
        all_results.append(fold_data)
    
    final_train_data = {
        'Fold': 'Final',
        'Dataset': 'Train',
        'Loss': final_train_results['loss'],
        'Accuracy': final_train_results['accuracy'],
        'Precision': final_train_results['precision'],
        'Recall': final_train_results['recall'],
        'F1_Score': final_train_results['f1'],
        'Precision_Class0': final_train_results['precision_per_class'][0],
        'Precision_Class1': final_train_results['precision_per_class'][1],
        'Recall_Class0': final_train_results['recall_per_class'][0],
        'Recall_Class1': final_train_results['recall_per_class'][1],
        'F1_Class0': final_train_results['f1_per_class'][0],
        'F1_Class1': final_train_results['f1_per_class'][1],
        'Train_Loss': final_train_results['loss'],
        'Train_Accuracy': final_train_results['accuracy'],
        'Train_Precision': final_train_results['precision'],
        'Train_Recall': final_train_results['recall'],
        'Train_F1_Score': final_train_results['f1']
    }
    all_results.append(final_train_data)
    
    test_data = {
        'Fold': 'Final',
        'Dataset': 'Test',
        'Loss': test_results['loss'],
        'Accuracy': test_results['accuracy'],
        'Precision': test_results['precision'],
        'Recall': test_results['recall'],
        'F1_Score': test_results['f1'],
        'Precision_Class0': test_results['precision_per_class'][0],
        'Precision_Class1': test_results['precision_per_class'][1],
        'Recall_Class0': test_results['recall_per_class'][0],
        'Recall_Class1': test_results['recall_per_class'][1],
        'F1_Class0': test_results['f1_per_class'][0],
        'F1_Class1': test_results['f1_per_class'][1],
        'Train_Loss': final_train_results['loss'],
        'Train_Accuracy': final_train_results['accuracy'],
        'Train_Precision': final_train_results['precision'],
        'Train_Recall': final_train_results['recall'],
        'Train_F1_Score': final_train_results['f1']
    }
    all_results.append(test_data)
    
    df = pd.DataFrame(all_results)
    
    validation_df = df[df['Dataset'] == 'Validation']
    if not validation_df.empty:
        avg_row = {
            'Fold': 'Average',
            'Dataset': 'Validation',
            'Loss': validation_df['Loss'].mean(),
            'Accuracy': validation_df['Accuracy'].mean(),
            'Precision': validation_df['Precision'].mean(),
            'Recall': validation_df['Recall'].mean(),
            'F1_Score': validation_df['F1_Score'].mean(),
            'Precision_Class0': validation_df['Precision_Class0'].mean(),
            'Precision_Class1': validation_df['Precision_Class1'].mean(),
            'Recall_Class0': validation_df['Recall_Class0'].mean(),
            'Recall_Class1': validation_df['Recall_Class1'].mean(),
            'F1_Class0': validation_df['F1_Class0'].mean(),
            'F1_Class1': validation_df['F1_Class1'].mean(),
            'Train_Loss': validation_df['Train_Loss'].mean(),
            'Train_Accuracy': validation_df['Train_Accuracy'].mean(),
            'Train_Precision': validation_df['Train_Precision'].mean(),
            'Train_Recall': validation_df['Train_Recall'].mean(),
            'Train_F1_Score': validation_df['Train_F1_Score'].mean()
        }
        
        df = pd.concat([df, pd.DataFrame([avg_row])], ignore_index=True)
    
    df.to_excel(filename, index=False)
    print(f"\n✓ Results saved to {filename}")
    
    print("\n" + "="*80)
    print("Results Summary:")
    print("="*80)
    if not validation_df.empty:
        print(f"5-fold cross-validation average validation accuracy: {validation_df['Accuracy'].mean():.4f}")
    print(f"Final training set accuracy: {final_train_results['accuracy']:.4f}")
    print(f"Test set accuracy: {test_results['accuracy']:.4f}")
    print(f"Test set F1 score: {test_results['f1']:.4f}")
    
    return df

def main():
    immature_dir = r"E:\TSG\jupyterlab\machine learning image\augmented_dataset\immature"
    mature_dir = r"E:\TSG\jupyterlab\machine learning image\augmented_dataset\mature"
    
    print("Loading data...")
    all_paths, all_labels = load_data(immature_dir, mature_dir)
    
    print("\nSplitting data into train and test sets...")
    train_paths, test_paths, train_labels, test_labels = train_test_split(
        all_paths, all_labels, test_size=0.2, random_state=42, stratify=all_labels
    )
    
    print(f"Train set size: {len(train_paths)}")
    print(f"Test set size: {len(test_paths)}")
    
    train_transform, val_transform = get_transforms()
    
    train_dataset = CustomDataset(train_paths, train_labels, train_transform)
    test_dataset = CustomDataset(test_paths, test_labels, val_transform)
    
    device = torch.device("cuda")
    print(f"\nUsing device: {device}")
    
    print("\nStarting 5-fold cross validation...")
    kfold = KFold(n_splits=5, shuffle=True, random_state=42)
    fold_results = []
    
    for fold, (train_idx, val_idx) in enumerate(kfold.split(train_dataset)):
        print(f"\n{'='*60}")
        print(f"Fold {fold+1}/5")
        print(f"{'='*60}")
        
        train_subsampler = SubsetRandomSampler(train_idx)
        val_subsampler = SubsetRandomSampler(val_idx)
        
        train_loader = DataLoader(train_dataset, batch_size=32, sampler=train_subsampler)
        val_loader = DataLoader(train_dataset, batch_size=32, sampler=val_subsampler)
        
        model = create_mobilenetv3_model(num_classes=2)
        model = model.to(device)
        
        criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
        optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=5e-4)
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', patience=2)
        
        num_epochs = 20
        best_val_acc = 0
        best_model_state = None
        best_train_metrics = None
        best_val_metrics = None
        best_train_loss = None
        
        for epoch in range(num_epochs):
            print(f"\nEpoch {epoch+1}/{num_epochs}")
            
            train_loss, train_metrics = train_epoch(model, train_loader, criterion, optimizer, device)
            
            val_loss, val_metrics = evaluate_model(model, val_loader, criterion, device, "Validation")
            
            scheduler.step(val_loss)
            
            print(f"Train - Loss: {train_loss:.4f}, Acc: {train_metrics['accuracy']:.4f}, "
                  f"F1: {train_metrics['f1']:.4f}")
            print(f"Val   - Loss: {val_loss:.4f}, Acc: {val_metrics['accuracy']:.4f}, "
                  f"F1: {val_metrics['f1']:.4f}")
            
            if val_metrics['accuracy'] > best_val_acc:
                best_val_acc = val_metrics['accuracy']
                best_model_state = model.state_dict().copy()
                best_train_metrics = train_metrics
                best_val_metrics = val_metrics
                best_train_loss = train_loss
        
        print_detailed_metrics(best_train_metrics, f"Fold {fold+1} - Best Training Set")
        print_detailed_metrics(best_val_metrics, f"Fold {fold+1} - Best Validation Set")
        
        fold_results.append({
            'fold': fold + 1,
            'best_val_acc': best_val_acc,
            'val_loss': best_val_metrics['loss'],
            'val_accuracy': best_val_metrics['accuracy'],
            'val_precision': best_val_metrics['precision'],
            'val_recall': best_val_metrics['recall'],
            'val_f1': best_val_metrics['f1'],
            'val_precision_per_class': best_val_metrics['precision_per_class'],
            'val_recall_per_class': best_val_metrics['recall_per_class'],
            'val_f1_per_class': best_val_metrics['f1_per_class'],
            'train_loss': best_train_loss,
            'train_accuracy': best_train_metrics['accuracy'],
            'train_precision': best_train_metrics['precision'],
            'train_recall': best_train_metrics['recall'],
            'train_f1': best_train_metrics['f1'],
            'model_state': best_model_state
        })
    
    print("\n" + "="*60)
    print("Cross-validation Results Summary:")
    print("="*60)
    for result in fold_results:
        print(f"Fold {result['fold']}: "
              f"Val Acc = {result['best_val_acc']:.4f}, "
              f"Val F1 = {result['val_f1']:.4f}, "
              f"Val Loss = {result['val_loss']:.4f}")
    
    avg_val_acc = np.mean([r['best_val_acc'] for r in fold_results])
    avg_val_f1 = np.mean([r['val_f1'] for r in fold_results])
    avg_val_loss = np.mean([r['val_loss'] for r in fold_results])
    print(f"\nAverage validation accuracy: {avg_val_acc:.4f}")
    print(f"Average validation F1 score: {avg_val_f1:.4f}")
    print(f"Average validation Loss: {avg_val_loss:.4f}")
    
    print("\n" + "="*60)
    print("Evaluating final model on test set...")
    print("="*60)
    
    print("\nTraining final model on entire training set...")
    final_train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)
    
    final_model = create_mobilenetv3_model(num_classes=2)
    final_model = final_model.to(device)
    
    final_criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
    final_optimizer = optim.Adam(final_model.parameters(), lr=0.001, weight_decay=5e-4)
    final_scheduler = optim.lr_scheduler.ReduceLROnPlateau(final_optimizer, mode='min', patience=2)
    
    num_final_epochs = 15
    best_test_acc = 0
    best_test_metrics = None
    best_final_train_metrics = None
    best_final_train_loss = None
    
    for epoch in range(num_final_epochs):
        print(f"\nFinal Model - Epoch {epoch+1}/{num_final_epochs}")
        
        train_loss, train_metrics = train_epoch(final_model, final_train_loader, final_criterion, final_optimizer, device)
        
        test_loss, test_metrics = evaluate_model(final_model, test_loader, final_criterion, device, "Test")
        
        final_scheduler.step(test_loss)
        
        print(f"Training Set - Loss: {train_loss:.4f}, Acc: {train_metrics['accuracy']:.4f}, "
              f"F1: {train_metrics['f1']:.4f}")
        print(f"Test Set     - Loss: {test_loss:.4f}, Acc: {test_metrics['accuracy']:.4f}, "
              f"F1: {test_metrics['f1']:.4f}")
        
        if test_metrics['accuracy'] > best_test_acc:
            best_test_acc = test_metrics['accuracy']
            best_test_metrics = test_metrics
            best_final_train_metrics = train_metrics
            best_final_train_loss = train_loss
            torch.save(final_model.state_dict(), 'best_mobilenetv3_model.pth')
    
    print("\n" + "="*60)
    print("Final Training Set Detailed Metrics:")
    print("="*60)
    print_detailed_metrics(best_final_train_metrics, "Final Training Set")
    
    print("\n" + "="*60)
    print("Test Set Detailed Metrics:")
    print("="*60)
    print_detailed_metrics(best_test_metrics, "Test Set")
    
    export_results_to_excel(fold_results, best_test_metrics, best_final_train_metrics, 'mobilenetv3_training_results.xlsx')
    
    def predict_single_image(image_path, model_path='best_mobilenetv3_model.pth'):
        model = create_mobilenetv3_model(num_classes=2)
        model.load_state_dict(torch.load(model_path, map_location=device))
        model = model.to(device)
        model.eval()
        
        image = Image.open(image_path).convert('RGB')
        transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                               std=[0.229, 0.224, 0.225])
        ])
        
        image_tensor = transform(image).unsqueeze(0).to(device)
        
        with torch.no_grad():
            outputs = model(image_tensor)
            probabilities = torch.softmax(outputs, dim=1)
            _, predicted = torch.max(outputs, 1)
            
            class_names = ['immature', 'mature']
            result = class_names[predicted.item()]
            confidence = probabilities[0][predicted.item()].item()
            
        return result, confidence
    
    print("\n" + "="*60)
    print("Model ready for prediction!")
    print("Use predict_single_image('path/to/image.jpg') to classify new images.")
    print("="*60)
    
    with open('mobilenetv3_classifier_info.pkl', 'wb') as f:
        pickle.dump({
            'train_paths': train_paths,
            'test_paths': test_paths,
            'train_labels': train_labels,
            'test_labels': test_labels,
            'class_names': ['immature', 'mature'],
            'normalization_mean': [0.485, 0.456, 0.406],
            'normalization_std': [0.229, 0.224, 0.225],
            'fold_results': fold_results,
            'test_results': best_test_metrics,
            'final_train_results': best_final_train_metrics
        }, f)
    
    return final_model, best_test_metrics, best_final_train_metrics

if __name__ == "__main__":
    model, test_results, train_results = main()

✓ GPU available: NVIDIA GeForce RTX 5070 Ti
  Memory: 17.09 GB
  CUDA version: 11.8
Loading data...
Immature images: 2980
Mature images: 1260
Total images: 4240

Splitting data into train and test sets...
Train set size: 3392
Test set size: 848

Using device: cuda

Starting 5-fold cross validation...

Fold 1/5

Epoch 1/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.598, Acc=0.92]


Train - Loss: 0.5980, Acc: 0.7394, F1: 0.7341
Val   - Loss: 0.5281, Acc: 0.7349, F1: 0.6765

Epoch 2/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.484, Acc=0.88]


Train - Loss: 0.4840, Acc: 0.8301, F1: 0.8225
Val   - Loss: 0.6000, Acc: 0.7216, F1: 0.7275

Epoch 3/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.456, Acc=0.88]


Train - Loss: 0.4562, Acc: 0.8478, F1: 0.8426
Val   - Loss: 0.5422, Acc: 0.7393, F1: 0.7242

Epoch 4/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.441, Acc=0.88]


Train - Loss: 0.4409, Acc: 0.8526, F1: 0.8481
Val   - Loss: 0.5503, Acc: 0.7732, F1: 0.7426

Epoch 5/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.408, Acc=0.92]


Train - Loss: 0.4083, Acc: 0.8710, F1: 0.8653
Val   - Loss: 0.4393, Acc: 0.8424, F1: 0.8325

Epoch 6/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.406, Acc=0.88]


Train - Loss: 0.4058, Acc: 0.8765, F1: 0.8734
Val   - Loss: 0.4260, Acc: 0.8306, F1: 0.8110

Epoch 7/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.388, Acc=0.92]


Train - Loss: 0.3876, Acc: 0.8868, F1: 0.8834
Val   - Loss: 0.4342, Acc: 0.8409, F1: 0.8275

Epoch 8/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.379, Acc=0.72]


Train - Loss: 0.3788, Acc: 0.8824, F1: 0.8789
Val   - Loss: 0.4143, Acc: 0.8630, F1: 0.8534

Epoch 9/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.383, Acc=0.96]


Train - Loss: 0.3832, Acc: 0.8913, F1: 0.8889
Val   - Loss: 0.4014, Acc: 0.8675, F1: 0.8580

Epoch 10/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.12s/it, Loss=0.386, Acc=0.88]


Train - Loss: 0.3862, Acc: 0.8891, F1: 0.8866
Val   - Loss: 0.3830, Acc: 0.8925, F1: 0.8903

Epoch 11/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.12s/it, Loss=0.365, Acc=0.8]


Train - Loss: 0.3647, Acc: 0.8997, F1: 0.8977
Val   - Loss: 0.3541, Acc: 0.8940, F1: 0.8927

Epoch 12/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.11s/it, Loss=0.377, Acc=0.96]


Train - Loss: 0.3768, Acc: 0.8916, F1: 0.8900
Val   - Loss: 0.3551, Acc: 0.8954, F1: 0.8942

Epoch 13/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.375, Acc=0.96]


Train - Loss: 0.3754, Acc: 0.8927, F1: 0.8910
Val   - Loss: 0.3552, Acc: 0.8851, F1: 0.8830

Epoch 14/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.12s/it, Loss=0.369, Acc=0.88]


Train - Loss: 0.3686, Acc: 0.8879, F1: 0.8857
Val   - Loss: 0.3596, Acc: 0.9175, F1: 0.9164

Epoch 15/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.13s/it, Loss=0.361, Acc=0.96]


Train - Loss: 0.3605, Acc: 0.9001, F1: 0.8985
Val   - Loss: 0.3450, Acc: 0.9087, F1: 0.9078

Epoch 16/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.12s/it, Loss=0.351, Acc=0.84]


Train - Loss: 0.3515, Acc: 0.9071, F1: 0.9055
Val   - Loss: 0.3429, Acc: 0.9057, F1: 0.9049

Epoch 17/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.12s/it, Loss=0.36, Acc=0.88]


Train - Loss: 0.3599, Acc: 0.9023, F1: 0.9004
Val   - Loss: 0.3391, Acc: 0.9043, F1: 0.9027

Epoch 18/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.12s/it, Loss=0.354, Acc=0.92]


Train - Loss: 0.3544, Acc: 0.9016, F1: 0.8995
Val   - Loss: 0.3410, Acc: 0.9131, F1: 0.9124

Epoch 19/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.12s/it, Loss=0.346, Acc=0.88]


Train - Loss: 0.3463, Acc: 0.9163, F1: 0.9148
Val   - Loss: 0.3321, Acc: 0.9116, F1: 0.9107

Epoch 20/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.11s/it, Loss=0.345, Acc=0.88]


Train - Loss: 0.3452, Acc: 0.9141, F1: 0.9128
Val   - Loss: 0.3317, Acc: 0.9146, F1: 0.9131

Fold 1 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3686
Accuracy: 0.8879
Precision: 0.8862
Recall: 0.8879
F1-Score: 0.8857

Per-class Metrics:
  Immature (0): Precision=0.9008, Recall=0.9459, F1=0.9228
  Mature (1): Precision=0.8506, Recall=0.7475, F1=0.7957

Confusion Matrix:
[[1817  104]
 [ 200  592]]

Fold 1 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3596
Accuracy: 0.9175
Precision: 0.9171
Recall: 0.9175
F1-Score: 0.9164

Per-class Metrics:
  Immature (0): Precision=0.9213, Recall=0.9611, F1=0.9408
  Mature (1): Precision=0.9082, Recall=0.8241, F1=0.8641

Confusion Matrix:
[[445  18]
 [ 38 178]]

Fold 2/5

Epoch 1/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.594, Acc=0.8]


Train - Loss: 0.5938, Acc: 0.7320, F1: 0.7217
Val   - Loss: 0.5798, Acc: 0.6657, F1: 0.6699

Epoch 2/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.493, Acc=0.8]


Train - Loss: 0.4927, Acc: 0.8257, F1: 0.8199
Val   - Loss: 0.5951, Acc: 0.7275, F1: 0.6886

Epoch 3/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.456, Acc=0.92]


Train - Loss: 0.4558, Acc: 0.8456, F1: 0.8398
Val   - Loss: 0.5958, Acc: 0.6937, F1: 0.6772

Epoch 4/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.09s/it, Loss=0.45, Acc=0.88]


Train - Loss: 0.4498, Acc: 0.8511, F1: 0.8453
Val   - Loss: 0.5765, Acc: 0.7261, F1: 0.6669

Epoch 5/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.429, Acc=0.84]


Train - Loss: 0.4294, Acc: 0.8621, F1: 0.8580
Val   - Loss: 0.5899, Acc: 0.7349, F1: 0.6912

Epoch 6/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.43, Acc=0.92]


Train - Loss: 0.4296, Acc: 0.8577, F1: 0.8527
Val   - Loss: 0.5567, Acc: 0.7025, F1: 0.5921

Epoch 7/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.413, Acc=0.88]


Train - Loss: 0.4130, Acc: 0.8717, F1: 0.8687
Val   - Loss: 0.4736, Acc: 0.8571, F1: 0.8580

Epoch 8/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.414, Acc=0.88]


Train - Loss: 0.4141, Acc: 0.8684, F1: 0.8655
Val   - Loss: 0.4925, Acc: 0.7835, F1: 0.7873

Epoch 9/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.401, Acc=0.84]


Train - Loss: 0.4012, Acc: 0.8809, F1: 0.8783
Val   - Loss: 0.5487, Acc: 0.7761, F1: 0.7795

Epoch 10/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.399, Acc=0.8]


Train - Loss: 0.3993, Acc: 0.8765, F1: 0.8736
Val   - Loss: 0.5694, Acc: 0.8439, F1: 0.8311

Epoch 11/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.38, Acc=0.84]


Train - Loss: 0.3802, Acc: 0.8920, F1: 0.8890
Val   - Loss: 0.4236, Acc: 0.8837, F1: 0.8852

Epoch 12/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.361, Acc=0.88]


Train - Loss: 0.3611, Acc: 0.9042, F1: 0.9025
Val   - Loss: 0.3852, Acc: 0.9013, F1: 0.9018

Epoch 13/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.354, Acc=0.96]


Train - Loss: 0.3542, Acc: 0.9104, F1: 0.9089
Val   - Loss: 0.3789, Acc: 0.8984, F1: 0.8984

Epoch 14/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.347, Acc=0.92]


Train - Loss: 0.3465, Acc: 0.9060, F1: 0.9047
Val   - Loss: 0.3636, Acc: 0.8895, F1: 0.8847

Epoch 15/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.345, Acc=0.88]


Train - Loss: 0.3450, Acc: 0.9134, F1: 0.9119
Val   - Loss: 0.3635, Acc: 0.8999, F1: 0.9000

Epoch 16/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.12s/it, Loss=0.349, Acc=0.84]


Train - Loss: 0.3489, Acc: 0.9104, F1: 0.9092
Val   - Loss: 0.3508, Acc: 0.9028, F1: 0.8998

Epoch 17/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.343, Acc=0.92]


Train - Loss: 0.3429, Acc: 0.9149, F1: 0.9138
Val   - Loss: 0.3466, Acc: 0.8984, F1: 0.8968

Epoch 18/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.12s/it, Loss=0.343, Acc=0.88]


Train - Loss: 0.3431, Acc: 0.9156, F1: 0.9146
Val   - Loss: 0.3326, Acc: 0.9308, F1: 0.9297

Epoch 19/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.12s/it, Loss=0.343, Acc=0.92]


Train - Loss: 0.3431, Acc: 0.9141, F1: 0.9126
Val   - Loss: 0.3358, Acc: 0.9146, F1: 0.9139

Epoch 20/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.13s/it, Loss=0.347, Acc=0.88]


Train - Loss: 0.3472, Acc: 0.9097, F1: 0.9087
Val   - Loss: 0.3403, Acc: 0.9205, F1: 0.9205

Fold 2 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3431
Accuracy: 0.9156
Precision: 0.9147
Recall: 0.9156
F1-Score: 0.9146

Per-class Metrics:
  Immature (0): Precision=0.9270, Recall=0.9556, F1=0.9411
  Mature (1): Precision=0.8851, Recall=0.8198, F1=0.8512

Confusion Matrix:
[[1829   85]
 [ 144  655]]

Fold 2 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3326
Accuracy: 0.9308
Precision: 0.9308
Recall: 0.9308
F1-Score: 0.9297

Per-class Metrics:
  Immature (0): Precision=0.9308, Recall=0.9723, F1=0.9511
  Mature (1): Precision=0.9309, Recall=0.8373, F1=0.8816

Confusion Matrix:
[[457  13]
 [ 34 175]]

Fold 3/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.12s/it, Loss=0.614, Acc=0.885]


Train - Loss: 0.6143, Acc: 0.7296, F1: 0.7230
Val   - Loss: 0.5609, Acc: 0.7168, F1: 0.5986

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.477, Acc=0.923]


Train - Loss: 0.4766, Acc: 0.8206, F1: 0.8134
Val   - Loss: 0.5655, Acc: 0.7611, F1: 0.7188

Epoch 3/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.46, Acc=0.923]


Train - Loss: 0.4597, Acc: 0.8397, F1: 0.8352
Val   - Loss: 0.5588, Acc: 0.7448, F1: 0.6595

Epoch 4/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.43, Acc=0.731]


Train - Loss: 0.4303, Acc: 0.8640, F1: 0.8608
Val   - Loss: 0.5205, Acc: 0.7699, F1: 0.7781

Epoch 5/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.416, Acc=0.846]


Train - Loss: 0.4159, Acc: 0.8762, F1: 0.8737
Val   - Loss: 0.4907, Acc: 0.8186, F1: 0.8233

Epoch 6/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.419, Acc=0.808]


Train - Loss: 0.4186, Acc: 0.8604, F1: 0.8568
Val   - Loss: 0.5213, Acc: 0.7507, F1: 0.7610

Epoch 7/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.09s/it, Loss=0.414, Acc=0.885]


Train - Loss: 0.4136, Acc: 0.8699, F1: 0.8669
Val   - Loss: 0.5277, Acc: 0.7655, F1: 0.7768

Epoch 8/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.417, Acc=0.885]


Train - Loss: 0.4175, Acc: 0.8629, F1: 0.8597
Val   - Loss: 0.5410, Acc: 0.7670, F1: 0.7720

Epoch 9/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.401, Acc=0.846]


Train - Loss: 0.4007, Acc: 0.8784, F1: 0.8753
Val   - Loss: 0.4311, Acc: 0.8658, F1: 0.8608

Epoch 10/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.376, Acc=0.846]


Train - Loss: 0.3757, Acc: 0.8968, F1: 0.8952
Val   - Loss: 0.3851, Acc: 0.8938, F1: 0.8913

Epoch 11/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.362, Acc=0.923]


Train - Loss: 0.3623, Acc: 0.9009, F1: 0.8999
Val   - Loss: 0.3781, Acc: 0.8761, F1: 0.8740

Epoch 12/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.359, Acc=0.846]


Train - Loss: 0.3591, Acc: 0.9038, F1: 0.9023
Val   - Loss: 0.3774, Acc: 0.8805, F1: 0.8788

Epoch 13/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.356, Acc=0.769]


Train - Loss: 0.3557, Acc: 0.9083, F1: 0.9067
Val   - Loss: 0.3686, Acc: 0.8894, F1: 0.8887

Epoch 14/20


Training: 100%|█████████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.355, Acc=1]


Train - Loss: 0.3548, Acc: 0.9049, F1: 0.9037
Val   - Loss: 0.3671, Acc: 0.8894, F1: 0.8874

Epoch 15/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.361, Acc=0.731]


Train - Loss: 0.3611, Acc: 0.9013, F1: 0.8999
Val   - Loss: 0.3732, Acc: 0.8805, F1: 0.8781

Epoch 16/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.35, Acc=0.885]


Train - Loss: 0.3503, Acc: 0.9035, F1: 0.9027
Val   - Loss: 0.3814, Acc: 0.8791, F1: 0.8800

Epoch 17/20


Training: 100%|█████████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.11s/it, Loss=0.355, Acc=1]


Train - Loss: 0.3546, Acc: 0.9090, F1: 0.9074
Val   - Loss: 0.3558, Acc: 0.9041, F1: 0.9046

Epoch 18/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.11s/it, Loss=0.348, Acc=0.846]


Train - Loss: 0.3476, Acc: 0.9116, F1: 0.9106
Val   - Loss: 0.3786, Acc: 0.8850, F1: 0.8867

Epoch 19/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.09s/it, Loss=0.348, Acc=0.846]


Train - Loss: 0.3482, Acc: 0.9105, F1: 0.9093
Val   - Loss: 0.3854, Acc: 0.8658, F1: 0.8669

Epoch 20/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.343, Acc=0.962]


Train - Loss: 0.3428, Acc: 0.9178, F1: 0.9170
Val   - Loss: 0.3692, Acc: 0.8820, F1: 0.8835

Fold 3 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3546
Accuracy: 0.9090
Precision: 0.9082
Recall: 0.9090
F1-Score: 0.9074

Per-class Metrics:
  Immature (0): Precision=0.9159, Recall=0.9579, F1=0.9364
  Mature (1): Precision=0.8903, Recall=0.7953, F1=0.8401

Confusion Matrix:
[[1818   80]
 [ 167  649]]

Fold 3 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3558
Accuracy: 0.9041
Precision: 0.9054
Recall: 0.9041
F1-Score: 0.9046

Per-class Metrics:
  Immature (0): Precision=0.9395, Recall=0.9259, F1=0.9326
  Mature (1): Precision=0.8191, Recall=0.8490, F1=0.8338

Confusion Matrix:
[[450  36]
 [ 29 163]]

Fold 4/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.12s/it, Loss=0.609, Acc=0.692]


Train - Loss: 0.6091, Acc: 0.7299, F1: 0.7208
Val   - Loss: 0.5575, Acc: 0.7006, F1: 0.5772

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.493, Acc=0.769]


Train - Loss: 0.4934, Acc: 0.8136, F1: 0.8079
Val   - Loss: 0.5651, Acc: 0.7478, F1: 0.7216

Epoch 3/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.454, Acc=0.962]


Train - Loss: 0.4537, Acc: 0.8497, F1: 0.8442
Val   - Loss: 0.6771, Acc: 0.7257, F1: 0.6440

Epoch 4/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.444, Acc=0.962]


Train - Loss: 0.4438, Acc: 0.8526, F1: 0.8482
Val   - Loss: 0.6291, Acc: 0.7389, F1: 0.6672

Epoch 5/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.406, Acc=0.923]


Train - Loss: 0.4064, Acc: 0.8777, F1: 0.8727
Val   - Loss: 0.5403, Acc: 0.7729, F1: 0.7351

Epoch 6/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.387, Acc=0.923]


Train - Loss: 0.3868, Acc: 0.8817, F1: 0.8784
Val   - Loss: 0.5107, Acc: 0.7891, F1: 0.7544

Epoch 7/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.39, Acc=0.962]


Train - Loss: 0.3900, Acc: 0.8850, F1: 0.8822
Val   - Loss: 0.4131, Acc: 0.8673, F1: 0.8624

Epoch 8/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.11s/it, Loss=0.377, Acc=0.962]


Train - Loss: 0.3767, Acc: 0.8917, F1: 0.8893
Val   - Loss: 0.4060, Acc: 0.8673, F1: 0.8621

Epoch 9/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.38, Acc=0.885]


Train - Loss: 0.3798, Acc: 0.8920, F1: 0.8893
Val   - Loss: 0.3786, Acc: 0.8835, F1: 0.8818

Epoch 10/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.372, Acc=0.885]


Train - Loss: 0.3721, Acc: 0.8946, F1: 0.8922
Val   - Loss: 0.3925, Acc: 0.8791, F1: 0.8754

Epoch 11/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.375, Acc=0.962]


Train - Loss: 0.3747, Acc: 0.9020, F1: 0.8999
Val   - Loss: 0.3833, Acc: 0.8791, F1: 0.8776

Epoch 12/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.373, Acc=0.962]


Train - Loss: 0.3727, Acc: 0.8924, F1: 0.8903
Val   - Loss: 0.3935, Acc: 0.8687, F1: 0.8611

Epoch 13/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.36, Acc=0.885]


Train - Loss: 0.3603, Acc: 0.9046, F1: 0.9021
Val   - Loss: 0.3791, Acc: 0.8835, F1: 0.8798

Epoch 14/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.363, Acc=0.923]


Train - Loss: 0.3630, Acc: 0.9035, F1: 0.9012
Val   - Loss: 0.3569, Acc: 0.8909, F1: 0.8878

Epoch 15/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.12s/it, Loss=0.357, Acc=0.885]


Train - Loss: 0.3567, Acc: 0.9097, F1: 0.9076
Val   - Loss: 0.3664, Acc: 0.8850, F1: 0.8826

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.352, Acc=1]


Train - Loss: 0.3524, Acc: 0.9068, F1: 0.9051
Val   - Loss: 0.3742, Acc: 0.8850, F1: 0.8821

Epoch 17/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.357, Acc=0.885]


Train - Loss: 0.3574, Acc: 0.9042, F1: 0.9022
Val   - Loss: 0.3814, Acc: 0.8850, F1: 0.8830

Epoch 18/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.352, Acc=0.885]


Train - Loss: 0.3519, Acc: 0.9079, F1: 0.9062
Val   - Loss: 0.3664, Acc: 0.8923, F1: 0.8907

Epoch 19/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.363, Acc=0.962]


Train - Loss: 0.3625, Acc: 0.9053, F1: 0.9034
Val   - Loss: 0.3569, Acc: 0.8909, F1: 0.8888

Epoch 20/20


Training: 100%|█████████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.355, Acc=1]


Train - Loss: 0.3553, Acc: 0.9090, F1: 0.9074
Val   - Loss: 0.3586, Acc: 0.8953, F1: 0.8943

Fold 4 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3553
Accuracy: 0.9090
Precision: 0.9081
Recall: 0.9090
F1-Score: 0.9074

Per-class Metrics:
  Immature (0): Precision=0.9163, Recall=0.9581, F1=0.9367
  Mature (1): Precision=0.8886, Recall=0.7925, F1=0.8378

Confusion Matrix:
[[1829   80]
 [ 167  638]]

Fold 4 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3586
Accuracy: 0.8953
Precision: 0.8940
Recall: 0.8953
F1-Score: 0.8943

Per-class Metrics:
  Immature (0): Precision=0.9139, Recall=0.9389, F1=0.9263
  Mature (1): Precision=0.8474, Recall=0.7931, F1=0.8193

Confusion Matrix:
[[446  29]
 [ 42 161]]

Fold 5/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.628, Acc=0.962]


Train - Loss: 0.6278, Acc: 0.7244, F1: 0.7205
Val   - Loss: 0.5752, Acc: 0.7655, F1: 0.7085

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.479, Acc=0.808]


Train - Loss: 0.4786, Acc: 0.8268, F1: 0.8220
Val   - Loss: 0.5586, Acc: 0.7035, F1: 0.7038

Epoch 3/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.46, Acc=0.769]


Train - Loss: 0.4605, Acc: 0.8464, F1: 0.8430
Val   - Loss: 0.5480, Acc: 0.7655, F1: 0.7009

Epoch 4/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.449, Acc=0.885]


Train - Loss: 0.4485, Acc: 0.8526, F1: 0.8482
Val   - Loss: 0.6481, Acc: 0.7773, F1: 0.7356

Epoch 5/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.429, Acc=0.846]


Train - Loss: 0.4292, Acc: 0.8604, F1: 0.8575
Val   - Loss: 0.5362, Acc: 0.7330, F1: 0.7173

Epoch 6/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.42, Acc=0.885]


Train - Loss: 0.4204, Acc: 0.8721, F1: 0.8697
Val   - Loss: 0.5580, Acc: 0.7065, F1: 0.7009

Epoch 7/20


Training: 100%|█████████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.419, Acc=1]


Train - Loss: 0.4194, Acc: 0.8692, F1: 0.8667
Val   - Loss: 0.5086, Acc: 0.7581, F1: 0.7589

Epoch 8/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.412, Acc=0.923]


Train - Loss: 0.4116, Acc: 0.8766, F1: 0.8739
Val   - Loss: 0.5307, Acc: 0.7699, F1: 0.7132

Epoch 9/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.403, Acc=0.769]


Train - Loss: 0.4029, Acc: 0.8762, F1: 0.8743
Val   - Loss: 0.5033, Acc: 0.8068, F1: 0.7779

Epoch 10/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.41, Acc=0.885]


Train - Loss: 0.4097, Acc: 0.8736, F1: 0.8722
Val   - Loss: 0.5383, Acc: 0.7227, F1: 0.7350

Epoch 11/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.393, Acc=0.885]


Train - Loss: 0.3930, Acc: 0.8880, F1: 0.8866
Val   - Loss: 0.5276, Acc: 0.7625, F1: 0.7746

Epoch 12/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.404, Acc=0.962]


Train - Loss: 0.4041, Acc: 0.8762, F1: 0.8741
Val   - Loss: 0.5272, Acc: 0.8112, F1: 0.8018

Epoch 13/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.372, Acc=0.885]


Train - Loss: 0.3717, Acc: 0.8998, F1: 0.8980
Val   - Loss: 0.4388, Acc: 0.8142, F1: 0.8193

Epoch 14/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.353, Acc=0.923]


Train - Loss: 0.3530, Acc: 0.9160, F1: 0.9147
Val   - Loss: 0.3980, Acc: 0.8864, F1: 0.8883

Epoch 15/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.354, Acc=0.962]


Train - Loss: 0.3540, Acc: 0.9079, F1: 0.9075
Val   - Loss: 0.3707, Acc: 0.8850, F1: 0.8831

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.353, Acc=0.769]


Train - Loss: 0.3534, Acc: 0.9097, F1: 0.9089
Val   - Loss: 0.3663, Acc: 0.8909, F1: 0.8893

Epoch 17/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.341, Acc=0.923]


Train - Loss: 0.3407, Acc: 0.9219, F1: 0.9214
Val   - Loss: 0.3792, Acc: 0.8923, F1: 0.8901

Epoch 18/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.346, Acc=0.885]


Train - Loss: 0.3461, Acc: 0.9164, F1: 0.9152
Val   - Loss: 0.3595, Acc: 0.9027, F1: 0.9001

Epoch 19/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.334, Acc=0.962]


Train - Loss: 0.3342, Acc: 0.9223, F1: 0.9215
Val   - Loss: 0.3533, Acc: 0.8909, F1: 0.8893

Epoch 20/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.335, Acc=0.923]


Train - Loss: 0.3355, Acc: 0.9197, F1: 0.9188
Val   - Loss: 0.3585, Acc: 0.9041, F1: 0.9021

Fold 5 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3355
Accuracy: 0.9197
Precision: 0.9189
Recall: 0.9197
F1-Score: 0.9188

Per-class Metrics:
  Immature (0): Precision=0.9297, Recall=0.9572, F1=0.9433
  Mature (1): Precision=0.8940, Recall=0.8329, F1=0.8624

Confusion Matrix:
[[1813   81]
 [ 137  683]]

Fold 5 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3585
Accuracy: 0.9041
Precision: 0.9027
Recall: 0.9041
F1-Score: 0.9021

Per-class Metrics:
  Immature (0): Precision=0.9142, Recall=0.9571, F1=0.9352
  Mature (1): Precision=0.8727, Recall=0.7660, F1=0.8159

Confusion Matrix:
[[469  21]
 [ 44 144]]

Cross-validation Results Summary:
Fold 1: Val Acc = 0.9175, Val F1 = 0.9164, Val Loss = 0.3596
Fold 2: Val Acc = 0.9308, Val F1 = 0.9297, Val Loss = 0.3326
Fold 3: Val Acc = 0.9041, Val F1 = 

Training: 100%|███████████████████████████████████████████████| 106/106 [05:29<00:00,  3.11s/it, Loss=0.583, Acc=0.812]


Training Set - Loss: 0.5830, Acc: 0.7521, F1: 0.7461
Test Set     - Loss: 0.5146, Acc: 0.8267, F1: 0.8038

Final Model - Epoch 2/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:29<00:00,  3.11s/it, Loss=0.484, Acc=0.812]


Training Set - Loss: 0.4841, Acc: 0.8320, F1: 0.8240
Test Set     - Loss: 0.4948, Acc: 0.7972, F1: 0.7799

Final Model - Epoch 3/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:30<00:00,  3.12s/it, Loss=0.457, Acc=0.812]


Training Set - Loss: 0.4567, Acc: 0.8502, F1: 0.8451
Test Set     - Loss: 0.5103, Acc: 0.7759, F1: 0.7236

Final Model - Epoch 4/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:30<00:00,  3.12s/it, Loss=0.437, Acc=0.812]


Training Set - Loss: 0.4367, Acc: 0.8541, F1: 0.8496
Test Set     - Loss: 0.6020, Acc: 0.6545, F1: 0.6677

Final Model - Epoch 5/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:31<00:00,  3.12s/it, Loss=0.423, Acc=0.906]


Training Set - Loss: 0.4232, Acc: 0.8597, F1: 0.8561
Test Set     - Loss: 0.5972, Acc: 0.7818, F1: 0.7635

Final Model - Epoch 6/15


Training: 100%|█████████████████████████████████████████████████| 106/106 [05:27<00:00,  3.09s/it, Loss=0.4, Acc=0.812]


Training Set - Loss: 0.4000, Acc: 0.8815, F1: 0.8786
Test Set     - Loss: 0.3942, Acc: 0.8915, F1: 0.8921

Final Model - Epoch 7/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:28<00:00,  3.10s/it, Loss=0.378, Acc=0.906]


Training Set - Loss: 0.3783, Acc: 0.8930, F1: 0.8912
Test Set     - Loss: 0.3525, Acc: 0.9151, F1: 0.9137

Final Model - Epoch 8/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:28<00:00,  3.10s/it, Loss=0.373, Acc=0.875]


Training Set - Loss: 0.3731, Acc: 0.8942, F1: 0.8927
Test Set     - Loss: 0.3278, Acc: 0.9316, F1: 0.9302

Final Model - Epoch 9/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:29<00:00,  3.11s/it, Loss=0.366, Acc=0.875]


Training Set - Loss: 0.3660, Acc: 0.8950, F1: 0.8928
Test Set     - Loss: 0.3263, Acc: 0.9233, F1: 0.9218

Final Model - Epoch 10/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:28<00:00,  3.10s/it, Loss=0.361, Acc=0.969]


Training Set - Loss: 0.3613, Acc: 0.9021, F1: 0.9006
Test Set     - Loss: 0.3416, Acc: 0.9175, F1: 0.9175

Final Model - Epoch 11/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:29<00:00,  3.11s/it, Loss=0.357, Acc=0.906]


Training Set - Loss: 0.3572, Acc: 0.9060, F1: 0.9043
Test Set     - Loss: 0.3326, Acc: 0.9292, F1: 0.9289

Final Model - Epoch 12/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:29<00:00,  3.11s/it, Loss=0.355, Acc=0.969]


Training Set - Loss: 0.3546, Acc: 0.9060, F1: 0.9040
Test Set     - Loss: 0.3207, Acc: 0.9281, F1: 0.9268

Final Model - Epoch 13/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:29<00:00,  3.10s/it, Loss=0.362, Acc=0.906]


Training Set - Loss: 0.3622, Acc: 0.8965, F1: 0.8951
Test Set     - Loss: 0.3416, Acc: 0.9175, F1: 0.9148

Final Model - Epoch 14/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:29<00:00,  3.11s/it, Loss=0.355, Acc=0.906]


Training Set - Loss: 0.3547, Acc: 0.9036, F1: 0.9022
Test Set     - Loss: 0.3268, Acc: 0.9281, F1: 0.9278

Final Model - Epoch 15/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:28<00:00,  3.10s/it, Loss=0.346, Acc=0.906]


Training Set - Loss: 0.3458, Acc: 0.9133, F1: 0.9122
Test Set     - Loss: 0.3576, Acc: 0.9151, F1: 0.9153

Final Training Set Detailed Metrics:

Final Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3731
Accuracy: 0.8942
Precision: 0.8927
Recall: 0.8942
F1-Score: 0.8927

Per-class Metrics:
  Immature (0): Precision=0.9098, Recall=0.9430, F1=0.9261
  Mature (1): Precision=0.8523, Recall=0.7788, F1=0.8139

Confusion Matrix:
[[2248  136]
 [ 223  785]]

Test Set Detailed Metrics:

Test Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3278
Accuracy: 0.9316
Precision: 0.9321
Recall: 0.9316
F1-Score: 0.9302

Per-class Metrics:
  Immature (0): Precision=0.9283, Recall=0.9782, F1=0.9526
  Mature (1): Precision=0.9409, Recall=0.8214, F1=0.8771

Confusion Matrix:
[[583  13]
 [ 45 207]]

✓ Results saved to mobilenetv3_training_results.xlsx

Results Summary:
5-fold cross-validation average validation accuracy: 0.9104
Final tr