In [2]:
import os
import sys
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset, SubsetRandomSampler
from torchvision import transforms, models
from PIL import Image
import numpy as np
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
from tqdm import tqdm
import warnings
import pandas as pd
import pickle
warnings.filterwarnings('ignore')

def check_gpu_available():
    if not torch.cuda.is_available():
        print("Error: No available GPU device detected.")
        print("Please ensure:")
        print("1. CUDA and cuDNN are installed")
        print("2. A GPU-compatible PyTorch version is installed")
        print("3. The graphics card driver is up to date")
        print("\nProgram requires GPU for training, exiting now...")
        sys.exit(1)
    
    print(f"✓ GPU available: {torch.cuda.get_device_name(0)}")
    print(f"  Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
    print(f"  CUDA version: {torch.version.cuda}")
    return True

check_gpu_available()

def set_seed(seed=42):
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

class CustomDataset(Dataset):
    def __init__(self, image_paths, labels, transform=None):
        self.image_paths = image_paths
        self.labels = labels
        self.transform = transform
        
    def __len__(self):
        return len(self.image_paths)
    
    def __getitem__(self, idx):
        image = Image.open(self.image_paths[idx]).convert('RGB')
        label = self.labels[idx]
        
        if self.transform:
            image = self.transform(image)
            
        return image, label

def load_data(immature_dir, mature_dir):
    immature_paths = []
    mature_paths = []
    
    for img_name in os.listdir(immature_dir):
        if img_name.lower().endswith(('.jpg', '.jpeg', '.png')):
            immature_paths.append(os.path.join(immature_dir, img_name))
    
    for img_name in os.listdir(mature_dir):
        if img_name.lower().endswith(('.jpg', '.jpeg', '.png')):
            mature_paths.append(os.path.join(mature_dir, img_name))
    
    all_paths = immature_paths + mature_paths
    all_labels = [0] * len(immature_paths) + [1] * len(mature_paths)
    
    print(f"Immature images: {len(immature_paths)}")
    print(f"Mature images: {len(mature_paths)}")
    print(f"Total images: {len(all_paths)}")
    
    return all_paths, all_labels

def get_transforms():
    train_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.RandomRotation(10),
        transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                           std=[0.229, 0.224, 0.225]),
        transforms.RandomErasing(p=0.5, scale=(0.02, 0.1)) 
    ])
    
    val_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                           std=[0.229, 0.224, 0.225])
    ])
    
    return train_transform, val_transform

def create_efficientnet_model(num_classes=2):
    model = models.efficientnet_b0(pretrained=True)
    
    num_features = model.classifier[1].in_features
    
    model.classifier[1] = nn.Sequential(
        nn.Dropout(0.95),   
        nn.Linear(num_features, 256),
        nn.ReLU(),
        nn.Dropout(0.4),  
        nn.Linear(256, num_classes)
    )
    
    return model

def calculate_metrics(all_labels, all_predictions):
    accuracy = np.mean(np.array(all_labels) == np.array(all_predictions))
    
    precision = precision_score(all_labels, all_predictions, average='weighted')
    recall = recall_score(all_labels, all_predictions, average='weighted')
    f1 = f1_score(all_labels, all_predictions, average='weighted')
    
    precision_per_class = precision_score(all_labels, all_predictions, average=None)
    recall_per_class = recall_score(all_labels, all_predictions, average=None)
    f1_per_class = f1_score(all_labels, all_predictions, average=None)
    
    cm = confusion_matrix(all_labels, all_predictions)
    
    report = classification_report(all_labels, all_predictions, 
                                  target_names=['immature', 'mature'], 
                                  output_dict=True)
    
    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'precision_per_class': precision_per_class,
        'recall_per_class': recall_per_class,
        'f1_per_class': f1_per_class,
        'confusion_matrix': cm,
        'classification_report': report
    }

def train_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    all_predictions = []
    all_labels = []
    
    progress_bar = tqdm(dataloader, desc='Training')
    for images, labels in progress_bar:
        images, labels = images.to(device), labels.to(device)
        
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        
        all_predictions.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
        
        batch_acc = (predicted == labels).sum().item() / labels.size(0)
        progress_bar.set_postfix({'Loss': running_loss/len(dataloader), 'Acc': batch_acc})
    
    epoch_loss = running_loss / len(dataloader)
    
    metrics = calculate_metrics(all_labels, all_predictions)
    metrics['loss'] = epoch_loss
    
    return epoch_loss, metrics

def evaluate_model(model, dataloader, criterion, device, dataset_name="Dataset"):
    model.eval()
    running_loss = 0.0
    all_predictions = []
    all_labels = []
    
    with torch.no_grad():
        for images, labels in dataloader:
            images, labels = images.to(device), labels.to(device)
            
            outputs = model(images)
            loss = criterion(outputs, labels)
            
            running_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            
            all_predictions.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    
    epoch_loss = running_loss / len(dataloader)
    
    metrics = calculate_metrics(all_labels, all_predictions)
    metrics['loss'] = epoch_loss
    
    return epoch_loss, metrics

def print_detailed_metrics(metrics, dataset_name="Dataset"):
    print(f"\n{dataset_name} Detailed Metrics:")
    print("-" * 50)
    print(f"Loss: {metrics['loss']:.4f}")
    print(f"Accuracy: {metrics['accuracy']:.4f}")
    print(f"Precision: {metrics['precision']:.4f}")
    print(f"Recall: {metrics['recall']:.4f}")
    print(f"F1-Score: {metrics['f1']:.4f}")
    
    print(f"\nPer-class Metrics:")
    print(f"  Immature (0): Precision={metrics['precision_per_class'][0]:.4f}, "
          f"Recall={metrics['recall_per_class'][0]:.4f}, F1={metrics['f1_per_class'][0]:.4f}")
    print(f"  Mature (1): Precision={metrics['precision_per_class'][1]:.4f}, "
          f"Recall={metrics['recall_per_class'][1]:.4f}, F1={metrics['f1_per_class'][1]:.4f}")
    
    print(f"\nConfusion Matrix:")
    print(metrics['confusion_matrix'])

def export_results_to_excel(fold_results, test_results, final_train_results, filename='training_results.xlsx'):
    all_results = []
    
    for fold_result in fold_results:
        fold_data = {
            'Fold': fold_result['fold'],
            'Dataset': 'Validation',
            'Loss': fold_result['val_loss'],
            'Accuracy': fold_result['val_accuracy'],
            'Precision': fold_result['val_precision'],
            'Recall': fold_result['val_recall'],
            'F1_Score': fold_result['val_f1'],
            'Precision_Class0': fold_result['val_precision_per_class'][0],
            'Precision_Class1': fold_result['val_precision_per_class'][1],
            'Recall_Class0': fold_result['val_recall_per_class'][0],
            'Recall_Class1': fold_result['val_recall_per_class'][1],
            'F1_Class0': fold_result['val_f1_per_class'][0],
            'F1_Class1': fold_result['val_f1_per_class'][1],
            'Train_Loss': fold_result['train_loss'],
            'Train_Accuracy': fold_result['train_accuracy'],
            'Train_Precision': fold_result['train_precision'],
            'Train_Recall': fold_result['train_recall'],
            'Train_F1_Score': fold_result['train_f1']
        }
        all_results.append(fold_data)
    
    final_train_data = {
        'Fold': 'Final',
        'Dataset': 'Train',
        'Loss': final_train_results['loss'],
        'Accuracy': final_train_results['accuracy'],
        'Precision': final_train_results['precision'],
        'Recall': final_train_results['recall'],
        'F1_Score': final_train_results['f1'],
        'Precision_Class0': final_train_results['precision_per_class'][0],
        'Precision_Class1': final_train_results['precision_per_class'][1],
        'Recall_Class0': final_train_results['recall_per_class'][0],
        'Recall_Class1': final_train_results['recall_per_class'][1],
        'F1_Class0': final_train_results['f1_per_class'][0],
        'F1_Class1': final_train_results['f1_per_class'][1],
        'Train_Loss': final_train_results['loss'],
        'Train_Accuracy': final_train_results['accuracy'],
        'Train_Precision': final_train_results['precision'],
        'Train_Recall': final_train_results['recall'],
        'Train_F1_Score': final_train_results['f1']
    }
    all_results.append(final_train_data)
    
    test_data = {
        'Fold': 'Final',
        'Dataset': 'Test',
        'Loss': test_results['loss'],
        'Accuracy': test_results['accuracy'],
        'Precision': test_results['precision'],
        'Recall': test_results['recall'],
        'F1_Score': test_results['f1'],
        'Precision_Class0': test_results['precision_per_class'][0],
        'Precision_Class1': test_results['precision_per_class'][1],
        'Recall_Class0': test_results['recall_per_class'][0],
        'Recall_Class1': test_results['recall_per_class'][1],
        'F1_Class0': test_results['f1_per_class'][0],
        'F1_Class1': test_results['f1_per_class'][1],
        'Train_Loss': final_train_results['loss'],
        'Train_Accuracy': final_train_results['accuracy'],
        'Train_Precision': final_train_results['precision'],
        'Train_Recall': final_train_results['recall'],
        'Train_F1_Score': final_train_results['f1']
    }
    all_results.append(test_data)
    
    df = pd.DataFrame(all_results)
    
    validation_df = df[df['Dataset'] == 'Validation']
    if not validation_df.empty:
        avg_row = {
            'Fold': 'Average',
            'Dataset': 'Validation',
            'Loss': validation_df['Loss'].mean(),
            'Accuracy': validation_df['Accuracy'].mean(),
            'Precision': validation_df['Precision'].mean(),
            'Recall': validation_df['Recall'].mean(),
            'F1_Score': validation_df['F1_Score'].mean(),
            'Precision_Class0': validation_df['Precision_Class0'].mean(),
            'Precision_Class1': validation_df['Precision_Class1'].mean(),
            'Recall_Class0': validation_df['Recall_Class0'].mean(),
            'Recall_Class1': validation_df['Recall_Class1'].mean(),
            'F1_Class0': validation_df['F1_Class0'].mean(),
            'F1_Class1': validation_df['F1_Class1'].mean(),
            'Train_Loss': validation_df['Train_Loss'].mean(),
            'Train_Accuracy': validation_df['Train_Accuracy'].mean(),
            'Train_Precision': validation_df['Train_Precision'].mean(),
            'Train_Recall': validation_df['Train_Recall'].mean(),
            'Train_F1_Score': validation_df['Train_F1_Score'].mean()
        }
        
        df = pd.concat([df, pd.DataFrame([avg_row])], ignore_index=True)
    
    df.to_excel(filename, index=False)
    print(f"\n✓ Results saved to {filename}")
    
    print("\n" + "="*80)
    print("Results Summary:")
    print("="*80)
    if not validation_df.empty:
        print(f"5-fold cross-validation average validation accuracy: {validation_df['Accuracy'].mean():.4f}")
    print(f"Final training set accuracy: {final_train_results['accuracy']:.4f}")
    print(f"Test set accuracy: {test_results['accuracy']:.4f}")
    print(f"Test set F1 score: {test_results['f1']:.4f}")
    
    return df

def main():
    immature_dir = r"E:\TSG\jupyterlab\machine learning image\augmented_dataset\immature"
    mature_dir = r"E:\TSG\jupyterlab\machine learning image\augmented_dataset\mature"
    
    print("Loading data...")
    all_paths, all_labels = load_data(immature_dir, mature_dir)
    
    print("\nSplitting data into train and test sets...")
    train_paths, test_paths, train_labels, test_labels = train_test_split(
        all_paths, all_labels, test_size=0.2, random_state=42, stratify=all_labels
    )
    
    print(f"Train set size: {len(train_paths)}")
    print(f"Test set size: {len(test_paths)}")
    
    train_transform, val_transform = get_transforms()
    
    train_dataset = CustomDataset(train_paths, train_labels, train_transform)
    test_dataset = CustomDataset(test_paths, test_labels, val_transform)
    
    device = torch.device("cuda")
    print(f"\nUsing device: {device}")
    
    print("\nStarting 5-fold cross validation...")
    kfold = KFold(n_splits=5, shuffle=True, random_state=42)
    fold_results = []
    
    for fold, (train_idx, val_idx) in enumerate(kfold.split(train_dataset)):
        print(f"\n{'='*60}")
        print(f"Fold {fold+1}/5")
        print(f"{'='*60}")
        
        train_subsampler = SubsetRandomSampler(train_idx)
        val_subsampler = SubsetRandomSampler(val_idx)
        
        train_loader = DataLoader(train_dataset, batch_size=32, sampler=train_subsampler)
        val_loader = DataLoader(train_dataset, batch_size=32, sampler=val_subsampler)
        
        model = create_efficientnet_model(num_classes=2)
        model = model.to(device)
        
        
        criterion = nn.CrossEntropyLoss(label_smoothing=0.2) 
        optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-3)  
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', patience=2)
        
        num_epochs = 20
        best_val_acc = 0
        best_model_state = None
        best_train_metrics = None
        best_val_metrics = None
        best_train_loss = None
        
        for epoch in range(num_epochs):
            print(f"\nEpoch {epoch+1}/{num_epochs}")
            
            train_loss, train_metrics = train_epoch(model, train_loader, criterion, optimizer, device)
            
            val_loss, val_metrics = evaluate_model(model, val_loader, criterion, device, "Validation")
            
            scheduler.step(val_loss)
            
            print(f"Train - Loss: {train_loss:.4f}, Acc: {train_metrics['accuracy']:.4f}, "
                  f"F1: {train_metrics['f1']:.4f}")
            print(f"Val   - Loss: {val_loss:.4f}, Acc: {val_metrics['accuracy']:.4f}, "
                  f"F1: {val_metrics['f1']:.4f}")
            
            if val_metrics['accuracy'] > best_val_acc:
                best_val_acc = val_metrics['accuracy']
                best_model_state = model.state_dict().copy()
                best_train_metrics = train_metrics
                best_val_metrics = val_metrics
                best_train_loss = train_loss
        
        print_detailed_metrics(best_train_metrics, f"Fold {fold+1} - Best Training Set")
        print_detailed_metrics(best_val_metrics, f"Fold {fold+1} - Best Validation Set")
        
        fold_results.append({
            'fold': fold + 1,
            'best_val_acc': best_val_acc,
            'val_loss': best_val_metrics['loss'],
            'val_accuracy': best_val_metrics['accuracy'],
            'val_precision': best_val_metrics['precision'],
            'val_recall': best_val_metrics['recall'],
            'val_f1': best_val_metrics['f1'],
            'val_precision_per_class': best_val_metrics['precision_per_class'],
            'val_recall_per_class': best_val_metrics['recall_per_class'],
            'val_f1_per_class': best_val_metrics['f1_per_class'],
            'train_loss': best_train_loss,
            'train_accuracy': best_train_metrics['accuracy'],
            'train_precision': best_train_metrics['precision'],
            'train_recall': best_train_metrics['recall'],
            'train_f1': best_train_metrics['f1'],
            'model_state': best_model_state
        })
    
    print("\n" + "="*60)
    print("Cross-validation Results Summary:")
    print("="*60)
    for result in fold_results:
        print(f"Fold {result['fold']}: "
              f"Val Acc = {result['best_val_acc']:.4f}, "
              f"Val F1 = {result['val_f1']:.4f}, "
              f"Val Loss = {result['val_loss']:.4f}")
    
    avg_val_acc = np.mean([r['best_val_acc'] for r in fold_results])
    avg_val_f1 = np.mean([r['val_f1'] for r in fold_results])
    avg_val_loss = np.mean([r['val_loss'] for r in fold_results])
    print(f"\nAverage validation accuracy: {avg_val_acc:.4f}")
    print(f"Average validation F1 score: {avg_val_f1:.4f}")
    print(f"Average validation Loss: {avg_val_loss:.4f}")
    
    print("\n" + "="*60)
    print("Evaluating final model on test set...")
    print("="*60)
    
    print("\nTraining final model on entire training set...")
    final_train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)
    
    final_model = create_efficientnet_model(num_classes=2)
    final_model = final_model.to(device)
    

    final_criterion = nn.CrossEntropyLoss(label_smoothing=0.2)
    final_optimizer = optim.Adam(final_model.parameters(), lr=0.001, weight_decay=1e-3)
    final_scheduler = optim.lr_scheduler.ReduceLROnPlateau(final_optimizer, mode='min', patience=2)
    
    num_final_epochs = 15
    best_test_acc = 0
    best_test_metrics = None
    best_final_train_metrics = None
    best_final_train_loss = None
    
    for epoch in range(num_final_epochs):
        print(f"\nFinal Model - Epoch {epoch+1}/{num_final_epochs}")
        
        train_loss, train_metrics = train_epoch(final_model, final_train_loader, final_criterion, final_optimizer, device)
        
        test_loss, test_metrics = evaluate_model(final_model, test_loader, final_criterion, device, "Test")
        
        final_scheduler.step(test_loss)
        
        print(f"Training Set - Loss: {train_loss:.4f}, Acc: {train_metrics['accuracy']:.4f}, "
              f"F1: {train_metrics['f1']:.4f}")
        print(f"Test Set     - Loss: {test_loss:.4f}, Acc: {test_metrics['accuracy']:.4f}, "
              f"F1: {test_metrics['f1']:.4f}")
        
        if test_metrics['accuracy'] > best_test_acc:
            best_test_acc = test_metrics['accuracy']
            best_test_metrics = test_metrics
            best_final_train_metrics = train_metrics
            best_final_train_loss = train_loss
            torch.save(final_model.state_dict(), 'best_efficientnet_model.pth')
    
    print("\n" + "="*60)
    print("Final Training Set Detailed Metrics:")
    print("="*60)
    print_detailed_metrics(best_final_train_metrics, "Final Training Set")
    
    print("\n" + "="*60)
    print("Test Set Detailed Metrics:")
    print("="*60)
    print_detailed_metrics(best_test_metrics, "Test Set")
    
    export_results_to_excel(fold_results, best_test_metrics, best_final_train_metrics, 'efficientnet_training_results.xlsx')
    
    def predict_single_image(image_path, model_path='best_efficientnet_model.pth'):
        model = create_efficientnet_model(num_classes=2)
        model.load_state_dict(torch.load(model_path, map_location=device))
        model = model.to(device)
        model.eval()
        
        image = Image.open(image_path).convert('RGB')
        transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                               std=[0.229, 0.224, 0.225])
        ])
        
        image_tensor = transform(image).unsqueeze(0).to(device)
        
        with torch.no_grad():
            outputs = model(image_tensor)
            probabilities = torch.softmax(outputs, dim=1)
            _, predicted = torch.max(outputs, 1)
            
            class_names = ['immature', 'mature']
            result = class_names[predicted.item()]
            confidence = probabilities[0][predicted.item()].item()
            
        return result, confidence
    
    print("\n" + "="*60)
    print("Model ready for prediction!")
    print("Use predict_single_image('path/to/image.jpg') to classify new images.")
    print("="*60)
    
    with open('efficientnet_classifier_info.pkl', 'wb') as f:
        pickle.dump({
            'train_paths': train_paths,
            'test_paths': test_paths,
            'train_labels': train_labels,
            'test_labels': test_labels,
            'class_names': ['immature', 'mature'],
            'normalization_mean': [0.485, 0.456, 0.406],
            'normalization_std': [0.229, 0.224, 0.225],
            'fold_results': fold_results,
            'test_results': best_test_metrics,
            'final_train_results': best_final_train_metrics
        }, f)
    
    return final_model, best_test_metrics, best_final_train_metrics

if __name__ == "__main__":
    model, test_results, train_results = main()

✓ GPU available: NVIDIA GeForce RTX 5070 Ti
  Memory: 17.09 GB
  CUDA version: 11.8
Loading data...
Immature images: 2980
Mature images: 1260
Total images: 4240

Splitting data into train and test sets...
Train set size: 3392
Test set size: 848

Using device: cuda

Starting 5-fold cross validation...

Fold 1/5

Epoch 1/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:41<00:00,  3.32s/it, Loss=0.625, Acc=0.84]


Train - Loss: 0.6252, Acc: 0.7228, F1: 0.7183
Val   - Loss: 0.6479, Acc: 0.6362, F1: 0.6441

Epoch 2/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.19s/it, Loss=0.564, Acc=0.8]


Train - Loss: 0.5642, Acc: 0.8013, F1: 0.7980
Val   - Loss: 0.5206, Acc: 0.8321, F1: 0.8310

Epoch 3/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.13s/it, Loss=0.533, Acc=0.72]


Train - Loss: 0.5327, Acc: 0.8360, F1: 0.8312
Val   - Loss: 0.5238, Acc: 0.8321, F1: 0.8257

Epoch 4/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.528, Acc=0.8]


Train - Loss: 0.5282, Acc: 0.8293, F1: 0.8243
Val   - Loss: 0.5135, Acc: 0.8542, F1: 0.8443

Epoch 5/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.14s/it, Loss=0.513, Acc=0.8]


Train - Loss: 0.5132, Acc: 0.8544, F1: 0.8485
Val   - Loss: 0.6305, Acc: 0.7320, F1: 0.7409

Epoch 6/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.508, Acc=0.88]


Train - Loss: 0.5082, Acc: 0.8489, F1: 0.8435
Val   - Loss: 0.5058, Acc: 0.8733, F1: 0.8722

Epoch 7/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.507, Acc=0.96]


Train - Loss: 0.5071, Acc: 0.8585, F1: 0.8546
Val   - Loss: 0.5237, Acc: 0.8527, F1: 0.8443

Epoch 8/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.515, Acc=0.92]


Train - Loss: 0.5148, Acc: 0.8515, F1: 0.8470
Val   - Loss: 0.4862, Acc: 0.8763, F1: 0.8767

Epoch 9/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.14s/it, Loss=0.513, Acc=0.88]


Train - Loss: 0.5129, Acc: 0.8489, F1: 0.8427
Val   - Loss: 0.5149, Acc: 0.8601, F1: 0.8492

Epoch 10/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.489, Acc=0.84]


Train - Loss: 0.4889, Acc: 0.8655, F1: 0.8611
Val   - Loss: 0.5447, Acc: 0.7585, F1: 0.7667

Epoch 11/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.499, Acc=0.84]


Train - Loss: 0.4986, Acc: 0.8614, F1: 0.8577
Val   - Loss: 0.4959, Acc: 0.8557, F1: 0.8574

Epoch 12/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.475, Acc=0.88]


Train - Loss: 0.4748, Acc: 0.8739, F1: 0.8709
Val   - Loss: 0.4515, Acc: 0.8837, F1: 0.8814

Epoch 13/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.463, Acc=0.92]


Train - Loss: 0.4625, Acc: 0.8916, F1: 0.8890
Val   - Loss: 0.4497, Acc: 0.9013, F1: 0.8994

Epoch 14/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.14s/it, Loss=0.462, Acc=0.92]


Train - Loss: 0.4621, Acc: 0.8913, F1: 0.8894
Val   - Loss: 0.4450, Acc: 0.8940, F1: 0.8918

Epoch 15/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.453, Acc=0.76]


Train - Loss: 0.4526, Acc: 0.8983, F1: 0.8954
Val   - Loss: 0.4489, Acc: 0.9043, F1: 0.9033

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.14s/it, Loss=0.455, Acc=1]


Train - Loss: 0.4546, Acc: 0.8961, F1: 0.8937
Val   - Loss: 0.4396, Acc: 0.9028, F1: 0.9030

Epoch 17/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.456, Acc=0.92]


Train - Loss: 0.4558, Acc: 0.8972, F1: 0.8955
Val   - Loss: 0.4557, Acc: 0.8910, F1: 0.8910

Epoch 18/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.448, Acc=0.84]


Train - Loss: 0.4483, Acc: 0.9027, F1: 0.9014
Val   - Loss: 0.4432, Acc: 0.9043, F1: 0.9016

Epoch 19/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.453, Acc=0.8]


Train - Loss: 0.4532, Acc: 0.8916, F1: 0.8900
Val   - Loss: 0.4411, Acc: 0.8969, F1: 0.8947

Epoch 20/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.14s/it, Loss=0.444, Acc=0.96]


Train - Loss: 0.4437, Acc: 0.9016, F1: 0.8992
Val   - Loss: 0.4417, Acc: 0.8969, F1: 0.8943

Fold 1 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4526
Accuracy: 0.8983
Precision: 0.8977
Recall: 0.8983
F1-Score: 0.8954

Per-class Metrics:
  Immature (0): Precision=0.9014, Recall=0.9615, F1=0.9305
  Mature (1): Precision=0.8886, Recall=0.7449, F1=0.8104

Confusion Matrix:
[[1847   74]
 [ 202  590]]

Fold 1 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4489
Accuracy: 0.9043
Precision: 0.9034
Recall: 0.9043
F1-Score: 0.9033

Per-class Metrics:
  Immature (0): Precision=0.9163, Recall=0.9460, F1=0.9309
  Mature (1): Precision=0.8756, Recall=0.8148, F1=0.8441

Confusion Matrix:
[[438  25]
 [ 40 176]]

Fold 2/5

Epoch 1/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.62, Acc=0.76]


Train - Loss: 0.6198, Acc: 0.7409, F1: 0.7361
Val   - Loss: 0.5241, Acc: 0.8306, F1: 0.8280

Epoch 2/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.14s/it, Loss=0.554, Acc=0.76]


Train - Loss: 0.5536, Acc: 0.8128, F1: 0.8082
Val   - Loss: 0.4868, Acc: 0.8733, F1: 0.8715

Epoch 3/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.528, Acc=0.84]


Train - Loss: 0.5284, Acc: 0.8360, F1: 0.8304
Val   - Loss: 0.5068, Acc: 0.8748, F1: 0.8764

Epoch 4/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.14s/it, Loss=0.51, Acc=0.92]


Train - Loss: 0.5101, Acc: 0.8548, F1: 0.8490
Val   - Loss: 0.4870, Acc: 0.8866, F1: 0.8852

Epoch 5/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.14s/it, Loss=0.508, Acc=0.88]


Train - Loss: 0.5080, Acc: 0.8574, F1: 0.8519
Val   - Loss: 0.5287, Acc: 0.8277, F1: 0.8108

Epoch 6/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.486, Acc=0.88]


Train - Loss: 0.4859, Acc: 0.8688, F1: 0.8636
Val   - Loss: 0.4445, Acc: 0.8999, F1: 0.8966

Epoch 7/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.14s/it, Loss=0.473, Acc=0.92]


Train - Loss: 0.4726, Acc: 0.8784, F1: 0.8736
Val   - Loss: 0.4396, Acc: 0.8984, F1: 0.8948

Epoch 8/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.463, Acc=0.88]


Train - Loss: 0.4629, Acc: 0.8975, F1: 0.8953
Val   - Loss: 0.4356, Acc: 0.9072, F1: 0.9053

Epoch 9/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.453, Acc=0.84]


Train - Loss: 0.4527, Acc: 0.8983, F1: 0.8957
Val   - Loss: 0.4444, Acc: 0.8866, F1: 0.8861

Epoch 10/20


Training: 100%|████████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.46, Acc=0.8]


Train - Loss: 0.4598, Acc: 0.8894, F1: 0.8864
Val   - Loss: 0.4381, Acc: 0.8999, F1: 0.8984

Epoch 11/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.452, Acc=0.88]


Train - Loss: 0.4521, Acc: 0.8950, F1: 0.8924
Val   - Loss: 0.4368, Acc: 0.9043, F1: 0.9034

Epoch 12/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.451, Acc=0.96]


Train - Loss: 0.4507, Acc: 0.8957, F1: 0.8944
Val   - Loss: 0.4308, Acc: 0.9161, F1: 0.9145

Epoch 13/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.14s/it, Loss=0.45, Acc=0.68]


Train - Loss: 0.4499, Acc: 0.9023, F1: 0.9006
Val   - Loss: 0.4281, Acc: 0.9116, F1: 0.9094

Epoch 14/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.445, Acc=0.92]


Train - Loss: 0.4447, Acc: 0.9071, F1: 0.9052
Val   - Loss: 0.4371, Acc: 0.9087, F1: 0.9067

Epoch 15/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.447, Acc=0.76]


Train - Loss: 0.4475, Acc: 0.9001, F1: 0.8981
Val   - Loss: 0.4217, Acc: 0.9190, F1: 0.9169

Epoch 16/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.13s/it, Loss=0.448, Acc=0.8]


Train - Loss: 0.4481, Acc: 0.9049, F1: 0.9026
Val   - Loss: 0.4320, Acc: 0.9087, F1: 0.9078

Epoch 17/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.446, Acc=0.84]


Train - Loss: 0.4459, Acc: 0.8975, F1: 0.8955
Val   - Loss: 0.4258, Acc: 0.9116, F1: 0.9099

Epoch 18/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.451, Acc=0.92]


Train - Loss: 0.4506, Acc: 0.9020, F1: 0.8998
Val   - Loss: 0.4236, Acc: 0.9087, F1: 0.9062

Epoch 19/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.438, Acc=0.92]


Train - Loss: 0.4383, Acc: 0.9126, F1: 0.9107
Val   - Loss: 0.4380, Acc: 0.8969, F1: 0.8934

Epoch 20/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.447, Acc=0.96]


Train - Loss: 0.4466, Acc: 0.9027, F1: 0.9004
Val   - Loss: 0.4236, Acc: 0.9190, F1: 0.9169

Fold 2 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4475
Accuracy: 0.9001
Precision: 0.8990
Recall: 0.9001
F1-Score: 0.8981

Per-class Metrics:
  Immature (0): Precision=0.9085, Recall=0.9545, F1=0.9310
  Mature (1): Precision=0.8761, Recall=0.7697, F1=0.8195

Confusion Matrix:
[[1827   87]
 [ 184  615]]

Fold 2 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4217
Accuracy: 0.9190
Precision: 0.9202
Recall: 0.9190
F1-Score: 0.9169

Per-class Metrics:
  Immature (0): Precision=0.9125, Recall=0.9766, F1=0.9435
  Mature (1): Precision=0.9375, Recall=0.7895, F1=0.8571

Confusion Matrix:
[[459  11]
 [ 44 165]]

Fold 3/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.618, Acc=0.808]


Train - Loss: 0.6176, Acc: 0.7347, F1: 0.7311
Val   - Loss: 0.5503, Acc: 0.8319, F1: 0.8321

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.555, Acc=0.692]


Train - Loss: 0.5548, Acc: 0.8099, F1: 0.8059
Val   - Loss: 0.5127, Acc: 0.8422, F1: 0.8439

Epoch 3/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.13s/it, Loss=0.522, Acc=0.885]


Train - Loss: 0.5224, Acc: 0.8419, F1: 0.8373
Val   - Loss: 0.5040, Acc: 0.8584, F1: 0.8486

Epoch 4/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.507, Acc=0.808]


Train - Loss: 0.5071, Acc: 0.8574, F1: 0.8534
Val   - Loss: 0.5242, Acc: 0.8260, F1: 0.8242

Epoch 5/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.13s/it, Loss=0.511, Acc=0.885]


Train - Loss: 0.5111, Acc: 0.8545, F1: 0.8500
Val   - Loss: 0.5569, Acc: 0.7920, F1: 0.7940

Epoch 6/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.14s/it, Loss=0.511, Acc=0.846]


Train - Loss: 0.5106, Acc: 0.8460, F1: 0.8406
Val   - Loss: 0.4994, Acc: 0.8761, F1: 0.8777

Epoch 7/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.489, Acc=0.808]


Train - Loss: 0.4890, Acc: 0.8747, F1: 0.8717
Val   - Loss: 0.5331, Acc: 0.8215, F1: 0.8119

Epoch 8/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.508, Acc=0.808]


Train - Loss: 0.5081, Acc: 0.8456, F1: 0.8413
Val   - Loss: 0.4914, Acc: 0.8496, F1: 0.8488

Epoch 9/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.494, Acc=0.885]


Train - Loss: 0.4945, Acc: 0.8651, F1: 0.8619
Val   - Loss: 0.5494, Acc: 0.7891, F1: 0.7979

Epoch 10/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.498, Acc=0.808]


Train - Loss: 0.4982, Acc: 0.8574, F1: 0.8551
Val   - Loss: 0.5049, Acc: 0.8348, F1: 0.8219

Epoch 11/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.13s/it, Loss=0.49, Acc=0.885]


Train - Loss: 0.4903, Acc: 0.8685, F1: 0.8659
Val   - Loss: 0.4749, Acc: 0.8717, F1: 0.8660

Epoch 12/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.489, Acc=0.808]


Train - Loss: 0.4890, Acc: 0.8637, F1: 0.8600
Val   - Loss: 0.5020, Acc: 0.8392, F1: 0.8418

Epoch 13/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.13s/it, Loss=0.491, Acc=0.808]


Train - Loss: 0.4914, Acc: 0.8644, F1: 0.8630
Val   - Loss: 0.5452, Acc: 0.7979, F1: 0.8072

Epoch 14/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.486, Acc=0.885]


Train - Loss: 0.4864, Acc: 0.8644, F1: 0.8614
Val   - Loss: 0.5268, Acc: 0.8142, F1: 0.8218

Epoch 15/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.473, Acc=0.885]


Train - Loss: 0.4727, Acc: 0.8747, F1: 0.8727
Val   - Loss: 0.4581, Acc: 0.8938, F1: 0.8918

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.13s/it, Loss=0.455, Acc=0.885]


Train - Loss: 0.4549, Acc: 0.9016, F1: 0.8998
Val   - Loss: 0.4427, Acc: 0.9027, F1: 0.9004

Epoch 17/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.449, Acc=0.962]


Train - Loss: 0.4491, Acc: 0.9013, F1: 0.8999
Val   - Loss: 0.4471, Acc: 0.8850, F1: 0.8832

Epoch 18/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.455, Acc=0.885]


Train - Loss: 0.4552, Acc: 0.8924, F1: 0.8911
Val   - Loss: 0.4733, Acc: 0.8643, F1: 0.8651

Epoch 19/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.45, Acc=0.769]


Train - Loss: 0.4497, Acc: 0.8954, F1: 0.8942
Val   - Loss: 0.4461, Acc: 0.8850, F1: 0.8844

Epoch 20/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.45, Acc=0.808]


Train - Loss: 0.4498, Acc: 0.8954, F1: 0.8938
Val   - Loss: 0.4452, Acc: 0.9027, F1: 0.9017

Fold 3 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4549
Accuracy: 0.9016
Precision: 0.9006
Recall: 0.9016
F1-Score: 0.8998

Per-class Metrics:
  Immature (0): Precision=0.9096, Recall=0.9542, F1=0.9313
  Mature (1): Precision=0.8797, Recall=0.7794, F1=0.8265

Confusion Matrix:
[[1811   87]
 [ 180  636]]

Fold 3 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4427
Accuracy: 0.9027
Precision: 0.9015
Recall: 0.9027
F1-Score: 0.9004

Per-class Metrics:
  Immature (0): Precision=0.9102, Recall=0.9588, F1=0.9339
  Mature (1): Precision=0.8795, Recall=0.7604, F1=0.8156

Confusion Matrix:
[[466  20]
 [ 46 146]]

Fold 4/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.628, Acc=0.885]


Train - Loss: 0.6278, Acc: 0.7303, F1: 0.7266
Val   - Loss: 0.5463, Acc: 0.7906, F1: 0.7971

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.14s/it, Loss=0.547, Acc=0.846]


Train - Loss: 0.5470, Acc: 0.8128, F1: 0.8094
Val   - Loss: 0.5106, Acc: 0.8437, F1: 0.8430

Epoch 3/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.15s/it, Loss=0.527, Acc=0.769]


Train - Loss: 0.5271, Acc: 0.8312, F1: 0.8291
Val   - Loss: 0.5315, Acc: 0.8378, F1: 0.8366

Epoch 4/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.506, Acc=0.808]


Train - Loss: 0.5063, Acc: 0.8530, F1: 0.8479
Val   - Loss: 0.5549, Acc: 0.7817, F1: 0.7823

Epoch 5/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.508, Acc=0.615]


Train - Loss: 0.5082, Acc: 0.8615, F1: 0.8575
Val   - Loss: 0.4839, Acc: 0.8732, F1: 0.8728

Epoch 6/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.509, Acc=0.885]


Train - Loss: 0.5090, Acc: 0.8493, F1: 0.8475
Val   - Loss: 0.5372, Acc: 0.8230, F1: 0.8271

Epoch 7/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.503, Acc=0.769]


Train - Loss: 0.5027, Acc: 0.8592, F1: 0.8554
Val   - Loss: 0.5183, Acc: 0.8186, F1: 0.8246

Epoch 8/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.496, Acc=0.885]


Train - Loss: 0.4959, Acc: 0.8721, F1: 0.8690
Val   - Loss: 0.5057, Acc: 0.8378, F1: 0.8416

Epoch 9/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.473, Acc=0.962]


Train - Loss: 0.4731, Acc: 0.8839, F1: 0.8818
Val   - Loss: 0.4667, Acc: 0.8702, F1: 0.8690

Epoch 10/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.46, Acc=0.846]


Train - Loss: 0.4599, Acc: 0.8946, F1: 0.8925
Val   - Loss: 0.4659, Acc: 0.8776, F1: 0.8758

Epoch 11/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.459, Acc=0.923]


Train - Loss: 0.4592, Acc: 0.8935, F1: 0.8911
Val   - Loss: 0.4707, Acc: 0.8732, F1: 0.8703

Epoch 12/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.453, Acc=0.808]


Train - Loss: 0.4532, Acc: 0.9016, F1: 0.8999
Val   - Loss: 0.4496, Acc: 0.8923, F1: 0.8906

Epoch 13/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.45, Acc=0.923]


Train - Loss: 0.4502, Acc: 0.8998, F1: 0.8980
Val   - Loss: 0.4523, Acc: 0.8835, F1: 0.8816

Epoch 14/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.447, Acc=0.846]


Train - Loss: 0.4471, Acc: 0.9042, F1: 0.9025
Val   - Loss: 0.4698, Acc: 0.8791, F1: 0.8806

Epoch 15/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.45, Acc=0.808]


Train - Loss: 0.4495, Acc: 0.9068, F1: 0.9051
Val   - Loss: 0.4686, Acc: 0.8732, F1: 0.8740

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.446, Acc=0.885]


Train - Loss: 0.4462, Acc: 0.9053, F1: 0.9039
Val   - Loss: 0.4476, Acc: 0.8997, F1: 0.8993

Epoch 17/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.14s/it, Loss=0.44, Acc=0.923]


Train - Loss: 0.4396, Acc: 0.9105, F1: 0.9089
Val   - Loss: 0.4541, Acc: 0.9012, F1: 0.9020

Epoch 18/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.15s/it, Loss=0.44, Acc=0.885]


Train - Loss: 0.4395, Acc: 0.9083, F1: 0.9062
Val   - Loss: 0.4550, Acc: 0.8761, F1: 0.8746

Epoch 19/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.43, Acc=0.923]


Train - Loss: 0.4304, Acc: 0.9167, F1: 0.9152
Val   - Loss: 0.4515, Acc: 0.8879, F1: 0.8876

Epoch 20/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.17s/it, Loss=0.441, Acc=0.962]


Train - Loss: 0.4407, Acc: 0.9079, F1: 0.9065
Val   - Loss: 0.4486, Acc: 0.8850, F1: 0.8835

Fold 4 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4396
Accuracy: 0.9105
Precision: 0.9097
Recall: 0.9105
F1-Score: 0.9089

Per-class Metrics:
  Immature (0): Precision=0.9169, Recall=0.9597, F1=0.9378
  Mature (1): Precision=0.8925, Recall=0.7938, F1=0.8402

Confusion Matrix:
[[1832   77]
 [ 166  639]]

Fold 4 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4541
Accuracy: 0.9012
Precision: 0.9036
Recall: 0.9012
F1-Score: 0.9020

Per-class Metrics:
  Immature (0): Precision=0.9416, Recall=0.9158, F1=0.9285
  Mature (1): Precision=0.8148, Recall=0.8670, F1=0.8401

Confusion Matrix:
[[435  40]
 [ 27 176]]

Fold 5/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.634, Acc=0.769]


Train - Loss: 0.6342, Acc: 0.7277, F1: 0.7231
Val   - Loss: 0.5323, Acc: 0.8053, F1: 0.7693

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.14s/it, Loss=0.543, Acc=0.846]


Train - Loss: 0.5431, Acc: 0.8217, F1: 0.8172
Val   - Loss: 0.5091, Acc: 0.8525, F1: 0.8415

Epoch 3/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.534, Acc=0.846]


Train - Loss: 0.5339, Acc: 0.8324, F1: 0.8273
Val   - Loss: 0.5161, Acc: 0.8481, F1: 0.8449

Epoch 4/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.511, Acc=0.885]


Train - Loss: 0.5107, Acc: 0.8515, F1: 0.8460
Val   - Loss: 0.4979, Acc: 0.8614, F1: 0.8611

Epoch 5/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.51, Acc=0.769]


Train - Loss: 0.5102, Acc: 0.8493, F1: 0.8445
Val   - Loss: 0.5210, Acc: 0.8466, F1: 0.8450

Epoch 6/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.502, Acc=0.923]


Train - Loss: 0.5019, Acc: 0.8604, F1: 0.8568
Val   - Loss: 0.5054, Acc: 0.8569, F1: 0.8407

Epoch 7/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.499, Acc=0.769]


Train - Loss: 0.4994, Acc: 0.8666, F1: 0.8635
Val   - Loss: 0.5120, Acc: 0.8422, F1: 0.8291

Epoch 8/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.09s/it, Loss=0.48, Acc=0.885]


Train - Loss: 0.4801, Acc: 0.8755, F1: 0.8711
Val   - Loss: 0.4429, Acc: 0.8997, F1: 0.8957

Epoch 9/20


Training: 100%|█████████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.459, Acc=1]


Train - Loss: 0.4592, Acc: 0.8939, F1: 0.8915
Val   - Loss: 0.4297, Acc: 0.9159, F1: 0.9140

Epoch 10/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.455, Acc=0.769]


Train - Loss: 0.4546, Acc: 0.9038, F1: 0.9021
Val   - Loss: 0.4455, Acc: 0.8953, F1: 0.8957

Epoch 11/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.455, Acc=0.885]


Train - Loss: 0.4552, Acc: 0.8957, F1: 0.8941
Val   - Loss: 0.4327, Acc: 0.9145, F1: 0.9137

Epoch 12/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.448, Acc=0.923]


Train - Loss: 0.4478, Acc: 0.9001, F1: 0.8983
Val   - Loss: 0.4419, Acc: 0.8938, F1: 0.8949

Epoch 13/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.446, Acc=0.923]


Train - Loss: 0.4458, Acc: 0.9049, F1: 0.9040
Val   - Loss: 0.4361, Acc: 0.8997, F1: 0.8966

Epoch 14/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.447, Acc=0.923]


Train - Loss: 0.4468, Acc: 0.9013, F1: 0.9000
Val   - Loss: 0.4400, Acc: 0.8997, F1: 0.8979

Epoch 15/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.442, Acc=0.923]


Train - Loss: 0.4424, Acc: 0.9038, F1: 0.9027
Val   - Loss: 0.4363, Acc: 0.8938, F1: 0.8927

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.442, Acc=0.846]


Train - Loss: 0.4416, Acc: 0.9094, F1: 0.9082
Val   - Loss: 0.4422, Acc: 0.9041, F1: 0.9011

Epoch 17/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.449, Acc=0.962]


Train - Loss: 0.4491, Acc: 0.9009, F1: 0.8997
Val   - Loss: 0.4397, Acc: 0.8938, F1: 0.8935

Epoch 18/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.445, Acc=0.808]


Train - Loss: 0.4450, Acc: 0.9035, F1: 0.9023
Val   - Loss: 0.4362, Acc: 0.9056, F1: 0.9046

Epoch 19/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.444, Acc=0.923]


Train - Loss: 0.4438, Acc: 0.9097, F1: 0.9083
Val   - Loss: 0.4402, Acc: 0.8953, F1: 0.8937

Epoch 20/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.441, Acc=0.885]


Train - Loss: 0.4411, Acc: 0.9101, F1: 0.9090
Val   - Loss: 0.4296, Acc: 0.9159, F1: 0.9147

Fold 5 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4592
Accuracy: 0.8939
Precision: 0.8929
Recall: 0.8939
F1-Score: 0.8915

Per-class Metrics:
  Immature (0): Precision=0.9003, Recall=0.9535, F1=0.9262
  Mature (1): Precision=0.8757, Recall=0.7561, F1=0.8115

Confusion Matrix:
[[1806   88]
 [ 200  620]]

Fold 5 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4297
Accuracy: 0.9159
Precision: 0.9152
Recall: 0.9159
F1-Score: 0.9140

Per-class Metrics:
  Immature (0): Precision=0.9204, Recall=0.9673, F1=0.9433
  Mature (1): Precision=0.9018, Recall=0.7819, F1=0.8376

Confusion Matrix:
[[474  16]
 [ 41 147]]

Cross-validation Results Summary:
Fold 1: Val Acc = 0.9043, Val F1 = 0.9033, Val Loss = 0.4489
Fold 2: Val Acc = 0.9190, Val F1 = 0.9169, Val Loss = 0.4217
Fold 3: Val Acc = 0.9027, Val F1 = 

Training: 100%|███████████████████████████████████████████████| 106/106 [05:31<00:00,  3.13s/it, Loss=0.618, Acc=0.812]


Training Set - Loss: 0.6179, Acc: 0.7397, F1: 0.7301
Test Set     - Loss: 0.5052, Acc: 0.8314, F1: 0.8101

Final Model - Epoch 2/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:34<00:00,  3.15s/it, Loss=0.545, Acc=0.844]


Training Set - Loss: 0.5450, Acc: 0.8208, F1: 0.8134
Test Set     - Loss: 0.5265, Acc: 0.8656, F1: 0.8667

Final Model - Epoch 3/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:30<00:00,  3.12s/it, Loss=0.517, Acc=0.844]


Training Set - Loss: 0.5169, Acc: 0.8567, F1: 0.8513
Test Set     - Loss: 0.4815, Acc: 0.8927, F1: 0.8897

Final Model - Epoch 4/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:31<00:00,  3.12s/it, Loss=0.517, Acc=0.906]


Training Set - Loss: 0.5170, Acc: 0.8482, F1: 0.8428
Test Set     - Loss: 0.5193, Acc: 0.8373, F1: 0.8426

Final Model - Epoch 5/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:29<00:00,  3.11s/it, Loss=0.515, Acc=0.875]


Training Set - Loss: 0.5152, Acc: 0.8473, F1: 0.8436
Test Set     - Loss: 0.4959, Acc: 0.8632, F1: 0.8669

Final Model - Epoch 6/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:30<00:00,  3.12s/it, Loss=0.492, Acc=0.875]


Training Set - Loss: 0.4925, Acc: 0.8685, F1: 0.8652
Test Set     - Loss: 0.4571, Acc: 0.8962, F1: 0.8979

Final Model - Epoch 7/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:30<00:00,  3.11s/it, Loss=0.498, Acc=0.938]


Training Set - Loss: 0.4979, Acc: 0.8600, F1: 0.8563
Test Set     - Loss: 0.4882, Acc: 0.9021, F1: 0.9007

Final Model - Epoch 8/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:30<00:00,  3.12s/it, Loss=0.509, Acc=0.938]


Training Set - Loss: 0.5093, Acc: 0.8544, F1: 0.8521
Test Set     - Loss: 0.5021, Acc: 0.8880, F1: 0.8899

Final Model - Epoch 9/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:31<00:00,  3.13s/it, Loss=0.496, Acc=0.906]


Training Set - Loss: 0.4956, Acc: 0.8647, F1: 0.8615
Test Set     - Loss: 0.5071, Acc: 0.8337, F1: 0.8351

Final Model - Epoch 10/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:32<00:00,  3.13s/it, Loss=0.474, Acc=0.906]


Training Set - Loss: 0.4736, Acc: 0.8824, F1: 0.8797
Test Set     - Loss: 0.4212, Acc: 0.9175, F1: 0.9174

Final Model - Epoch 11/15


Training: 100%|████████████████████████████████████████████████| 106/106 [05:31<00:00,  3.13s/it, Loss=0.46, Acc=0.906]


Training Set - Loss: 0.4600, Acc: 0.8924, F1: 0.8904
Test Set     - Loss: 0.4241, Acc: 0.9163, F1: 0.9133

Final Model - Epoch 12/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:32<00:00,  3.13s/it, Loss=0.456, Acc=0.781]


Training Set - Loss: 0.4559, Acc: 0.8950, F1: 0.8925
Test Set     - Loss: 0.4139, Acc: 0.9257, F1: 0.9250

Final Model - Epoch 13/15


Training: 100%|███████████████████████████████████████████████████| 106/106 [05:32<00:00,  3.14s/it, Loss=0.453, Acc=1]


Training Set - Loss: 0.4531, Acc: 0.8939, F1: 0.8923
Test Set     - Loss: 0.4287, Acc: 0.8998, F1: 0.8985

Final Model - Epoch 14/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:32<00:00,  3.13s/it, Loss=0.455, Acc=0.906]


Training Set - Loss: 0.4546, Acc: 0.8965, F1: 0.8951
Test Set     - Loss: 0.4210, Acc: 0.9186, F1: 0.9163

Final Model - Epoch 15/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:32<00:00,  3.13s/it, Loss=0.453, Acc=0.875]


Training Set - Loss: 0.4525, Acc: 0.8948, F1: 0.8926
Test Set     - Loss: 0.4084, Acc: 0.9340, F1: 0.9332

Final Training Set Detailed Metrics:

Final Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4525
Accuracy: 0.8948
Precision: 0.8935
Recall: 0.8948
F1-Score: 0.8926

Per-class Metrics:
  Immature (0): Precision=0.9036, Recall=0.9518, F1=0.9271
  Mature (1): Precision=0.8695, Recall=0.7599, F1=0.8110

Confusion Matrix:
[[2269  115]
 [ 242  766]]

Test Set Detailed Metrics:

Test Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4084
Accuracy: 0.9340
Precision: 0.9335
Recall: 0.9340
F1-Score: 0.9332

Per-class Metrics:
  Immature (0): Precision=0.9397, Recall=0.9681, F1=0.9537
  Mature (1): Precision=0.9188, Recall=0.8532, F1=0.8848

Confusion Matrix:
[[577  19]
 [ 37 215]]

✓ Results saved to efficientnet_training_results.xlsx

Results Summary:
5-fold cross-validation average validation accuracy: 0.9086
Final t