In [4]:
import os
import sys
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset, SubsetRandomSampler
from torchvision import transforms, models
from PIL import Image
import numpy as np
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
from tqdm import tqdm
import warnings
import pandas as pd
import pickle
warnings.filterwarnings('ignore')

def check_gpu_available():
    if not torch.cuda.is_available():
        print("Error: No available GPU device detected.")
        print("Please ensure:")
        print("1. CUDA and cuDNN are installed")
        print("2. A GPU-compatible PyTorch version is installed")
        print("3. The graphics card driver is up to date")
        print("\nProgram requires GPU for training, exiting now...")
        sys.exit(1)
    
    print(f"✓ GPU available: {torch.cuda.get_device_name(0)}")
    print(f"  Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
    print(f"  CUDA version: {torch.version.cuda}")
    return True

check_gpu_available()

def set_seed(seed=42):
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

class CustomDataset(Dataset):
    def __init__(self, image_paths, labels, transform=None):
        self.image_paths = image_paths
        self.labels = labels
        self.transform = transform
        
    def __len__(self):
        return len(self.image_paths)
    
    def __getitem__(self, idx):
        image = Image.open(self.image_paths[idx]).convert('RGB')
        label = self.labels[idx]
        
        if self.transform:
            image = self.transform(image)
            
        return image, label

def load_data(immature_dir, mature_dir):
    immature_paths = []
    mature_paths = []
    
    for img_name in os.listdir(immature_dir):
        if img_name.lower().endswith(('.jpg', '.jpeg', '.png')):
            immature_paths.append(os.path.join(immature_dir, img_name))
    
    for img_name in os.listdir(mature_dir):
        if img_name.lower().endswith(('.jpg', '.jpeg', '.png')):
            mature_paths.append(os.path.join(mature_dir, img_name))
    
    all_paths = immature_paths + mature_paths
    all_labels = [0] * len(immature_paths) + [1] * len(mature_paths)
    
    print(f"Immature images: {len(immature_paths)}")
    print(f"Mature images: {len(mature_paths)}")
    print(f"Total images: {len(all_paths)}")
    
    return all_paths, all_labels

def get_transforms():
    train_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.RandomRotation(10),
        transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                           std=[0.229, 0.224, 0.225])
    ])
    
    val_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                           std=[0.229, 0.224, 0.225])
    ])
    
    return train_transform, val_transform

def create_resnet18_model(num_classes=2):
    model = models.resnet18(pretrained=True)
    
    num_features = model.fc.in_features
    model.fc = nn.Sequential(
        nn.Dropout(0.5),
        nn.Linear(num_features, 256),
        nn.ReLU(),
        nn.Dropout(0.3),
        nn.Linear(256, num_classes)
    )
    
    return model

def calculate_metrics(all_labels, all_predictions):
    accuracy = np.mean(np.array(all_labels) == np.array(all_predictions))
    
    precision = precision_score(all_labels, all_predictions, average='weighted')
    recall = recall_score(all_labels, all_predictions, average='weighted')
    f1 = f1_score(all_labels, all_predictions, average='weighted')
    
    precision_per_class = precision_score(all_labels, all_predictions, average=None)
    recall_per_class = recall_score(all_labels, all_predictions, average=None)
    f1_per_class = f1_score(all_labels, all_predictions, average=None)
    
    cm = confusion_matrix(all_labels, all_predictions)
    
    report = classification_report(all_labels, all_predictions, 
                                  target_names=['immature', 'mature'], 
                                  output_dict=True)
    
    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'precision_per_class': precision_per_class,
        'recall_per_class': recall_per_class,
        'f1_per_class': f1_per_class,
        'confusion_matrix': cm,
        'classification_report': report
    }

def train_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    all_predictions = []
    all_labels = []
    
    progress_bar = tqdm(dataloader, desc='Training')
    for images, labels in progress_bar:
        images, labels = images.to(device), labels.to(device)
        
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        
        all_predictions.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
        
        batch_acc = (predicted == labels).sum().item() / labels.size(0)
        progress_bar.set_postfix({'Loss': running_loss/len(dataloader), 'Acc': batch_acc})
    
    epoch_loss = running_loss / len(dataloader)
    
    metrics = calculate_metrics(all_labels, all_predictions)
    metrics['loss'] = epoch_loss
    
    return epoch_loss, metrics

def evaluate_model(model, dataloader, criterion, device, dataset_name="Dataset"):
    model.eval()
    running_loss = 0.0
    all_predictions = []
    all_labels = []
    
    with torch.no_grad():
        for images, labels in dataloader:
            images, labels = images.to(device), labels.to(device)
            
            outputs = model(images)
            loss = criterion(outputs, labels)
            
            running_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            
            all_predictions.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    
    epoch_loss = running_loss / len(dataloader)
    
    metrics = calculate_metrics(all_labels, all_predictions)
    metrics['loss'] = epoch_loss
    
    return epoch_loss, metrics

def print_detailed_metrics(metrics, dataset_name="Dataset"):
    print(f"\n{dataset_name} Detailed Metrics:")
    print("-" * 50)
    print(f"Loss: {metrics['loss']:.4f}")
    print(f"Accuracy: {metrics['accuracy']:.4f}")
    print(f"Precision: {metrics['precision']:.4f}")
    print(f"Recall: {metrics['recall']:.4f}")
    print(f"F1-Score: {metrics['f1']:.4f}")
    
    print(f"\nPer-class Metrics:")
    print(f"  Immature (0): Precision={metrics['precision_per_class'][0]:.4f}, "
          f"Recall={metrics['recall_per_class'][0]:.4f}, F1={metrics['f1_per_class'][0]:.4f}")
    print(f"  Mature (1): Precision={metrics['precision_per_class'][1]:.4f}, "
          f"Recall={metrics['recall_per_class'][1]:.4f}, F1={metrics['f1_per_class'][1]:.4f}")
    
    print(f"\nConfusion Matrix:")
    print(metrics['confusion_matrix'])

def export_results_to_excel(fold_results, test_results, final_train_results, filename='training_results.xlsx'):
    all_results = []
    
    for fold_result in fold_results:
        fold_data = {
            'Fold': fold_result['fold'],
            'Dataset': 'Validation',
            'Loss': fold_result['val_loss'],
            'Accuracy': fold_result['val_accuracy'],
            'Precision': fold_result['val_precision'],
            'Recall': fold_result['val_recall'],
            'F1_Score': fold_result['val_f1'],
            'Precision_Class0': fold_result['val_precision_per_class'][0],
            'Precision_Class1': fold_result['val_precision_per_class'][1],
            'Recall_Class0': fold_result['val_recall_per_class'][0],
            'Recall_Class1': fold_result['val_recall_per_class'][1],
            'F1_Class0': fold_result['val_f1_per_class'][0],
            'F1_Class1': fold_result['val_f1_per_class'][1],
            'Train_Loss': fold_result['train_loss'],
            'Train_Accuracy': fold_result['train_accuracy'],
            'Train_Precision': fold_result['train_precision'],
            'Train_Recall': fold_result['train_recall'],
            'Train_F1_Score': fold_result['train_f1']
        }
        all_results.append(fold_data)
    
    final_train_data = {
        'Fold': 'Final',
        'Dataset': 'Train',
        'Loss': final_train_results['loss'],
        'Accuracy': final_train_results['accuracy'],
        'Precision': final_train_results['precision'],
        'Recall': final_train_results['recall'],
        'F1_Score': final_train_results['f1'],
        'Precision_Class0': final_train_results['precision_per_class'][0],
        'Precision_Class1': final_train_results['precision_per_class'][1],
        'Recall_Class0': final_train_results['recall_per_class'][0],
        'Recall_Class1': final_train_results['recall_per_class'][1],
        'F1_Class0': final_train_results['f1_per_class'][0],
        'F1_Class1': final_train_results['f1_per_class'][1],
        'Train_Loss': final_train_results['loss'],
        'Train_Accuracy': final_train_results['accuracy'],
        'Train_Precision': final_train_results['precision'],
        'Train_Recall': final_train_results['recall'],
        'Train_F1_Score': final_train_results['f1']
    }
    all_results.append(final_train_data)
    
    test_data = {
        'Fold': 'Final',
        'Dataset': 'Test',
        'Loss': test_results['loss'],
        'Accuracy': test_results['accuracy'],
        'Precision': test_results['precision'],
        'Recall': test_results['recall'],
        'F1_Score': test_results['f1'],
        'Precision_Class0': test_results['precision_per_class'][0],
        'Precision_Class1': test_results['precision_per_class'][1],
        'Recall_Class0': test_results['recall_per_class'][0],
        'Recall_Class1': test_results['recall_per_class'][1],
        'F1_Class0': test_results['f1_per_class'][0],
        'F1_Class1': test_results['f1_per_class'][1],
        'Train_Loss': final_train_results['loss'],
        'Train_Accuracy': final_train_results['accuracy'],
        'Train_Precision': final_train_results['precision'],
        'Train_Recall': final_train_results['recall'],
        'Train_F1_Score': final_train_results['f1']
    }
    all_results.append(test_data)
    
    df = pd.DataFrame(all_results)
    
    validation_df = df[df['Dataset'] == 'Validation']
    if not validation_df.empty:
        avg_row = {
            'Fold': 'Average',
            'Dataset': 'Validation',
            'Loss': validation_df['Loss'].mean(),
            'Accuracy': validation_df['Accuracy'].mean(),
            'Precision': validation_df['Precision'].mean(),
            'Recall': validation_df['Recall'].mean(),
            'F1_Score': validation_df['F1_Score'].mean(),
            'Precision_Class0': validation_df['Precision_Class0'].mean(),
            'Precision_Class1': validation_df['Precision_Class1'].mean(),
            'Recall_Class0': validation_df['Recall_Class0'].mean(),
            'Recall_Class1': validation_df['Recall_Class1'].mean(),
            'F1_Class0': validation_df['F1_Class0'].mean(),
            'F1_Class1': validation_df['F1_Class1'].mean(),
            'Train_Loss': validation_df['Train_Loss'].mean(),
            'Train_Accuracy': validation_df['Train_Accuracy'].mean(),
            'Train_Precision': validation_df['Train_Precision'].mean(),
            'Train_Recall': validation_df['Train_Recall'].mean(),
            'Train_F1_Score': validation_df['Train_F1_Score'].mean()
        }
        
        df = pd.concat([df, pd.DataFrame([avg_row])], ignore_index=True)
    
    df.to_excel(filename, index=False)
    print(f"\n✓ Results saved to {filename}")
    
    print("\n" + "="*80)
    print("Results Summary:")
    print("="*80)
    if not validation_df.empty:
        print(f"5-fold cross-validation average validation accuracy: {validation_df['Accuracy'].mean():.4f}")
    print(f"Final training set accuracy: {final_train_results['accuracy']:.4f}")
    print(f"Test set accuracy: {test_results['accuracy']:.4f}")
    print(f"Test set F1 score: {test_results['f1']:.4f}")
    
    return df

def main():
    immature_dir = r"E:\TSG\jupyterlab\machine learning image\augmented_dataset\immature"
    mature_dir = r"E:\TSG\jupyterlab\machine learning image\augmented_dataset\mature"
    
    print("Loading data...")
    all_paths, all_labels = load_data(immature_dir, mature_dir)
    
    print("\nSplitting data into train and test sets...")
    train_paths, test_paths, train_labels, test_labels = train_test_split(
        all_paths, all_labels, test_size=0.2, random_state=42, stratify=all_labels
    )
    
    print(f"Train set size: {len(train_paths)}")
    print(f"Test set size: {len(test_paths)}")
    
    train_transform, val_transform = get_transforms()
    
    train_dataset = CustomDataset(train_paths, train_labels, train_transform)
    test_dataset = CustomDataset(test_paths, test_labels, val_transform)
    
    device = torch.device("cuda")
    print(f"\nUsing device: {device}")
    
    print("\nStarting 5-fold cross validation...")
    kfold = KFold(n_splits=5, shuffle=True, random_state=42)
    fold_results = []
    
    for fold, (train_idx, val_idx) in enumerate(kfold.split(train_dataset)):
        print(f"\n{'='*60}")
        print(f"Fold {fold+1}/5")
        print(f"{'='*60}")
        
        train_subsampler = SubsetRandomSampler(train_idx)
        val_subsampler = SubsetRandomSampler(val_idx)
        
        train_loader = DataLoader(train_dataset, batch_size=32, sampler=train_subsampler)
        val_loader = DataLoader(train_dataset, batch_size=32, sampler=val_subsampler)
        
        model = create_resnet18_model(num_classes=2)
        model = model.to(device)
        
        criterion = nn.CrossEntropyLoss()
        optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-4)
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', patience=3)
        
        num_epochs = 20
        best_val_acc = 0
        best_model_state = None
        best_train_metrics = None
        best_val_metrics = None
        best_train_loss = None
        
        for epoch in range(num_epochs):
            print(f"\nEpoch {epoch+1}/{num_epochs}")
            
            train_loss, train_metrics = train_epoch(model, train_loader, criterion, optimizer, device)
            
            val_loss, val_metrics = evaluate_model(model, val_loader, criterion, device, "Validation")
            
            scheduler.step(val_loss)
            
            print(f"Train - Loss: {train_loss:.4f}, Acc: {train_metrics['accuracy']:.4f}, "
                  f"F1: {train_metrics['f1']:.4f}")
            print(f"Val   - Loss: {val_loss:.4f}, Acc: {val_metrics['accuracy']:.4f}, "
                  f"F1: {val_metrics['f1']:.4f}")
            
            if val_metrics['accuracy'] > best_val_acc:
                best_val_acc = val_metrics['accuracy']
                best_model_state = model.state_dict().copy()
                best_train_metrics = train_metrics
                best_val_metrics = val_metrics
                best_train_loss = train_loss
        
        print_detailed_metrics(best_train_metrics, f"Fold {fold+1} - Best Training Set")
        print_detailed_metrics(best_val_metrics, f"Fold {fold+1} - Best Validation Set")
        
        fold_results.append({
            'fold': fold + 1,
            'best_val_acc': best_val_acc,
            'val_loss': best_val_metrics['loss'],
            'val_accuracy': best_val_metrics['accuracy'],
            'val_precision': best_val_metrics['precision'],
            'val_recall': best_val_metrics['recall'],
            'val_f1': best_val_metrics['f1'],
            'val_precision_per_class': best_val_metrics['precision_per_class'],
            'val_recall_per_class': best_val_metrics['recall_per_class'],
            'val_f1_per_class': best_val_metrics['f1_per_class'],
            'train_loss': best_train_loss,
            'train_accuracy': best_train_metrics['accuracy'],
            'train_precision': best_train_metrics['precision'],
            'train_recall': best_train_metrics['recall'],
            'train_f1': best_train_metrics['f1'],
            'model_state': best_model_state
        })
    
    print("\n" + "="*60)
    print("Cross-validation Results Summary:")
    print("="*60)
    for result in fold_results:
        print(f"Fold {result['fold']}: "
              f"Val Acc = {result['best_val_acc']:.4f}, "
              f"Val F1 = {result['val_f1']:.4f}, "
              f"Val Loss = {result['val_loss']:.4f}")
    
    avg_val_acc = np.mean([r['best_val_acc'] for r in fold_results])
    avg_val_f1 = np.mean([r['val_f1'] for r in fold_results])
    avg_val_loss = np.mean([r['val_loss'] for r in fold_results])
    print(f"\nAverage validation accuracy: {avg_val_acc:.4f}")
    print(f"Average validation F1 score: {avg_val_f1:.4f}")
    print(f"Average validation Loss: {avg_val_loss:.4f}")
    
    print("\n" + "="*60)
    print("Evaluating final model on test set...")
    print("="*60)
    
    print("\nTraining final model on entire training set...")
    final_train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)
    
    final_model = create_resnet18_model(num_classes=2)
    final_model = final_model.to(device)
    
    final_criterion = nn.CrossEntropyLoss()
    final_optimizer = optim.Adam(final_model.parameters(), lr=0.001)
    final_scheduler = optim.lr_scheduler.ReduceLROnPlateau(final_optimizer, mode='min', patience=3)
    
    num_final_epochs = 15
    best_test_acc = 0
    best_test_metrics = None
    best_final_train_metrics = None
    best_final_train_loss = None
    
    for epoch in range(num_final_epochs):
        print(f"\nFinal Model - Epoch {epoch+1}/{num_final_epochs}")
        
        train_loss, train_metrics = train_epoch(final_model, final_train_loader, final_criterion, final_optimizer, device)
        
        test_loss, test_metrics = evaluate_model(final_model, test_loader, final_criterion, device, "Test")
        
        final_scheduler.step(test_loss)
        
        print(f"Training Set - Loss: {train_loss:.4f}, Acc: {train_metrics['accuracy']:.4f}, "
              f"F1: {train_metrics['f1']:.4f}")
        print(f"Test Set     - Loss: {test_loss:.4f}, Acc: {test_metrics['accuracy']:.4f}, "
              f"F1: {test_metrics['f1']:.4f}")
        
        if test_metrics['accuracy'] > best_test_acc:
            best_test_acc = test_metrics['accuracy']
            best_test_metrics = test_metrics
            best_final_train_metrics = train_metrics
            best_final_train_loss = train_loss
            torch.save(final_model.state_dict(), 'best_resnet18_model.pth')
    
    print("\n" + "="*60)
    print("Final Training Set Detailed Metrics:")
    print("="*60)
    print_detailed_metrics(best_final_train_metrics, "Final Training Set")
    
    print("\n" + "="*60)
    print("Test Set Detailed Metrics:")
    print("="*60)
    print_detailed_metrics(best_test_metrics, "Test Set")
    
    export_results_to_excel(fold_results, best_test_metrics, best_final_train_metrics, 'model_training_results.xlsx')
    
    def predict_single_image(image_path, model_path='best_resnet18_model.pth'):
        model = create_resnet18_model(num_classes=2)
        model.load_state_dict(torch.load(model_path, map_location=device))
        model = model.to(device)
        model.eval()
        
        image = Image.open(image_path).convert('RGB')
        transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                               std=[0.229, 0.224, 0.225])
        ])
        
        image_tensor = transform(image).unsqueeze(0).to(device)
        
        with torch.no_grad():
            outputs = model(image_tensor)
            probabilities = torch.softmax(outputs, dim=1)
            _, predicted = torch.max(outputs, 1)
            
            class_names = ['immature', 'mature']
            result = class_names[predicted.item()]
            confidence = probabilities[0][predicted.item()].item()
            
        return result, confidence
    
    print("\n" + "="*60)
    print("Model ready for prediction!")
    print("Use predict_single_image('path/to/image.jpg') to classify new images.")
    print("="*60)
    
    with open('classifier_info.pkl', 'wb') as f:
        pickle.dump({
            'train_paths': train_paths,
            'test_paths': test_paths,
            'train_labels': train_labels,
            'test_labels': test_labels,
            'class_names': ['immature', 'mature'],
            'normalization_mean': [0.485, 0.456, 0.406],
            'normalization_std': [0.229, 0.224, 0.225],
            'fold_results': fold_results,
            'test_results': best_test_metrics,
            'final_train_results': best_final_train_metrics
        }, f)
    
    return final_model, best_test_metrics, best_final_train_metrics

if __name__ == "__main__":
    model, test_results, train_results = main()

✓ GPU available: NVIDIA GeForce RTX 5070 Ti
  Memory: 17.09 GB
  CUDA version: 11.8
Loading data...
Immature images: 2980
Mature images: 1260
Total images: 4240

Splitting data into train and test sets...
Train set size: 3392
Test set size: 848

Using device: cuda

Starting 5-fold cross validation...

Fold 1/5

Epoch 1/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:35<00:00,  3.25s/it, Loss=0.463, Acc=0.88]


Train - Loss: 0.4627, Acc: 0.7829, F1: 0.7725
Val   - Loss: 0.4884, Acc: 0.7865, F1: 0.7798

Epoch 2/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.19s/it, Loss=0.416, Acc=0.72]


Train - Loss: 0.4156, Acc: 0.8179, F1: 0.8098
Val   - Loss: 0.7264, Acc: 0.6819, F1: 0.5556

Epoch 3/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:16<00:00,  3.01s/it, Loss=0.44, Acc=0.88]


Train - Loss: 0.4398, Acc: 0.8072, F1: 0.7964
Val   - Loss: 0.4635, Acc: 0.8336, F1: 0.8264

Epoch 4/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:18<00:00,  3.05s/it, Loss=0.408, Acc=0.84]


Train - Loss: 0.4080, Acc: 0.8290, F1: 0.8208
Val   - Loss: 0.4347, Acc: 0.7923, F1: 0.7979

Epoch 5/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:18<00:00,  3.04s/it, Loss=0.414, Acc=0.92]


Train - Loss: 0.4136, Acc: 0.8238, F1: 0.8185
Val   - Loss: 0.6074, Acc: 0.5994, F1: 0.5960

Epoch 6/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:17<00:00,  3.03s/it, Loss=0.386, Acc=0.76]


Train - Loss: 0.3863, Acc: 0.8415, F1: 0.8352
Val   - Loss: 0.4929, Acc: 0.8115, F1: 0.8028

Epoch 7/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.06s/it, Loss=0.393, Acc=0.92]


Train - Loss: 0.3934, Acc: 0.8345, F1: 0.8269
Val   - Loss: 0.4757, Acc: 0.7923, F1: 0.7584

Epoch 8/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.405, Acc=0.64]


Train - Loss: 0.4047, Acc: 0.8220, F1: 0.8125
Val   - Loss: 0.3290, Acc: 0.8513, F1: 0.8463

Epoch 9/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.361, Acc=0.84]


Train - Loss: 0.3609, Acc: 0.8470, F1: 0.8409
Val   - Loss: 0.4246, Acc: 0.8100, F1: 0.7860

Epoch 10/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.07s/it, Loss=0.392, Acc=0.68]


Train - Loss: 0.3922, Acc: 0.8397, F1: 0.8325
Val   - Loss: 0.4002, Acc: 0.8027, F1: 0.7794

Epoch 11/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.12s/it, Loss=0.356, Acc=0.84]


Train - Loss: 0.3556, Acc: 0.8492, F1: 0.8430
Val   - Loss: 0.4472, Acc: 0.7909, F1: 0.7977

Epoch 12/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.367, Acc=0.68]


Train - Loss: 0.3670, Acc: 0.8515, F1: 0.8449
Val   - Loss: 0.4056, Acc: 0.7909, F1: 0.7940

Epoch 13/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.327, Acc=0.92]


Train - Loss: 0.3267, Acc: 0.8647, F1: 0.8600
Val   - Loss: 0.3137, Acc: 0.8542, F1: 0.8531

Epoch 14/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:19<00:00,  3.06s/it, Loss=0.288, Acc=0.88]


Train - Loss: 0.2883, Acc: 0.8861, F1: 0.8826
Val   - Loss: 0.2863, Acc: 0.8719, F1: 0.8692

Epoch 15/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.298, Acc=0.88]


Train - Loss: 0.2978, Acc: 0.8739, F1: 0.8698
Val   - Loss: 0.2644, Acc: 0.8822, F1: 0.8790

Epoch 16/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.274, Acc=0.88]


Train - Loss: 0.2735, Acc: 0.8865, F1: 0.8833
Val   - Loss: 0.2838, Acc: 0.8675, F1: 0.8639

Epoch 17/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.277, Acc=0.96]


Train - Loss: 0.2769, Acc: 0.8824, F1: 0.8793
Val   - Loss: 0.2750, Acc: 0.8778, F1: 0.8754

Epoch 18/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.279, Acc=0.88]


Train - Loss: 0.2794, Acc: 0.8787, F1: 0.8742
Val   - Loss: 0.2871, Acc: 0.8792, F1: 0.8778

Epoch 19/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.273, Acc=0.96]


Train - Loss: 0.2725, Acc: 0.8820, F1: 0.8789
Val   - Loss: 0.2977, Acc: 0.8866, F1: 0.8851

Epoch 20/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.261, Acc=0.88]


Train - Loss: 0.2605, Acc: 0.8905, F1: 0.8872
Val   - Loss: 0.2588, Acc: 0.8807, F1: 0.8788

Fold 1 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2725
Accuracy: 0.8820
Precision: 0.8803
Recall: 0.8820
F1-Score: 0.8789

Per-class Metrics:
  Immature (0): Precision=0.8914, Recall=0.9490, F1=0.9193
  Mature (1): Precision=0.8533, Recall=0.7197, F1=0.7808

Confusion Matrix:
[[1823   98]
 [ 222  570]]

Fold 1 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2977
Accuracy: 0.8866
Precision: 0.8853
Recall: 0.8866
F1-Score: 0.8851

Per-class Metrics:
  Immature (0): Precision=0.9004, Recall=0.9374, F1=0.9185
  Mature (1): Precision=0.8528, Recall=0.7778, F1=0.8136

Confusion Matrix:
[[434  29]
 [ 48 168]]

Fold 2/5

Epoch 1/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.474, Acc=0.76]


Train - Loss: 0.4744, Acc: 0.7803, F1: 0.7657
Val   - Loss: 0.5448, Acc: 0.7069, F1: 0.5994

Epoch 2/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.439, Acc=0.84]


Train - Loss: 0.4393, Acc: 0.8109, F1: 0.7998
Val   - Loss: 0.3748, Acc: 0.8203, F1: 0.7957

Epoch 3/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.12s/it, Loss=0.409, Acc=0.76]


Train - Loss: 0.4092, Acc: 0.8168, F1: 0.8081
Val   - Loss: 0.7078, Acc: 0.7717, F1: 0.7326

Epoch 4/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.397, Acc=0.88]


Train - Loss: 0.3968, Acc: 0.8286, F1: 0.8232
Val   - Loss: 0.3740, Acc: 0.8336, F1: 0.8307

Epoch 5/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.405, Acc=0.72]


Train - Loss: 0.4052, Acc: 0.8190, F1: 0.8125
Val   - Loss: 0.4640, Acc: 0.8513, F1: 0.8397

Epoch 6/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.13s/it, Loss=0.394, Acc=0.96]


Train - Loss: 0.3942, Acc: 0.8323, F1: 0.8229
Val   - Loss: 0.4070, Acc: 0.8336, F1: 0.8162

Epoch 7/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.392, Acc=0.88]


Train - Loss: 0.3917, Acc: 0.8323, F1: 0.8228
Val   - Loss: 0.5492, Acc: 0.7585, F1: 0.7600

Epoch 8/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.12s/it, Loss=0.392, Acc=0.92]


Train - Loss: 0.3915, Acc: 0.8330, F1: 0.8223
Val   - Loss: 0.3672, Acc: 0.8468, F1: 0.8367

Epoch 9/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.38, Acc=0.84]


Train - Loss: 0.3803, Acc: 0.8293, F1: 0.8205
Val   - Loss: 0.3976, Acc: 0.7997, F1: 0.7730

Epoch 10/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.375, Acc=0.84]


Train - Loss: 0.3748, Acc: 0.8404, F1: 0.8326
Val   - Loss: 0.4274, Acc: 0.8262, F1: 0.8275

Epoch 11/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.365, Acc=0.84]


Train - Loss: 0.3650, Acc: 0.8481, F1: 0.8414
Val   - Loss: 0.3867, Acc: 0.8218, F1: 0.8128

Epoch 12/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.376, Acc=0.88]


Train - Loss: 0.3762, Acc: 0.8378, F1: 0.8296
Val   - Loss: 0.4547, Acc: 0.8336, F1: 0.8283

Epoch 13/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.333, Acc=0.96]


Train - Loss: 0.3335, Acc: 0.8559, F1: 0.8482
Val   - Loss: 0.2911, Acc: 0.8675, F1: 0.8618

Epoch 14/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.309, Acc=0.8]


Train - Loss: 0.3090, Acc: 0.8662, F1: 0.8607
Val   - Loss: 0.3027, Acc: 0.8645, F1: 0.8572

Epoch 15/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.09s/it, Loss=0.311, Acc=0.84]


Train - Loss: 0.3114, Acc: 0.8728, F1: 0.8687
Val   - Loss: 0.2932, Acc: 0.8837, F1: 0.8808

Epoch 16/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.12s/it, Loss=0.288, Acc=0.96]


Train - Loss: 0.2881, Acc: 0.8773, F1: 0.8723
Val   - Loss: 0.4238, Acc: 0.8247, F1: 0.8059

Epoch 17/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.13s/it, Loss=0.302, Acc=0.84]


Train - Loss: 0.3021, Acc: 0.8691, F1: 0.8653
Val   - Loss: 0.2932, Acc: 0.8748, F1: 0.8691

Epoch 18/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.12s/it, Loss=0.281, Acc=0.96]


Train - Loss: 0.2812, Acc: 0.8758, F1: 0.8730
Val   - Loss: 0.2742, Acc: 0.8866, F1: 0.8826

Epoch 19/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.288, Acc=0.96]


Train - Loss: 0.2883, Acc: 0.8710, F1: 0.8669
Val   - Loss: 0.2621, Acc: 0.8881, F1: 0.8851

Epoch 20/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.276, Acc=0.96]


Train - Loss: 0.2760, Acc: 0.8839, F1: 0.8807
Val   - Loss: 0.2682, Acc: 0.8792, F1: 0.8730

Fold 2 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2883
Accuracy: 0.8710
Precision: 0.8690
Recall: 0.8710
F1-Score: 0.8669

Per-class Metrics:
  Immature (0): Precision=0.8800, Recall=0.9462, F1=0.9119
  Mature (1): Precision=0.8427, Recall=0.6909, F1=0.7593

Confusion Matrix:
[[1811  103]
 [ 247  552]]

Fold 2 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2621
Accuracy: 0.8881
Precision: 0.8875
Recall: 0.8881
F1-Score: 0.8851

Per-class Metrics:
  Immature (0): Precision=0.8909, Recall=0.9553, F1=0.9220
  Mature (1): Precision=0.8800, Recall=0.7368, F1=0.8021

Confusion Matrix:
[[449  21]
 [ 55 154]]

Fold 3/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.492, Acc=0.923]


Train - Loss: 0.4919, Acc: 0.7531, F1: 0.7370
Val   - Loss: 0.5162, Acc: 0.7625, F1: 0.7294

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.449, Acc=0.846]


Train - Loss: 0.4491, Acc: 0.7977, F1: 0.7839
Val   - Loss: 0.6489, Acc: 0.7094, F1: 0.7063

Epoch 3/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.398, Acc=0.808]


Train - Loss: 0.3985, Acc: 0.8147, F1: 0.8093
Val   - Loss: 0.4324, Acc: 0.8378, F1: 0.8343

Epoch 4/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.08s/it, Loss=0.426, Acc=0.846]


Train - Loss: 0.4263, Acc: 0.8113, F1: 0.8026
Val   - Loss: 0.4645, Acc: 0.8068, F1: 0.7909

Epoch 5/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.386, Acc=0.808]


Train - Loss: 0.3865, Acc: 0.8294, F1: 0.8242
Val   - Loss: 0.4431, Acc: 0.7979, F1: 0.7875

Epoch 6/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.413, Acc=0.885]


Train - Loss: 0.4135, Acc: 0.8239, F1: 0.8186
Val   - Loss: 0.4400, Acc: 0.8363, F1: 0.8333

Epoch 7/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.388, Acc=0.731]


Train - Loss: 0.3876, Acc: 0.8357, F1: 0.8306
Val   - Loss: 0.6237, Acc: 0.7640, F1: 0.7027

Epoch 8/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.08s/it, Loss=0.377, Acc=0.923]


Train - Loss: 0.3774, Acc: 0.8375, F1: 0.8348
Val   - Loss: 0.3272, Acc: 0.8850, F1: 0.8834

Epoch 9/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.08s/it, Loss=0.343, Acc=0.808]


Train - Loss: 0.3428, Acc: 0.8493, F1: 0.8443
Val   - Loss: 0.3619, Acc: 0.8378, F1: 0.8370

Epoch 10/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.324, Acc=0.846]


Train - Loss: 0.3239, Acc: 0.8622, F1: 0.8576
Val   - Loss: 0.3045, Acc: 0.8761, F1: 0.8689

Epoch 11/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.318, Acc=0.923]


Train - Loss: 0.3176, Acc: 0.8644, F1: 0.8599
Val   - Loss: 0.3282, Acc: 0.8584, F1: 0.8577

Epoch 12/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.307, Acc=0.923]


Train - Loss: 0.3073, Acc: 0.8662, F1: 0.8628
Val   - Loss: 0.3122, Acc: 0.8525, F1: 0.8447

Epoch 13/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.31, Acc=0.962]


Train - Loss: 0.3103, Acc: 0.8692, F1: 0.8662
Val   - Loss: 0.3359, Acc: 0.8407, F1: 0.8405

Epoch 14/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.305, Acc=0.923]


Train - Loss: 0.3046, Acc: 0.8666, F1: 0.8638
Val   - Loss: 0.3024, Acc: 0.8643, F1: 0.8629

Epoch 15/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.296, Acc=0.846]


Train - Loss: 0.2965, Acc: 0.8828, F1: 0.8804
Val   - Loss: 0.3703, Acc: 0.8569, F1: 0.8492

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.286, Acc=1]


Train - Loss: 0.2860, Acc: 0.8843, F1: 0.8825
Val   - Loss: 0.3236, Acc: 0.8702, F1: 0.8652

Epoch 17/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.283, Acc=0.962]


Train - Loss: 0.2835, Acc: 0.8758, F1: 0.8738
Val   - Loss: 0.2764, Acc: 0.8864, F1: 0.8846

Epoch 18/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.284, Acc=0.769]


Train - Loss: 0.2843, Acc: 0.8832, F1: 0.8812
Val   - Loss: 0.2613, Acc: 0.8909, F1: 0.8885

Epoch 19/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.272, Acc=0.846]


Train - Loss: 0.2721, Acc: 0.8850, F1: 0.8829
Val   - Loss: 0.2709, Acc: 0.8850, F1: 0.8811

Epoch 20/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.281, Acc=0.885]


Train - Loss: 0.2808, Acc: 0.8884, F1: 0.8859
Val   - Loss: 0.3041, Acc: 0.8628, F1: 0.8616

Fold 3 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2843
Accuracy: 0.8832
Precision: 0.8814
Recall: 0.8832
F1-Score: 0.8812

Per-class Metrics:
  Immature (0): Precision=0.8982, Recall=0.9394, F1=0.9184
  Mature (1): Precision=0.8422, Recall=0.7525, F1=0.7948

Confusion Matrix:
[[1783  115]
 [ 202  614]]

Fold 3 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2613
Accuracy: 0.8909
Precision: 0.8890
Recall: 0.8909
F1-Score: 0.8885

Per-class Metrics:
  Immature (0): Precision=0.9039, Recall=0.9486, F1=0.9257
  Mature (1): Precision=0.8512, Recall=0.7448, F1=0.7944

Confusion Matrix:
[[461  25]
 [ 49 143]]

Fold 4/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.471, Acc=0.885]


Train - Loss: 0.4706, Acc: 0.7915, F1: 0.7830
Val   - Loss: 0.4304, Acc: 0.8201, F1: 0.8215

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.427, Acc=0.808]


Train - Loss: 0.4266, Acc: 0.8073, F1: 0.7983
Val   - Loss: 0.4269, Acc: 0.8260, F1: 0.8257

Epoch 3/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.413, Acc=0.846]


Train - Loss: 0.4132, Acc: 0.8217, F1: 0.8135
Val   - Loss: 0.3962, Acc: 0.8319, F1: 0.8301

Epoch 4/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.441, Acc=0.885]


Train - Loss: 0.4410, Acc: 0.8084, F1: 0.7998
Val   - Loss: 0.4681, Acc: 0.7699, F1: 0.7157

Epoch 5/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.403, Acc=0.654]


Train - Loss: 0.4032, Acc: 0.8349, F1: 0.8292
Val   - Loss: 0.7383, Acc: 0.7035, F1: 0.7084

Epoch 6/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.12s/it, Loss=0.397, Acc=0.846]


Train - Loss: 0.3969, Acc: 0.8265, F1: 0.8192
Val   - Loss: 0.3848, Acc: 0.8363, F1: 0.8233

Epoch 7/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.402, Acc=0.808]


Train - Loss: 0.4016, Acc: 0.8276, F1: 0.8181
Val   - Loss: 0.4332, Acc: 0.8407, F1: 0.8355

Epoch 8/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.394, Acc=0.692]


Train - Loss: 0.3944, Acc: 0.8161, F1: 0.8049
Val   - Loss: 0.5172, Acc: 0.7788, F1: 0.7369

Epoch 9/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.12s/it, Loss=0.396, Acc=0.769]


Train - Loss: 0.3957, Acc: 0.8349, F1: 0.8267
Val   - Loss: 0.3966, Acc: 0.8171, F1: 0.8080

Epoch 10/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.12s/it, Loss=0.368, Acc=0.731]


Train - Loss: 0.3684, Acc: 0.8430, F1: 0.8367
Val   - Loss: 0.4391, Acc: 0.8038, F1: 0.7772

Epoch 11/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.338, Acc=0.846]


Train - Loss: 0.3381, Acc: 0.8644, F1: 0.8598
Val   - Loss: 0.3280, Acc: 0.8555, F1: 0.8465

Epoch 12/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.13s/it, Loss=0.323, Acc=0.885]


Train - Loss: 0.3226, Acc: 0.8567, F1: 0.8503
Val   - Loss: 0.3222, Acc: 0.8569, F1: 0.8522

Epoch 13/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.12s/it, Loss=0.316, Acc=0.923]


Train - Loss: 0.3161, Acc: 0.8681, F1: 0.8628
Val   - Loss: 0.3059, Acc: 0.8717, F1: 0.8645

Epoch 14/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.3, Acc=0.923]


Train - Loss: 0.3004, Acc: 0.8718, F1: 0.8680
Val   - Loss: 0.2829, Acc: 0.8658, F1: 0.8643

Epoch 15/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.291, Acc=0.962]


Train - Loss: 0.2913, Acc: 0.8769, F1: 0.8737
Val   - Loss: 0.3065, Acc: 0.8628, F1: 0.8545

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.12s/it, Loss=0.289, Acc=0.923]


Train - Loss: 0.2887, Acc: 0.8843, F1: 0.8815
Val   - Loss: 0.7246, Acc: 0.7773, F1: 0.7335

Epoch 17/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.13s/it, Loss=0.283, Acc=0.846]


Train - Loss: 0.2827, Acc: 0.8828, F1: 0.8791
Val   - Loss: 0.3027, Acc: 0.8673, F1: 0.8603

Epoch 18/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.13s/it, Loss=0.283, Acc=0.846]


Train - Loss: 0.2831, Acc: 0.8777, F1: 0.8746
Val   - Loss: 0.4893, Acc: 0.8289, F1: 0.8066

Epoch 19/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.245, Acc=0.962]


Train - Loss: 0.2448, Acc: 0.8968, F1: 0.8934
Val   - Loss: 0.2528, Acc: 0.8850, F1: 0.8830

Epoch 20/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.12s/it, Loss=0.261, Acc=0.885]


Train - Loss: 0.2606, Acc: 0.8917, F1: 0.8885
Val   - Loss: 0.2553, Acc: 0.8761, F1: 0.8723

Fold 4 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2448
Accuracy: 0.8968
Precision: 0.8972
Recall: 0.8968
F1-Score: 0.8934

Per-class Metrics:
  Immature (0): Precision=0.8952, Recall=0.9665, F1=0.9295
  Mature (1): Precision=0.9020, Recall=0.7317, F1=0.8080

Confusion Matrix:
[[1845   64]
 [ 216  589]]

Fold 4 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2528
Accuracy: 0.8850
Precision: 0.8832
Recall: 0.8850
F1-Score: 0.8830

Per-class Metrics:
  Immature (0): Precision=0.8994, Recall=0.9411, F1=0.9198
  Mature (1): Precision=0.8453, Recall=0.7537, F1=0.7969

Confusion Matrix:
[[447  28]
 [ 50 153]]

Fold 5/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.12s/it, Loss=0.506, Acc=0.731]


Train - Loss: 0.5056, Acc: 0.7561, F1: 0.7384
Val   - Loss: 0.4725, Acc: 0.7714, F1: 0.7510

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.445, Acc=0.923]


Train - Loss: 0.4455, Acc: 0.7937, F1: 0.7868
Val   - Loss: 0.4909, Acc: 0.8112, F1: 0.7817

Epoch 3/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.408, Acc=0.923]


Train - Loss: 0.4075, Acc: 0.8272, F1: 0.8223
Val   - Loss: 0.4223, Acc: 0.8378, F1: 0.8214

Epoch 4/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.426, Acc=0.692]


Train - Loss: 0.4261, Acc: 0.8220, F1: 0.8183
Val   - Loss: 0.3676, Acc: 0.8363, F1: 0.8271

Epoch 5/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.422, Acc=0.846]


Train - Loss: 0.4222, Acc: 0.8198, F1: 0.8124
Val   - Loss: 0.4116, Acc: 0.8378, F1: 0.8191

Epoch 6/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.402, Acc=0.692]


Train - Loss: 0.4017, Acc: 0.8272, F1: 0.8217
Val   - Loss: 0.3890, Acc: 0.8407, F1: 0.8372

Epoch 7/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.41, Acc=0.846]


Train - Loss: 0.4105, Acc: 0.8305, F1: 0.8222
Val   - Loss: 0.5150, Acc: 0.8127, F1: 0.7984

Epoch 8/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.37, Acc=0.885]


Train - Loss: 0.3698, Acc: 0.8312, F1: 0.8223
Val   - Loss: 0.3845, Acc: 0.8289, F1: 0.8268

Epoch 9/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.33, Acc=0.923]


Train - Loss: 0.3303, Acc: 0.8596, F1: 0.8520
Val   - Loss: 0.4643, Acc: 0.8260, F1: 0.8046

Epoch 10/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.12s/it, Loss=0.318, Acc=0.808]


Train - Loss: 0.3181, Acc: 0.8589, F1: 0.8523
Val   - Loss: 0.3081, Acc: 0.8776, F1: 0.8728

Epoch 11/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.12s/it, Loss=0.318, Acc=0.962]


Train - Loss: 0.3179, Acc: 0.8570, F1: 0.8504
Val   - Loss: 0.3007, Acc: 0.8835, F1: 0.8808

Epoch 12/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.308, Acc=0.962]


Train - Loss: 0.3082, Acc: 0.8633, F1: 0.8579
Val   - Loss: 0.2784, Acc: 0.8850, F1: 0.8831

Epoch 13/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.307, Acc=0.808]


Train - Loss: 0.3067, Acc: 0.8651, F1: 0.8608
Val   - Loss: 0.3251, Acc: 0.8732, F1: 0.8714

Epoch 14/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.287, Acc=0.885]


Train - Loss: 0.2873, Acc: 0.8814, F1: 0.8781
Val   - Loss: 0.2589, Acc: 0.8997, F1: 0.8947

Epoch 15/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.287, Acc=0.846]


Train - Loss: 0.2868, Acc: 0.8714, F1: 0.8673
Val   - Loss: 0.3015, Acc: 0.8614, F1: 0.8636

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.293, Acc=0.923]


Train - Loss: 0.2932, Acc: 0.8729, F1: 0.8692
Val   - Loss: 0.2819, Acc: 0.8894, F1: 0.8859

Epoch 17/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:24<00:00,  3.11s/it, Loss=0.282, Acc=0.885]


Train - Loss: 0.2824, Acc: 0.8821, F1: 0.8787
Val   - Loss: 0.2867, Acc: 0.8850, F1: 0.8850

Epoch 18/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.12s/it, Loss=0.275, Acc=0.808]


Train - Loss: 0.2749, Acc: 0.8858, F1: 0.8830
Val   - Loss: 0.2785, Acc: 0.8938, F1: 0.8946

Epoch 19/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.13s/it, Loss=0.263, Acc=0.808]


Train - Loss: 0.2628, Acc: 0.8884, F1: 0.8864
Val   - Loss: 0.2667, Acc: 0.8805, F1: 0.8796

Epoch 20/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.11s/it, Loss=0.263, Acc=0.885]


Train - Loss: 0.2631, Acc: 0.8876, F1: 0.8856
Val   - Loss: 0.2512, Acc: 0.9071, F1: 0.9055

Fold 5 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2631
Accuracy: 0.8876
Precision: 0.8861
Recall: 0.8876
F1-Score: 0.8856

Per-class Metrics:
  Immature (0): Precision=0.8998, Recall=0.9440, F1=0.9214
  Mature (1): Precision=0.8542, Recall=0.7573, F1=0.8028

Confusion Matrix:
[[1788  106]
 [ 199  621]]

Fold 5 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2512
Accuracy: 0.9071
Precision: 0.9057
Recall: 0.9071
F1-Score: 0.9055

Per-class Metrics:
  Immature (0): Precision=0.9194, Recall=0.9551, F1=0.9369
  Mature (1): Precision=0.8698, Recall=0.7819, F1=0.8235

Confusion Matrix:
[[468  22]
 [ 41 147]]

Cross-validation Results Summary:
Fold 1: Val Acc = 0.8866, Val F1 = 0.8851, Val Loss = 0.2977
Fold 2: Val Acc = 0.8881, Val F1 = 0.8851, Val Loss = 0.2621
Fold 3: Val Acc = 0.8909, Val F1 = 

Training: 100%|███████████████████████████████████████████████| 106/106 [05:31<00:00,  3.13s/it, Loss=0.469, Acc=0.812]


Training Set - Loss: 0.4689, Acc: 0.7821, F1: 0.7695
Test Set     - Loss: 0.3470, Acc: 0.8632, F1: 0.8611

Final Model - Epoch 2/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:32<00:00,  3.14s/it, Loss=0.427, Acc=0.719]


Training Set - Loss: 0.4265, Acc: 0.8196, F1: 0.8110
Test Set     - Loss: 0.3522, Acc: 0.8432, F1: 0.8265

Final Model - Epoch 3/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:30<00:00,  3.12s/it, Loss=0.409, Acc=0.844]


Training Set - Loss: 0.4086, Acc: 0.8222, F1: 0.8162
Test Set     - Loss: 0.3727, Acc: 0.8443, F1: 0.8438

Final Model - Epoch 4/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:29<00:00,  3.10s/it, Loss=0.382, Acc=0.812]


Training Set - Loss: 0.3817, Acc: 0.8373, F1: 0.8304
Test Set     - Loss: 0.3147, Acc: 0.8915, F1: 0.8900

Final Model - Epoch 5/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:29<00:00,  3.11s/it, Loss=0.371, Acc=0.906]


Training Set - Loss: 0.3707, Acc: 0.8449, F1: 0.8393
Test Set     - Loss: 0.5405, Acc: 0.7476, F1: 0.6764

Final Model - Epoch 6/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:29<00:00,  3.11s/it, Loss=0.374, Acc=0.812]


Training Set - Loss: 0.3741, Acc: 0.8337, F1: 0.8272
Test Set     - Loss: 0.4344, Acc: 0.7818, F1: 0.7530

Final Model - Epoch 7/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:30<00:00,  3.12s/it, Loss=0.369, Acc=0.812]


Training Set - Loss: 0.3686, Acc: 0.8432, F1: 0.8357
Test Set     - Loss: 0.3909, Acc: 0.8208, F1: 0.7968

Final Model - Epoch 8/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:30<00:00,  3.12s/it, Loss=0.354, Acc=0.875]


Training Set - Loss: 0.3542, Acc: 0.8467, F1: 0.8410
Test Set     - Loss: 0.3403, Acc: 0.8868, F1: 0.8879

Final Model - Epoch 9/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:30<00:00,  3.12s/it, Loss=0.316, Acc=0.906]


Training Set - Loss: 0.3157, Acc: 0.8670, F1: 0.8617
Test Set     - Loss: 0.2437, Acc: 0.9116, F1: 0.9094

Final Model - Epoch 10/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:31<00:00,  3.12s/it, Loss=0.288, Acc=0.906]


Training Set - Loss: 0.2882, Acc: 0.8865, F1: 0.8832
Test Set     - Loss: 0.2227, Acc: 0.9104, F1: 0.9068

Final Model - Epoch 11/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:33<00:00,  3.15s/it, Loss=0.288, Acc=0.875]


Training Set - Loss: 0.2876, Acc: 0.8771, F1: 0.8728
Test Set     - Loss: 0.2392, Acc: 0.9033, F1: 0.8980

Final Model - Epoch 12/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:33<00:00,  3.15s/it, Loss=0.266, Acc=0.938]


Training Set - Loss: 0.2663, Acc: 0.8830, F1: 0.8800
Test Set     - Loss: 0.2355, Acc: 0.9116, F1: 0.9082

Final Model - Epoch 13/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:30<00:00,  3.11s/it, Loss=0.272, Acc=0.812]


Training Set - Loss: 0.2723, Acc: 0.8806, F1: 0.8771
Test Set     - Loss: 0.2138, Acc: 0.9245, F1: 0.9236

Final Model - Epoch 14/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:26<00:00,  3.08s/it, Loss=0.262, Acc=0.844]


Training Set - Loss: 0.2621, Acc: 0.8903, F1: 0.8878
Test Set     - Loss: 0.2136, Acc: 0.9198, F1: 0.9190

Final Model - Epoch 15/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:27<00:00,  3.09s/it, Loss=0.255, Acc=0.812]


Training Set - Loss: 0.2550, Acc: 0.8892, F1: 0.8866
Test Set     - Loss: 0.2081, Acc: 0.9210, F1: 0.9187

Final Training Set Detailed Metrics:

Final Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2723
Accuracy: 0.8806
Precision: 0.8792
Recall: 0.8806
F1-Score: 0.8771

Per-class Metrics:
  Immature (0): Precision=0.8873, Recall=0.9509, F1=0.9180
  Mature (1): Precision=0.8602, Recall=0.7143, F1=0.7805

Confusion Matrix:
[[2267  117]
 [ 288  720]]

Test Set Detailed Metrics:

Test Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2138
Accuracy: 0.9245
Precision: 0.9239
Recall: 0.9245
F1-Score: 0.9236

Per-class Metrics:
  Immature (0): Precision=0.9318, Recall=0.9631, F1=0.9472
  Mature (1): Precision=0.9052, Recall=0.8333, F1=0.8678

Confusion Matrix:
[[574  22]
 [ 42 210]]

✓ Results saved to model_training_results.xlsx

Results Summary:
5-fold cross-validation average validation accuracy: 0.8915
Final training