In [2]:
import os
import sys
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset, SubsetRandomSampler
from torchvision import transforms, models
from PIL import Image
import numpy as np
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
from tqdm import tqdm
import warnings
import pandas as pd
import pickle
warnings.filterwarnings('ignore')

def check_gpu_available():
    if not torch.cuda.is_available():
        print("Error: No available GPU device detected.")
        print("Please ensure:")
        print("1. CUDA and cuDNN are installed")
        print("2. PyTorch version with GPU support is installed")
        print("3. Graphics card driver is up to date")
        print("\nProgram requires GPU for training, exiting now...")
        sys.exit(1)
    
    print(f"✓ GPU available: {torch.cuda.get_device_name(0)}")
    print(f"  Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
    print(f"  CUDA version: {torch.version.cuda}")
    return True

check_gpu_available()

def set_seed(seed=42):
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

class CustomDataset(Dataset):
    def __init__(self, image_paths, labels, transform=None):
        self.image_paths = image_paths
        self.labels = labels
        self.transform = transform
        
    def __len__(self):
        return len(self.image_paths)
    
    def __getitem__(self, idx):
        image = Image.open(self.image_paths[idx]).convert('RGB')
        label = self.labels[idx]
        
        if self.transform:
            image = self.transform(image)
            
        return image, label

def load_data(immature_dir, mature_dir):
    immature_paths = []
    mature_paths = []
    
    for img_name in os.listdir(immature_dir):
        if img_name.lower().endswith(('.jpg', '.jpeg', '.png')):
            immature_paths.append(os.path.join(immature_dir, img_name))
    
    for img_name in os.listdir(mature_dir):
        if img_name.lower().endswith(('.jpg', '.jpeg', '.png')):
            mature_paths.append(os.path.join(mature_dir, img_name))
    
    all_paths = immature_paths + mature_paths
    all_labels = [0] * len(immature_paths) + [1] * len(mature_paths)
    
    print(f"Immature images: {len(immature_paths)}")
    print(f"Mature images: {len(mature_paths)}")
    print(f"Total images: {len(all_paths)}")
    
    return all_paths, all_labels

def get_transforms():
    train_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.RandomRotation(10),
        transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                           std=[0.229, 0.224, 0.225])
    ])
    
    val_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                           std=[0.229, 0.224, 0.225])
    ])
    
    return train_transform, val_transform

def create_resnet50_model(num_classes=2):
    model = models.resnet50(pretrained=True)
    
    num_features = model.fc.in_features
    model.fc = nn.Sequential(
        nn.Dropout(0.5),
        nn.Linear(num_features, 256),
        nn.ReLU(),
        nn.Dropout(0.3),
        nn.Linear(256, num_classes)
    )
    
    return model

def calculate_metrics(all_labels, all_predictions):
    accuracy = np.mean(np.array(all_labels) == np.array(all_predictions))
    
    precision = precision_score(all_labels, all_predictions, average='weighted')
    recall = recall_score(all_labels, all_predictions, average='weighted')
    f1 = f1_score(all_labels, all_predictions, average='weighted')
    
    precision_per_class = precision_score(all_labels, all_predictions, average=None)
    recall_per_class = recall_score(all_labels, all_predictions, average=None)
    f1_per_class = f1_score(all_labels, all_predictions, average=None)
    
    cm = confusion_matrix(all_labels, all_predictions)
    
    report = classification_report(all_labels, all_predictions, 
                                  target_names=['immature', 'mature'], 
                                  output_dict=True)
    
    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'precision_per_class': precision_per_class,
        'recall_per_class': recall_per_class,
        'f1_per_class': f1_per_class,
        'confusion_matrix': cm,
        'classification_report': report
    }

def train_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    all_predictions = []
    all_labels = []
    
    progress_bar = tqdm(dataloader, desc='Training')
    for images, labels in progress_bar:
        images, labels = images.to(device), labels.to(device)
        
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        
        all_predictions.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
        
        batch_acc = (predicted == labels).sum().item() / labels.size(0)
        progress_bar.set_postfix({'Loss': running_loss/len(dataloader), 'Acc': batch_acc})
    
    epoch_loss = running_loss / len(dataloader)
    
    metrics = calculate_metrics(all_labels, all_predictions)
    metrics['loss'] = epoch_loss
    
    return epoch_loss, metrics

def evaluate_model(model, dataloader, criterion, device, dataset_name="Dataset"):
    model.eval()
    running_loss = 0.0
    all_predictions = []
    all_labels = []
    
    with torch.no_grad():
        for images, labels in dataloader:
            images, labels = images.to(device), labels.to(device)
            
            outputs = model(images)
            loss = criterion(outputs, labels)
            
            running_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            
            all_predictions.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    
    epoch_loss = running_loss / len(dataloader)
    
    metrics = calculate_metrics(all_labels, all_predictions)
    metrics['loss'] = epoch_loss
    
    return epoch_loss, metrics

def print_detailed_metrics(metrics, dataset_name="Dataset"):
    print(f"\n{dataset_name} Detailed Metrics:")
    print("-" * 50)
    print(f"Loss: {metrics['loss']:.4f}")
    print(f"Accuracy: {metrics['accuracy']:.4f}")
    print(f"Precision: {metrics['precision']:.4f}")
    print(f"Recall: {metrics['recall']:.4f}")
    print(f"F1-Score: {metrics['f1']:.4f}")
    
    print(f"\nPer-class Metrics:")
    print(f"  Immature (0): Precision={metrics['precision_per_class'][0]:.4f}, "
          f"Recall={metrics['recall_per_class'][0]:.4f}, F1={metrics['f1_per_class'][0]:.4f}")
    print(f"  Mature (1): Precision={metrics['precision_per_class'][1]:.4f}, "
          f"Recall={metrics['recall_per_class'][1]:.4f}, F1={metrics['f1_per_class'][1]:.4f}")
    
    print(f"\nConfusion Matrix:")
    print(metrics['confusion_matrix'])

def export_results_to_excel(fold_results, test_results, final_train_results, filename='training_results.xlsx'):
    all_results = []
    
    for fold_result in fold_results:
        fold_data = {
            'Fold': fold_result['fold'],
            'Dataset': 'Validation',
            'Loss': fold_result['val_loss'],
            'Accuracy': fold_result['val_accuracy'],
            'Precision': fold_result['val_precision'],
            'Recall': fold_result['val_recall'],
            'F1_Score': fold_result['val_f1'],
            'Precision_Class0': fold_result['val_precision_per_class'][0],
            'Precision_Class1': fold_result['val_precision_per_class'][1],
            'Recall_Class0': fold_result['val_recall_per_class'][0],
            'Recall_Class1': fold_result['val_recall_per_class'][1],
            'F1_Class0': fold_result['val_f1_per_class'][0],
            'F1_Class1': fold_result['val_f1_per_class'][1],
            'Train_Loss': fold_result['train_loss'],
            'Train_Accuracy': fold_result['train_accuracy'],
            'Train_Precision': fold_result['train_precision'],
            'Train_Recall': fold_result['train_recall'],
            'Train_F1_Score': fold_result['train_f1']
        }
        all_results.append(fold_data)
    
    final_train_data = {
        'Fold': 'Final',
        'Dataset': 'Train',
        'Loss': final_train_results['loss'],
        'Accuracy': final_train_results['accuracy'],
        'Precision': final_train_results['precision'],
        'Recall': final_train_results['recall'],
        'F1_Score': final_train_results['f1'],
        'Precision_Class0': final_train_results['precision_per_class'][0],
        'Precision_Class1': final_train_results['precision_per_class'][1],
        'Recall_Class0': final_train_results['recall_per_class'][0],
        'Recall_Class1': final_train_results['recall_per_class'][1],
        'F1_Class0': final_train_results['f1_per_class'][0],
        'F1_Class1': final_train_results['f1_per_class'][1],
        'Train_Loss': final_train_results['loss'],
        'Train_Accuracy': final_train_results['accuracy'],
        'Train_Precision': final_train_results['precision'],
        'Train_Recall': final_train_results['recall'],
        'Train_F1_Score': final_train_results['f1']
    }
    all_results.append(final_train_data)
    
    test_data = {
        'Fold': 'Final',
        'Dataset': 'Test',
        'Loss': test_results['loss'],
        'Accuracy': test_results['accuracy'],
        'Precision': test_results['precision'],
        'Recall': test_results['recall'],
        'F1_Score': test_results['f1'],
        'Precision_Class0': test_results['precision_per_class'][0],
        'Precision_Class1': test_results['precision_per_class'][1],
        'Recall_Class0': test_results['recall_per_class'][0],
        'Recall_Class1': test_results['recall_per_class'][1],
        'F1_Class0': test_results['f1_per_class'][0],
        'F1_Class1': test_results['f1_per_class'][1],
        'Train_Loss': final_train_results['loss'],
        'Train_Accuracy': final_train_results['accuracy'],
        'Train_Precision': final_train_results['precision'],
        'Train_Recall': final_train_results['recall'],
        'Train_F1_Score': final_train_results['f1']
    }
    all_results.append(test_data)
    
    df = pd.DataFrame(all_results)
    
    validation_df = df[df['Dataset'] == 'Validation']
    if not validation_df.empty:
        avg_row = {
            'Fold': 'Average',
            'Dataset': 'Validation',
            'Loss': validation_df['Loss'].mean(),
            'Accuracy': validation_df['Accuracy'].mean(),
            'Precision': validation_df['Precision'].mean(),
            'Recall': validation_df['Recall'].mean(),
            'F1_Score': validation_df['F1_Score'].mean(),
            'Precision_Class0': validation_df['Precision_Class0'].mean(),
            'Precision_Class1': validation_df['Precision_Class1'].mean(),
            'Recall_Class0': validation_df['Recall_Class0'].mean(),
            'Recall_Class1': validation_df['Recall_Class1'].mean(),
            'F1_Class0': validation_df['F1_Class0'].mean(),
            'F1_Class1': validation_df['F1_Class1'].mean(),
            'Train_Loss': validation_df['Train_Loss'].mean(),
            'Train_Accuracy': validation_df['Train_Accuracy'].mean(),
            'Train_Precision': validation_df['Train_Precision'].mean(),
            'Train_Recall': validation_df['Train_Recall'].mean(),
            'Train_F1_Score': validation_df['Train_F1_Score'].mean()
        }
        
        df = pd.concat([df, pd.DataFrame([avg_row])], ignore_index=True)
    
    df.to_excel(filename, index=False)
    print(f"\n✓ Results saved to {filename}")
    
    print("\n" + "="*80)
    print("Summary of Results:")
    print("="*80)
    if not validation_df.empty:
        print(f"5-fold cross validation average validation accuracy: {validation_df['Accuracy'].mean():.4f}")
    print(f"Final training set accuracy: {final_train_results['accuracy']:.4f}")
    print(f"Test set accuracy: {test_results['accuracy']:.4f}")
    print(f"Test set F1 score: {test_results['f1']:.4f}")
    
    return df

def main():
    immature_dir = r"E:\TSG\jupyterlab\machine learning image\augmented_dataset\immature"
    mature_dir = r"E:\TSG\jupyterlab\machine learning image\augmented_dataset\mature"
    
    print("Loading data...")
    all_paths, all_labels = load_data(immature_dir, mature_dir)
    
    print("\nSplitting data into train and test sets...")
    train_paths, test_paths, train_labels, test_labels = train_test_split(
        all_paths, all_labels, test_size=0.2, random_state=42, stratify=all_labels
    )
    
    print(f"Train set size: {len(train_paths)}")
    print(f"Test set size: {len(test_paths)}")
    
    train_transform, val_transform = get_transforms()
    
    train_dataset = CustomDataset(train_paths, train_labels, train_transform)
    test_dataset = CustomDataset(test_paths, test_labels, val_transform)
    
    device = torch.device("cuda")
    print(f"\nUsing device: {device}")
    
    print("\nStarting 5-fold cross validation...")
    kfold = KFold(n_splits=5, shuffle=True, random_state=42)
    fold_results = []
    
    for fold, (train_idx, val_idx) in enumerate(kfold.split(train_dataset)):
        print(f"\n{'='*60}")
        print(f"Fold {fold+1}/5")
        print(f"{'='*60}")
        
        train_subsampler = SubsetRandomSampler(train_idx)
        val_subsampler = SubsetRandomSampler(val_idx)
        
        train_loader = DataLoader(train_dataset, batch_size=32, sampler=train_subsampler)
        val_loader = DataLoader(train_dataset, batch_size=32, sampler=val_subsampler)
        
        model = create_resnet50_model(num_classes=2)
        model = model.to(device)
        
        criterion = nn.CrossEntropyLoss()
        optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-4)
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', patience=3)
        
        num_epochs = 20
        best_val_acc = 0
        best_model_state = None
        best_train_metrics = None
        best_val_metrics = None
        best_train_loss = None
        
        for epoch in range(num_epochs):
            print(f"\nEpoch {epoch+1}/{num_epochs}")
            
            train_loss, train_metrics = train_epoch(model, train_loader, criterion, optimizer, device)
            
            val_loss, val_metrics = evaluate_model(model, val_loader, criterion, device, "Validation")
            
            scheduler.step(val_loss)
            
            print(f"Train - Loss: {train_loss:.4f}, Acc: {train_metrics['accuracy']:.4f}, "
                  f"F1: {train_metrics['f1']:.4f}")
            print(f"Val   - Loss: {val_loss:.4f}, Acc: {val_metrics['accuracy']:.4f}, "
                  f"F1: {val_metrics['f1']:.4f}")
            
            if val_metrics['accuracy'] > best_val_acc:
                best_val_acc = val_metrics['accuracy']
                best_model_state = model.state_dict().copy()
                best_train_metrics = train_metrics
                best_val_metrics = val_metrics
                best_train_loss = train_loss
        
        print_detailed_metrics(best_train_metrics, f"Fold {fold+1} - Best Training Set")
        print_detailed_metrics(best_val_metrics, f"Fold {fold+1} - Best Validation Set")
        
        fold_results.append({
            'fold': fold + 1,
            'best_val_acc': best_val_acc,
            'val_loss': best_val_metrics['loss'],
            'val_accuracy': best_val_metrics['accuracy'],
            'val_precision': best_val_metrics['precision'],
            'val_recall': best_val_metrics['recall'],
            'val_f1': best_val_metrics['f1'],
            'val_precision_per_class': best_val_metrics['precision_per_class'],
            'val_recall_per_class': best_val_metrics['recall_per_class'],
            'val_f1_per_class': best_val_metrics['f1_per_class'],
            'train_loss': best_train_loss,
            'train_accuracy': best_train_metrics['accuracy'],
            'train_precision': best_train_metrics['precision'],
            'train_recall': best_train_metrics['recall'],
            'train_f1': best_train_metrics['f1'],
            'model_state': best_model_state
        })
    
    print("\n" + "="*60)
    print("Cross Validation Results Summary:")
    print("="*60)
    for result in fold_results:
        print(f"Fold {result['fold']}: "
              f"Val Acc = {result['best_val_acc']:.4f}, "
              f"Val F1 = {result['val_f1']:.4f}, "
              f"Val Loss = {result['val_loss']:.4f}")
    
    avg_val_acc = np.mean([r['best_val_acc'] for r in fold_results])
    avg_val_f1 = np.mean([r['val_f1'] for r in fold_results])
    avg_val_loss = np.mean([r['val_loss'] for r in fold_results])
    print(f"\nAverage Validation Accuracy: {avg_val_acc:.4f}")
    print(f"Average Validation F1 Score: {avg_val_f1:.4f}")
    print(f"Average Validation Loss: {avg_val_loss:.4f}")
    
    print("\n" + "="*60)
    print("Evaluating Final Model on Test Set...")
    print("="*60)
    
    print("\nTraining final model on entire training set...")
    final_train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)
    
    final_model = create_resnet50_model(num_classes=2)
    final_model = final_model.to(device)
    
    final_criterion = nn.CrossEntropyLoss()
    final_optimizer = optim.Adam(final_model.parameters(), lr=0.001)
    final_scheduler = optim.lr_scheduler.ReduceLROnPlateau(final_optimizer, mode='min', patience=3)
    
    num_final_epochs = 15
    best_test_acc = 0
    best_test_metrics = None
    best_final_train_metrics = None
    best_final_train_loss = None
    
    for epoch in range(num_final_epochs):
        print(f"\nFinal Model - Epoch {epoch+1}/{num_final_epochs}")
        
        train_loss, train_metrics = train_epoch(final_model, final_train_loader, final_criterion, final_optimizer, device)
        
        test_loss, test_metrics = evaluate_model(final_model, test_loader, final_criterion, device, "Test")
        
        final_scheduler.step(test_loss)
        
        print(f"Training Set - Loss: {train_loss:.4f}, Acc: {train_metrics['accuracy']:.4f}, "
              f"F1: {train_metrics['f1']:.4f}")
        print(f"Test Set - Loss: {test_loss:.4f}, Acc: {test_metrics['accuracy']:.4f}, "
              f"F1: {test_metrics['f1']:.4f}")
        
        if test_metrics['accuracy'] > best_test_acc:
            best_test_acc = test_metrics['accuracy']
            best_test_metrics = test_metrics
            best_final_train_metrics = train_metrics
            best_final_train_loss = train_loss
            torch.save(final_model.state_dict(), 'best_resnet50_model.pth')
    
    print("\n" + "="*60)
    print("Final Training Set Detailed Metrics:")
    print("="*60)
    print_detailed_metrics(best_final_train_metrics, "Final Training Set")
    
    print("\n" + "="*60)
    print("Test Set Detailed Metrics:")
    print("="*60)
    print_detailed_metrics(best_test_metrics, "Test Set")
    
    export_results_to_excel(fold_results, best_test_metrics, best_final_train_metrics, 'model_training_results.xlsx')
    
    def predict_single_image(image_path, model_path='best_resnet50_model.pth'):
        model = create_resnet50_model(num_classes=2)
        model.load_state_dict(torch.load(model_path, map_location=device))
        model = model.to(device)
        model.eval()
        
        image = Image.open(image_path).convert('RGB')
        transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                               std=[0.229, 0.224, 0.225])
        ])
        
        image_tensor = transform(image).unsqueeze(0).to(device)
        
        with torch.no_grad():
            outputs = model(image_tensor)
            probabilities = torch.softmax(outputs, dim=1)
            _, predicted = torch.max(outputs, 1)
            
            class_names = ['immature', 'mature']
            result = class_names[predicted.item()]
            confidence = probabilities[0][predicted.item()].item()
            
        return result, confidence
    
    print("\n" + "="*60)
    print("Model is ready for prediction!")
    print("Use predict_single_image('path/to/image.jpg') to classify new images.")
    print("="*60)
    
    with open('classifier_info.pkl', 'wb') as f:
        pickle.dump({
            'train_paths': train_paths,
            'test_paths': test_paths,
            'train_labels': train_labels,
            'test_labels': test_labels,
            'class_names': ['immature', 'mature'],
            'normalization_mean': [0.485, 0.456, 0.406],
            'normalization_std': [0.229, 0.224, 0.225],
            'fold_results': fold_results,
            'test_results': best_test_metrics,
            'final_train_results': best_final_train_metrics
        }, f)
    
    return final_model, best_test_metrics, best_final_train_metrics

if __name__ == "__main__":
    model, test_results, train_results = main()

✓ GPU available: NVIDIA GeForce RTX 5070 Ti
  Memory: 17.09 GB
  CUDA version: 11.8
Loading data...
Immature images: 2980
Mature images: 1260
Total images: 4240

Splitting data into train and test sets...
Train set size: 3392
Test set size: 848

Using device: cuda

Starting 5-fold cross validation...

Fold 1/5

Epoch 1/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.20s/it, Loss=0.528, Acc=0.68]


Train - Loss: 0.5277, Acc: 0.7409, F1: 0.7040
Val   - Loss: 0.5567, Acc: 0.6892, F1: 0.5722

Epoch 2/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.463, Acc=0.68]


Train - Loss: 0.4633, Acc: 0.7696, F1: 0.7441
Val   - Loss: 0.4833, Acc: 0.6907, F1: 0.5730

Epoch 3/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.436, Acc=0.6]


Train - Loss: 0.4364, Acc: 0.7995, F1: 0.7896
Val   - Loss: 1.0245, Acc: 0.8203, F1: 0.8051

Epoch 4/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.456, Acc=0.72]


Train - Loss: 0.4557, Acc: 0.7895, F1: 0.7807
Val   - Loss: 0.4256, Acc: 0.8321, F1: 0.8244

Epoch 5/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.428, Acc=0.92]


Train - Loss: 0.4280, Acc: 0.8245, F1: 0.8202
Val   - Loss: 0.6147, Acc: 0.7143, F1: 0.6513

Epoch 6/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.17s/it, Loss=0.413, Acc=0.76]


Train - Loss: 0.4134, Acc: 0.8209, F1: 0.8132
Val   - Loss: 0.5330, Acc: 0.7732, F1: 0.7307

Epoch 7/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.411, Acc=0.76]


Train - Loss: 0.4107, Acc: 0.8183, F1: 0.8141
Val   - Loss: 0.6282, Acc: 0.6156, F1: 0.6164

Epoch 8/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.413, Acc=0.88]


Train - Loss: 0.4127, Acc: 0.8201, F1: 0.8077
Val   - Loss: 0.7123, Acc: 0.7216, F1: 0.7312

Epoch 9/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.367, Acc=0.84]


Train - Loss: 0.3669, Acc: 0.8433, F1: 0.8353
Val   - Loss: 0.3616, Acc: 0.8454, F1: 0.8440

Epoch 10/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.16s/it, Loss=0.369, Acc=0.72]


Train - Loss: 0.3689, Acc: 0.8422, F1: 0.8358
Val   - Loss: 0.3443, Acc: 0.8513, F1: 0.8455

Epoch 11/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.36, Acc=0.76]


Train - Loss: 0.3600, Acc: 0.8489, F1: 0.8426
Val   - Loss: 0.3139, Acc: 0.8719, F1: 0.8709

Epoch 12/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.17s/it, Loss=0.352, Acc=0.84]


Train - Loss: 0.3519, Acc: 0.8489, F1: 0.8413
Val   - Loss: 0.3384, Acc: 0.8527, F1: 0.8520

Epoch 13/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.354, Acc=0.84]


Train - Loss: 0.3542, Acc: 0.8507, F1: 0.8436
Val   - Loss: 0.3227, Acc: 0.8601, F1: 0.8583

Epoch 14/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.343, Acc=0.84]


Train - Loss: 0.3426, Acc: 0.8570, F1: 0.8498
Val   - Loss: 0.3693, Acc: 0.8247, F1: 0.8279

Epoch 15/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.337, Acc=0.88]


Train - Loss: 0.3366, Acc: 0.8603, F1: 0.8547
Val   - Loss: 0.3121, Acc: 0.8675, F1: 0.8639

Epoch 16/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.33, Acc=0.92]


Train - Loss: 0.3302, Acc: 0.8669, F1: 0.8622
Val   - Loss: 0.3570, Acc: 0.8439, F1: 0.8462

Epoch 17/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.06s/it, Loss=0.34, Acc=0.92]


Train - Loss: 0.3397, Acc: 0.8537, F1: 0.8469
Val   - Loss: 0.3253, Acc: 0.8660, F1: 0.8648

Epoch 18/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.323, Acc=0.88]


Train - Loss: 0.3228, Acc: 0.8688, F1: 0.8632
Val   - Loss: 0.3202, Acc: 0.8645, F1: 0.8634

Epoch 19/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.326, Acc=0.76]


Train - Loss: 0.3260, Acc: 0.8555, F1: 0.8486
Val   - Loss: 0.3479, Acc: 0.8321, F1: 0.8155

Epoch 20/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.07s/it, Loss=0.311, Acc=0.8]


Train - Loss: 0.3107, Acc: 0.8655, F1: 0.8602
Val   - Loss: 0.2865, Acc: 0.8763, F1: 0.8725

Fold 1 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3107
Accuracy: 0.8655
Precision: 0.8637
Recall: 0.8655
F1-Score: 0.8602

Per-class Metrics:
  Immature (0): Precision=0.8719, Recall=0.9495, F1=0.9090
  Mature (1): Precision=0.8438, Recall=0.6616, F1=0.7417

Confusion Matrix:
[[1824   97]
 [ 268  524]]

Fold 1 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2865
Accuracy: 0.8763
Precision: 0.8762
Recall: 0.8763
F1-Score: 0.8725

Per-class Metrics:
  Immature (0): Precision=0.8767, Recall=0.9525, F1=0.9130
  Mature (1): Precision=0.8750, Recall=0.7130, F1=0.7857

Confusion Matrix:
[[441  22]
 [ 62 154]]

Fold 2/5

Epoch 1/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.06s/it, Loss=0.581, Acc=0.88]


Train - Loss: 0.5813, Acc: 0.6966, F1: 0.5960
Val   - Loss: 0.5222, Acc: 0.7408, F1: 0.7343

Epoch 2/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:19<00:00,  3.05s/it, Loss=0.503, Acc=0.8]


Train - Loss: 0.5035, Acc: 0.7475, F1: 0.7086
Val   - Loss: 0.7471, Acc: 0.7452, F1: 0.6782

Epoch 3/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.07s/it, Loss=0.46, Acc=0.76]


Train - Loss: 0.4596, Acc: 0.7799, F1: 0.7632
Val   - Loss: 0.5014, Acc: 0.7555, F1: 0.7576

Epoch 4/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.07s/it, Loss=0.447, Acc=0.8]


Train - Loss: 0.4468, Acc: 0.7980, F1: 0.7915
Val   - Loss: 0.5976, Acc: 0.7599, F1: 0.7036

Epoch 5/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.455, Acc=0.68]


Train - Loss: 0.4553, Acc: 0.7888, F1: 0.7792
Val   - Loss: 0.8865, Acc: 0.7423, F1: 0.7410

Epoch 6/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.07s/it, Loss=0.428, Acc=0.68]


Train - Loss: 0.4280, Acc: 0.8161, F1: 0.8058
Val   - Loss: 0.4593, Acc: 0.7688, F1: 0.7709

Epoch 7/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.07s/it, Loss=0.42, Acc=0.96]


Train - Loss: 0.4199, Acc: 0.8113, F1: 0.8020
Val   - Loss: 0.4779, Acc: 0.7909, F1: 0.7966

Epoch 8/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:19<00:00,  3.06s/it, Loss=0.418, Acc=0.72]


Train - Loss: 0.4178, Acc: 0.8146, F1: 0.8046
Val   - Loss: 0.6580, Acc: 0.7761, F1: 0.7636

Epoch 9/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:19<00:00,  3.05s/it, Loss=0.415, Acc=0.64]


Train - Loss: 0.4149, Acc: 0.8245, F1: 0.8134
Val   - Loss: 0.4029, Acc: 0.8262, F1: 0.8165

Epoch 10/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:19<00:00,  3.06s/it, Loss=0.405, Acc=0.92]


Train - Loss: 0.4049, Acc: 0.8271, F1: 0.8186
Val   - Loss: 0.4525, Acc: 0.8203, F1: 0.8234

Epoch 11/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.06s/it, Loss=0.393, Acc=0.8]


Train - Loss: 0.3932, Acc: 0.8190, F1: 0.8081
Val   - Loss: 0.4383, Acc: 0.8321, F1: 0.8291

Epoch 12/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.08s/it, Loss=0.385, Acc=0.76]


Train - Loss: 0.3849, Acc: 0.8275, F1: 0.8169
Val   - Loss: 0.3511, Acc: 0.8351, F1: 0.8297

Epoch 13/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.378, Acc=0.96]


Train - Loss: 0.3783, Acc: 0.8227, F1: 0.8137
Val   - Loss: 0.3380, Acc: 0.8778, F1: 0.8766

Epoch 14/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.07s/it, Loss=0.369, Acc=0.92]


Train - Loss: 0.3694, Acc: 0.8382, F1: 0.8282
Val   - Loss: 1.6131, Acc: 0.5538, F1: 0.5687

Epoch 15/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.06s/it, Loss=0.381, Acc=0.92]


Train - Loss: 0.3810, Acc: 0.8338, F1: 0.8247
Val   - Loss: 0.3973, Acc: 0.8395, F1: 0.8350

Epoch 16/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:19<00:00,  3.06s/it, Loss=0.388, Acc=0.84]


Train - Loss: 0.3876, Acc: 0.8290, F1: 0.8219
Val   - Loss: 0.4056, Acc: 0.8144, F1: 0.8176

Epoch 17/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.06s/it, Loss=0.385, Acc=0.8]


Train - Loss: 0.3851, Acc: 0.8304, F1: 0.8232
Val   - Loss: 0.4066, Acc: 0.8292, F1: 0.8316

Epoch 18/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:19<00:00,  3.06s/it, Loss=0.372, Acc=0.92]


Train - Loss: 0.3723, Acc: 0.8419, F1: 0.8335
Val   - Loss: 0.3280, Acc: 0.8527, F1: 0.8485

Epoch 19/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.07s/it, Loss=0.34, Acc=0.96]


Train - Loss: 0.3399, Acc: 0.8544, F1: 0.8488
Val   - Loss: 0.3199, Acc: 0.8660, F1: 0.8589

Epoch 20/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.334, Acc=0.8]


Train - Loss: 0.3337, Acc: 0.8515, F1: 0.8461
Val   - Loss: 0.3683, Acc: 0.8498, F1: 0.8476

Fold 2 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3783
Accuracy: 0.8227
Precision: 0.8176
Recall: 0.8227
F1-Score: 0.8137

Per-class Metrics:
  Immature (0): Precision=0.8369, Recall=0.9300, F1=0.8810
  Mature (1): Precision=0.7713, Recall=0.5657, F1=0.6527

Confusion Matrix:
[[1780  134]
 [ 347  452]]

Fold 2 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3380
Accuracy: 0.8778
Precision: 0.8762
Recall: 0.8778
F1-Score: 0.8766

Per-class Metrics:
  Immature (0): Precision=0.9006, Recall=0.9255, F1=0.9129
  Mature (1): Precision=0.8214, Recall=0.7703, F1=0.7951

Confusion Matrix:
[[435  35]
 [ 48 161]]

Fold 3/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.501, Acc=0.769]


Train - Loss: 0.5013, Acc: 0.7542, F1: 0.7368
Val   - Loss: 0.4393, Acc: 0.7935, F1: 0.7762

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.437, Acc=0.731]


Train - Loss: 0.4366, Acc: 0.7955, F1: 0.7836
Val   - Loss: 0.5413, Acc: 0.7168, F1: 0.5986

Epoch 3/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.434, Acc=0.923]


Train - Loss: 0.4345, Acc: 0.8073, F1: 0.7962
Val   - Loss: 0.8097, Acc: 0.7419, F1: 0.7156

Epoch 4/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.06s/it, Loss=0.4, Acc=0.885]


Train - Loss: 0.3999, Acc: 0.8224, F1: 0.8172
Val   - Loss: 0.3978, Acc: 0.8245, F1: 0.8264

Epoch 5/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.06s/it, Loss=0.413, Acc=0.731]


Train - Loss: 0.4127, Acc: 0.8139, F1: 0.8076
Val   - Loss: 1.6377, Acc: 0.6888, F1: 0.7018

Epoch 6/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.07s/it, Loss=0.393, Acc=0.846]


Train - Loss: 0.3934, Acc: 0.8231, F1: 0.8167
Val   - Loss: 0.3967, Acc: 0.8260, F1: 0.8013

Epoch 7/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.07s/it, Loss=0.381, Acc=0.846]


Train - Loss: 0.3810, Acc: 0.8382, F1: 0.8328
Val   - Loss: 0.7418, Acc: 0.6136, F1: 0.6269

Epoch 8/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:19<00:00,  3.06s/it, Loss=0.382, Acc=0.846]


Train - Loss: 0.3819, Acc: 0.8331, F1: 0.8270
Val   - Loss: 0.4166, Acc: 0.8024, F1: 0.8091

Epoch 9/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.06s/it, Loss=0.367, Acc=0.846]


Train - Loss: 0.3675, Acc: 0.8316, F1: 0.8254
Val   - Loss: 0.5089, Acc: 0.7965, F1: 0.7818

Epoch 10/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.06s/it, Loss=0.39, Acc=0.769]


Train - Loss: 0.3896, Acc: 0.8353, F1: 0.8281
Val   - Loss: 0.4653, Acc: 0.7611, F1: 0.7595

Epoch 11/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.07s/it, Loss=0.342, Acc=0.731]


Train - Loss: 0.3421, Acc: 0.8515, F1: 0.8467
Val   - Loss: 0.3569, Acc: 0.8702, F1: 0.8640

Epoch 12/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.318, Acc=0.923]


Train - Loss: 0.3183, Acc: 0.8648, F1: 0.8605
Val   - Loss: 0.3682, Acc: 0.8348, F1: 0.8395

Epoch 13/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.07s/it, Loss=0.32, Acc=0.731]


Train - Loss: 0.3197, Acc: 0.8648, F1: 0.8609
Val   - Loss: 0.5242, Acc: 0.7699, F1: 0.7806

Epoch 14/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.29, Acc=0.962]


Train - Loss: 0.2903, Acc: 0.8755, F1: 0.8729
Val   - Loss: 0.8994, Acc: 0.6770, F1: 0.6902

Epoch 15/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.07s/it, Loss=0.299, Acc=0.885]


Train - Loss: 0.2988, Acc: 0.8699, F1: 0.8661
Val   - Loss: 0.5013, Acc: 0.8068, F1: 0.7782

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.07s/it, Loss=0.298, Acc=0.923]


Train - Loss: 0.2980, Acc: 0.8696, F1: 0.8662
Val   - Loss: 0.2927, Acc: 0.8864, F1: 0.8863

Epoch 17/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.07s/it, Loss=0.284, Acc=0.923]


Train - Loss: 0.2836, Acc: 0.8784, F1: 0.8758
Val   - Loss: 0.2841, Acc: 0.8909, F1: 0.8876

Epoch 18/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.289, Acc=0.731]


Train - Loss: 0.2894, Acc: 0.8755, F1: 0.8722
Val   - Loss: 0.2874, Acc: 0.8805, F1: 0.8781

Epoch 19/20


Training: 100%|██████████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.07s/it, Loss=0.27, Acc=1]


Train - Loss: 0.2703, Acc: 0.8847, F1: 0.8817
Val   - Loss: 0.3011, Acc: 0.8702, F1: 0.8702

Epoch 20/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.07s/it, Loss=0.276, Acc=0.962]


Train - Loss: 0.2762, Acc: 0.8810, F1: 0.8786
Val   - Loss: 0.3022, Acc: 0.8746, F1: 0.8688

Fold 3 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2836
Accuracy: 0.8784
Precision: 0.8765
Recall: 0.8784
F1-Score: 0.8758

Per-class Metrics:
  Immature (0): Precision=0.8912, Recall=0.9410, F1=0.9154
  Mature (1): Precision=0.8423, Recall=0.7328, F1=0.7837

Confusion Matrix:
[[1786  112]
 [ 218  598]]

Fold 3 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2841
Accuracy: 0.8909
Precision: 0.8895
Recall: 0.8909
F1-Score: 0.8876

Per-class Metrics:
  Immature (0): Precision=0.8977, Recall=0.9568, F1=0.9263
  Mature (1): Precision=0.8688, Recall=0.7240, F1=0.7898

Confusion Matrix:
[[465  21]
 [ 53 139]]

Fold 4/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.502, Acc=0.654]


Train - Loss: 0.5016, Acc: 0.7576, F1: 0.7416
Val   - Loss: 1.5600, Acc: 0.7035, F1: 0.5841

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.445, Acc=0.769]


Train - Loss: 0.4453, Acc: 0.8073, F1: 0.8002
Val   - Loss: 0.7950, Acc: 0.7006, F1: 0.5772

Epoch 3/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.08s/it, Loss=0.417, Acc=0.808]


Train - Loss: 0.4167, Acc: 0.8202, F1: 0.8116
Val   - Loss: 0.5588, Acc: 0.7286, F1: 0.6382

Epoch 4/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.413, Acc=0.808]


Train - Loss: 0.4131, Acc: 0.8294, F1: 0.8208
Val   - Loss: 0.4201, Acc: 0.7743, F1: 0.7277

Epoch 5/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.396, Acc=0.769]


Train - Loss: 0.3964, Acc: 0.8305, F1: 0.8219
Val   - Loss: 0.4290, Acc: 0.7965, F1: 0.7722

Epoch 6/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.401, Acc=0.962]


Train - Loss: 0.4006, Acc: 0.8331, F1: 0.8254
Val   - Loss: 0.7435, Acc: 0.6903, F1: 0.7029

Epoch 7/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.399, Acc=0.846]


Train - Loss: 0.3991, Acc: 0.8287, F1: 0.8221
Val   - Loss: 0.4341, Acc: 0.8053, F1: 0.8039

Epoch 8/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.39, Acc=0.692]


Train - Loss: 0.3898, Acc: 0.8265, F1: 0.8168
Val   - Loss: 1.1606, Acc: 0.7035, F1: 0.5893

Epoch 9/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.08s/it, Loss=0.344, Acc=0.808]


Train - Loss: 0.3444, Acc: 0.8585, F1: 0.8531
Val   - Loss: 0.3964, Acc: 0.8230, F1: 0.8248

Epoch 10/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.335, Acc=0.885]


Train - Loss: 0.3355, Acc: 0.8530, F1: 0.8462
Val   - Loss: 0.5591, Acc: 0.7566, F1: 0.6972

Epoch 11/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.328, Acc=0.846]


Train - Loss: 0.3285, Acc: 0.8607, F1: 0.8556
Val   - Loss: 0.3027, Acc: 0.8555, F1: 0.8539

Epoch 12/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.322, Acc=0.808]


Train - Loss: 0.3224, Acc: 0.8592, F1: 0.8550
Val   - Loss: 0.5662, Acc: 0.7640, F1: 0.7122

Epoch 13/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.315, Acc=0.769]


Train - Loss: 0.3145, Acc: 0.8703, F1: 0.8662
Val   - Loss: 0.3993, Acc: 0.8053, F1: 0.8113

Epoch 14/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.313, Acc=0.885]


Train - Loss: 0.3131, Acc: 0.8600, F1: 0.8548
Val   - Loss: 0.7461, Acc: 0.7375, F1: 0.6628

Epoch 15/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.305, Acc=0.808]


Train - Loss: 0.3054, Acc: 0.8662, F1: 0.8624
Val   - Loss: 0.2900, Acc: 0.8599, F1: 0.8581

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.313, Acc=0.808]


Train - Loss: 0.3126, Acc: 0.8626, F1: 0.8570
Val   - Loss: 0.5198, Acc: 0.7861, F1: 0.7945

Epoch 17/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.294, Acc=0.808]


Train - Loss: 0.2940, Acc: 0.8832, F1: 0.8798
Val   - Loss: 0.4954, Acc: 0.7847, F1: 0.7488

Epoch 18/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.291, Acc=0.885]


Train - Loss: 0.2915, Acc: 0.8762, F1: 0.8721
Val   - Loss: 0.2910, Acc: 0.8732, F1: 0.8685

Epoch 19/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:23<00:00,  3.10s/it, Loss=0.291, Acc=0.885]


Train - Loss: 0.2911, Acc: 0.8740, F1: 0.8708
Val   - Loss: 0.2964, Acc: 0.8687, F1: 0.8620

Epoch 20/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.274, Acc=0.731]


Train - Loss: 0.2737, Acc: 0.8884, F1: 0.8852
Val   - Loss: 0.2723, Acc: 0.8776, F1: 0.8742

Fold 4 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2737
Accuracy: 0.8884
Precision: 0.8874
Recall: 0.8884
F1-Score: 0.8852

Per-class Metrics:
  Immature (0): Precision=0.8932, Recall=0.9555, F1=0.9233
  Mature (1): Precision=0.8735, Recall=0.7292, F1=0.7949

Confusion Matrix:
[[1824   85]
 [ 218  587]]

Fold 4 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2723
Accuracy: 0.8776
Precision: 0.8760
Recall: 0.8776
F1-Score: 0.8742

Per-class Metrics:
  Immature (0): Precision=0.8858, Recall=0.9474, F1=0.9156
  Mature (1): Precision=0.8529, Recall=0.7143, F1=0.7775

Confusion Matrix:
[[450  25]
 [ 58 145]]

Fold 5/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.581, Acc=0.731]


Train - Loss: 0.5807, Acc: 0.6794, F1: 0.6162
Val   - Loss: 5.5072, Acc: 0.7227, F1: 0.6064

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.501, Acc=0.846]


Train - Loss: 0.5008, Acc: 0.7513, F1: 0.7214
Val   - Loss: 7.0264, Acc: 0.7227, F1: 0.6064

Epoch 3/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.457, Acc=0.808]


Train - Loss: 0.4569, Acc: 0.7797, F1: 0.7668
Val   - Loss: 0.4052, Acc: 0.8112, F1: 0.7965

Epoch 4/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.419, Acc=0.923]


Train - Loss: 0.4192, Acc: 0.8161, F1: 0.8134
Val   - Loss: 0.4696, Acc: 0.7611, F1: 0.7695

Epoch 5/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.07s/it, Loss=0.401, Acc=0.885]


Train - Loss: 0.4007, Acc: 0.8268, F1: 0.8234
Val   - Loss: 0.5621, Acc: 0.6534, F1: 0.6700

Epoch 6/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.413, Acc=0.731]


Train - Loss: 0.4133, Acc: 0.8014, F1: 0.7928
Val   - Loss: 1.4502, Acc: 0.6136, F1: 0.6336

Epoch 7/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.07s/it, Loss=0.401, Acc=0.846]


Train - Loss: 0.4009, Acc: 0.8290, F1: 0.8231
Val   - Loss: 0.5641, Acc: 0.6593, F1: 0.6768

Epoch 8/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.387, Acc=0.923]


Train - Loss: 0.3874, Acc: 0.8346, F1: 0.8274
Val   - Loss: 0.3459, Acc: 0.8481, F1: 0.8436

Epoch 9/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.363, Acc=0.885]


Train - Loss: 0.3631, Acc: 0.8489, F1: 0.8434
Val   - Loss: 0.3197, Acc: 0.8732, F1: 0.8637

Epoch 10/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:20<00:00,  3.06s/it, Loss=0.349, Acc=0.923]


Train - Loss: 0.3491, Acc: 0.8486, F1: 0.8433
Val   - Loss: 0.3313, Acc: 0.8481, F1: 0.8472

Epoch 11/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.07s/it, Loss=0.33, Acc=0.885]


Train - Loss: 0.3301, Acc: 0.8552, F1: 0.8511
Val   - Loss: 0.6263, Acc: 0.7478, F1: 0.7607

Epoch 12/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.343, Acc=0.846]


Train - Loss: 0.3431, Acc: 0.8556, F1: 0.8508
Val   - Loss: 0.3055, Acc: 0.8732, F1: 0.8690

Epoch 13/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.07s/it, Loss=0.34, Acc=0.846]


Train - Loss: 0.3399, Acc: 0.8515, F1: 0.8472
Val   - Loss: 0.3578, Acc: 0.8717, F1: 0.8598

Epoch 14/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.327, Acc=0.846]


Train - Loss: 0.3271, Acc: 0.8530, F1: 0.8486
Val   - Loss: 0.3775, Acc: 0.8171, F1: 0.8239

Epoch 15/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.323, Acc=0.808]


Train - Loss: 0.3231, Acc: 0.8556, F1: 0.8514
Val   - Loss: 0.3473, Acc: 0.8525, F1: 0.8543

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.09s/it, Loss=0.331, Acc=0.962]


Train - Loss: 0.3311, Acc: 0.8526, F1: 0.8485
Val   - Loss: 0.3055, Acc: 0.8746, F1: 0.8698

Epoch 17/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.331, Acc=0.808]


Train - Loss: 0.3315, Acc: 0.8604, F1: 0.8559
Val   - Loss: 0.6190, Acc: 0.7448, F1: 0.7513

Epoch 18/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.07s/it, Loss=0.323, Acc=0.885]


Train - Loss: 0.3227, Acc: 0.8644, F1: 0.8610
Val   - Loss: 0.8495, Acc: 0.7021, F1: 0.7171

Epoch 19/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:22<00:00,  3.08s/it, Loss=0.33, Acc=0.808]


Train - Loss: 0.3299, Acc: 0.8570, F1: 0.8528
Val   - Loss: 0.3245, Acc: 0.8687, F1: 0.8672

Epoch 20/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:21<00:00,  3.08s/it, Loss=0.321, Acc=0.846]


Train - Loss: 0.3206, Acc: 0.8622, F1: 0.8575
Val   - Loss: 0.3353, Acc: 0.8466, F1: 0.8283

Fold 5 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3311
Accuracy: 0.8526
Precision: 0.8496
Recall: 0.8526
F1-Score: 0.8485

Per-class Metrics:
  Immature (0): Precision=0.8680, Recall=0.9303, F1=0.8981
  Mature (1): Precision=0.8070, Recall=0.6732, F1=0.7340

Confusion Matrix:
[[1762  132]
 [ 268  552]]

Fold 5 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3055
Accuracy: 0.8746
Precision: 0.8725
Recall: 0.8746
F1-Score: 0.8698

Per-class Metrics:
  Immature (0): Precision=0.8828, Recall=0.9531, F1=0.9166
  Mature (1): Precision=0.8456, Recall=0.6702, F1=0.7478

Confusion Matrix:
[[467  23]
 [ 62 126]]

Cross Validation Results Summary:
Fold 1: Val Acc = 0.8763, Val F1 = 0.8725, Val Loss = 0.2865
Fold 2: Val Acc = 0.8778, Val F1 = 0.8766, Val Loss = 0.3380
Fold 3: Val Acc = 0.8909, Val F1 = 

Training: 100%|████████████████████████████████████████████████| 106/106 [05:27<00:00,  3.09s/it, Loss=0.503, Acc=0.75]


Training Set - Loss: 0.5033, Acc: 0.7450, F1: 0.7172
Test Set - Loss: 0.4562, Acc: 0.7795, F1: 0.7588

Final Model - Epoch 2/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:26<00:00,  3.08s/it, Loss=0.441, Acc=0.781]


Training Set - Loss: 0.4412, Acc: 0.7925, F1: 0.7859
Test Set - Loss: 0.4777, Acc: 0.8066, F1: 0.7744

Final Model - Epoch 3/15


Training: 100%|████████████████████████████████████████████████| 106/106 [05:23<00:00,  3.05s/it, Loss=0.419, Acc=0.75]


Training Set - Loss: 0.4191, Acc: 0.8175, F1: 0.8076
Test Set - Loss: 0.8971, Acc: 0.7995, F1: 0.7959

Final Model - Epoch 4/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:21<00:00,  3.03s/it, Loss=0.402, Acc=0.875]


Training Set - Loss: 0.4023, Acc: 0.8302, F1: 0.8194
Test Set - Loss: 0.3119, Acc: 0.8833, F1: 0.8774

Final Model - Epoch 5/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:21<00:00,  3.03s/it, Loss=0.396, Acc=0.906]


Training Set - Loss: 0.3956, Acc: 0.8296, F1: 0.8207
Test Set - Loss: 2.0785, Acc: 0.6710, F1: 0.6845

Final Model - Epoch 6/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:21<00:00,  3.04s/it, Loss=0.389, Acc=0.844]


Training Set - Loss: 0.3893, Acc: 0.8293, F1: 0.8224
Test Set - Loss: 0.3211, Acc: 0.8585, F1: 0.8474

Final Model - Epoch 7/15


Training: 100%|████████████████████████████████████████████████| 106/106 [05:21<00:00,  3.03s/it, Loss=0.38, Acc=0.812]


Training Set - Loss: 0.3799, Acc: 0.8373, F1: 0.8299
Test Set - Loss: 0.6111, Acc: 0.7642, F1: 0.7035

Final Model - Epoch 8/15


Training: 100%|████████████████████████████████████████████████| 106/106 [05:20<00:00,  3.03s/it, Loss=0.401, Acc=0.75]


Training Set - Loss: 0.4006, Acc: 0.8222, F1: 0.8138
Test Set - Loss: 0.4722, Acc: 0.8007, F1: 0.7651

Final Model - Epoch 9/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:21<00:00,  3.03s/it, Loss=0.346, Acc=0.906]


Training Set - Loss: 0.3455, Acc: 0.8514, F1: 0.8458
Test Set - Loss: 0.2651, Acc: 0.8962, F1: 0.8917

Final Model - Epoch 10/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:20<00:00,  3.02s/it, Loss=0.326, Acc=0.812]


Training Set - Loss: 0.3260, Acc: 0.8526, F1: 0.8473
Test Set - Loss: 0.2660, Acc: 0.8868, F1: 0.8826

Final Model - Epoch 11/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:21<00:00,  3.03s/it, Loss=0.316, Acc=0.906]


Training Set - Loss: 0.3161, Acc: 0.8676, F1: 0.8633
Test Set - Loss: 0.2896, Acc: 0.8703, F1: 0.8610

Final Model - Epoch 12/15


Training: 100%|████████████████████████████████████████████████| 106/106 [05:21<00:00,  3.03s/it, Loss=0.32, Acc=0.906]


Training Set - Loss: 0.3197, Acc: 0.8685, F1: 0.8640
Test Set - Loss: 0.3677, Acc: 0.8432, F1: 0.8243

Final Model - Epoch 13/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:21<00:00,  3.03s/it, Loss=0.295, Acc=0.938]


Training Set - Loss: 0.2954, Acc: 0.8779, F1: 0.8742
Test Set - Loss: 0.4477, Acc: 0.8137, F1: 0.7827

Final Model - Epoch 14/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:21<00:00,  3.03s/it, Loss=0.295, Acc=0.938]


Training Set - Loss: 0.2948, Acc: 0.8765, F1: 0.8733
Test Set - Loss: 0.2244, Acc: 0.9092, F1: 0.9067

Final Model - Epoch 15/15


Training: 100%|███████████████████████████████████████████████| 106/106 [05:21<00:00,  3.03s/it, Loss=0.301, Acc=0.781]


Training Set - Loss: 0.3008, Acc: 0.8753, F1: 0.8716
Test Set - Loss: 0.2304, Acc: 0.9057, F1: 0.9020

Final Training Set Detailed Metrics:

Final Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2948
Accuracy: 0.8765
Precision: 0.8746
Recall: 0.8765
F1-Score: 0.8733

Per-class Metrics:
  Immature (0): Precision=0.8870, Recall=0.9446, F1=0.9149
  Mature (1): Precision=0.8453, Recall=0.7153, F1=0.7749

Confusion Matrix:
[[2252  132]
 [ 287  721]]

Test Set Detailed Metrics:

Test Set Detailed Metrics:
--------------------------------------------------
Loss: 0.2244
Accuracy: 0.9092
Precision: 0.9096
Recall: 0.9092
F1-Score: 0.9067

Per-class Metrics:
  Immature (0): Precision=0.9074, Recall=0.9698, F1=0.9376
  Mature (1): Precision=0.9147, Recall=0.7659, F1=0.8337

Confusion Matrix:
[[578  18]
 [ 59 193]]

✓ Results saved to model_training_results.xlsx

Summary of Results:
5-fold cross validation average validation accuracy: 0.8794
Final training 