In [2]:
import os
import sys
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset, SubsetRandomSampler
from torchvision import transforms
from torchvision.models import vgg16, VGG16_Weights
from PIL import Image
import numpy as np
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
from tqdm import tqdm
import warnings
import pandas as pd
import pickle
warnings.filterwarnings('ignore')

def check_gpu_available():
    if not torch.cuda.is_available():
        print("Error: No available GPU device detected.")
        print("Please ensure:")
        print("1. CUDA and cuDNN are installed")
        print("2. PyTorch version with GPU support is installed")
        print("3. Graphics card driver is up to date")
        print("\nProgram requires GPU for training, exiting now...")
        sys.exit(1)
    
    print(f"✓ GPU available: {torch.cuda.get_device_name(0)}")
    print(f"  Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
    print(f"  CUDA version: {torch.version.cuda}")
    return True

check_gpu_available()

def set_seed(seed=42):
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

class CustomDataset(Dataset):
    def __init__(self, image_paths, labels, transform=None):
        self.image_paths = image_paths
        self.labels = labels
        self.transform = transform
        
    def __len__(self):
        return len(self.image_paths)
    
    def __getitem__(self, idx):
        image = Image.open(self.image_paths[idx]).convert('RGB')
        label = self.labels[idx]
        
        if self.transform:
            image = self.transform(image)
            
        return image, label

def load_data(immature_dir, mature_dir):
    immature_paths = []
    mature_paths = []
    
    for img_name in os.listdir(immature_dir):
        if img_name.lower().endswith(('.jpg', '.jpeg', '.png')):
            immature_paths.append(os.path.join(immature_dir, img_name))
    
    for img_name in os.listdir(mature_dir):
        if img_name.lower().endswith(('.jpg', '.jpeg', '.png')):
            mature_paths.append(os.path.join(mature_dir, img_name))
    
    all_paths = immature_paths + mature_paths
    all_labels = [0] * len(immature_paths) + [1] * len(mature_paths)
    
    print(f"Immature images: {len(immature_paths)}")
    print(f"Mature images: {len(mature_paths)}")
    print(f"Total images: {len(all_paths)}")
    
    return all_paths, all_labels

def get_transforms():
    train_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.RandomRotation(10),
        transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                           std=[0.229, 0.224, 0.225])
    ])
    
    val_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                           std=[0.229, 0.224, 0.225])
    ])
    
    return train_transform, val_transform

def create_vgg16_model(num_classes=2):
    model = vgg16(weights=VGG16_Weights.IMAGENET1K_V1)
    
    num_features = model.classifier[6].in_features
    model.classifier[6] = nn.Sequential(
        nn.Dropout(0.5),
        nn.Linear(num_features, 256),
        nn.ReLU(),
        nn.Dropout(0.3),
        nn.Linear(256, num_classes)
    )
    
    return model

def calculate_metrics(all_labels, all_predictions):
    accuracy = np.mean(np.array(all_labels) == np.array(all_predictions))
    
    precision = precision_score(all_labels, all_predictions, average='weighted')
    recall = recall_score(all_labels, all_predictions, average='weighted')
    f1 = f1_score(all_labels, all_predictions, average='weighted')
    
    precision_per_class = precision_score(all_labels, all_predictions, average=None)
    recall_per_class = recall_score(all_labels, all_predictions, average=None)
    f1_per_class = f1_score(all_labels, all_predictions, average=None)
    
    cm = confusion_matrix(all_labels, all_predictions)
    
    report = classification_report(all_labels, all_predictions, 
                                  target_names=['immature', 'mature'], 
                                  output_dict=True)
    
    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'precision_per_class': precision_per_class,
        'recall_per_class': recall_per_class,
        'f1_per_class': f1_per_class,
        'confusion_matrix': cm,
        'classification_report': report
    }

def train_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    all_predictions = []
    all_labels = []
    
    progress_bar = tqdm(dataloader, desc='Training')
    for images, labels in progress_bar:
        images, labels = images.to(device), labels.to(device)
        
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        
        all_predictions.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
        
        batch_acc = (predicted == labels).sum().item() / labels.size(0)
        progress_bar.set_postfix({'Loss': running_loss/len(dataloader), 'Acc': batch_acc})
    
    epoch_loss = running_loss / len(dataloader)
    
    metrics = calculate_metrics(all_labels, all_predictions)
    metrics['loss'] = epoch_loss
    
    return epoch_loss, metrics

def evaluate_model(model, dataloader, criterion, device, dataset_name="Dataset"):
    model.eval()
    running_loss = 0.0
    all_predictions = []
    all_labels = []
    
    with torch.no_grad():
        for images, labels in dataloader:
            images, labels = images.to(device), labels.to(device)
            
            outputs = model(images)
            loss = criterion(outputs, labels)
            
            running_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            
            all_predictions.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    
    epoch_loss = running_loss / len(dataloader)
    
    metrics = calculate_metrics(all_labels, all_predictions)
    metrics['loss'] = epoch_loss
    
    return epoch_loss, metrics

def print_detailed_metrics(metrics, dataset_name="Dataset"):
    print(f"\n{dataset_name} Detailed Metrics:")
    print("-" * 50)
    print(f"Loss: {metrics['loss']:.4f}")
    print(f"Accuracy: {metrics['accuracy']:.4f}")
    print(f"Precision: {metrics['precision']:.4f}")
    print(f"Recall: {metrics['recall']:.4f}")
    print(f"F1-Score: {metrics['f1']:.4f}")
    
    print(f"\nPer-class Metrics:")
    print(f"  Immature (0): Precision={metrics['precision_per_class'][0]:.4f}, "
          f"Recall={metrics['recall_per_class'][0]:.4f}, F1={metrics['f1_per_class'][0]:.4f}")
    print(f"  Mature (1): Precision={metrics['precision_per_class'][1]:.4f}, "
          f"Recall={metrics['recall_per_class'][1]:.4f}, F1={metrics['f1_per_class'][1]:.4f}")
    
    print(f"\nConfusion Matrix:")
    print(metrics['confusion_matrix'])

def export_results_to_excel(fold_results, test_results, final_train_results, filename='training_results.xlsx'):
    all_results = []
    
    for fold_result in fold_results:
        fold_data = {
            'Fold': fold_result['fold'],
            'Dataset': 'Validation',
            'Loss': fold_result['val_loss'],
            'Accuracy': fold_result['val_accuracy'],
            'Precision': fold_result['val_precision'],
            'Recall': fold_result['val_recall'],
            'F1_Score': fold_result['val_f1'],
            'Precision_Class0': fold_result['val_precision_per_class'][0],
            'Precision_Class1': fold_result['val_precision_per_class'][1],
            'Recall_Class0': fold_result['val_recall_per_class'][0],
            'Recall_Class1': fold_result['val_recall_per_class'][1],
            'F1_Class0': fold_result['val_f1_per_class'][0],
            'F1_Class1': fold_result['val_f1_per_class'][1],
            'Train_Loss': fold_result['train_loss'],
            'Train_Accuracy': fold_result['train_accuracy'],
            'Train_Precision': fold_result['train_precision'],
            'Train_Recall': fold_result['train_recall'],
            'Train_F1_Score': fold_result['train_f1']
        }
        all_results.append(fold_data)
    
    final_train_data = {
        'Fold': 'Final',
        'Dataset': 'Train',
        'Loss': final_train_results['loss'],
        'Accuracy': final_train_results['accuracy'],
        'Precision': final_train_results['precision'],
        'Recall': final_train_results['recall'],
        'F1_Score': final_train_results['f1'],
        'Precision_Class0': final_train_results['precision_per_class'][0],
        'Precision_Class1': final_train_results['precision_per_class'][1],
        'Recall_Class0': final_train_results['recall_per_class'][0],
        'Recall_Class1': final_train_results['recall_per_class'][1],
        'F1_Class0': final_train_results['f1_per_class'][0],
        'F1_Class1': final_train_results['f1_per_class'][1],
        'Train_Loss': final_train_results['loss'],
        'Train_Accuracy': final_train_results['accuracy'],
        'Train_Precision': final_train_results['precision'],
        'Train_Recall': final_train_results['recall'],
        'Train_F1_Score': final_train_results['f1']
    }
    all_results.append(final_train_data)
    
    test_data = {
        'Fold': 'Final',
        'Dataset': 'Test',
        'Loss': test_results['loss'],
        'Accuracy': test_results['accuracy'],
        'Precision': test_results['precision'],
        'Recall': test_results['recall'],
        'F1_Score': test_results['f1'],
        'Precision_Class0': test_results['precision_per_class'][0],
        'Precision_Class1': test_results['precision_per_class'][1],
        'Recall_Class0': test_results['recall_per_class'][0],
        'Recall_Class1': test_results['recall_per_class'][1],
        'F1_Class0': test_results['f1_per_class'][0],
        'F1_Class1': test_results['f1_per_class'][1],
        'Train_Loss': final_train_results['loss'],
        'Train_Accuracy': final_train_results['accuracy'],
        'Train_Precision': final_train_results['precision'],
        'Train_Recall': final_train_results['recall'],
        'Train_F1_Score': final_train_results['f1']
    }
    all_results.append(test_data)
    
    df = pd.DataFrame(all_results)
    
    validation_df = df[df['Dataset'] == 'Validation']
    if not validation_df.empty:
        avg_row = {
            'Fold': 'Average',
            'Dataset': 'Validation',
            'Loss': validation_df['Loss'].mean(),
            'Accuracy': validation_df['Accuracy'].mean(),
            'Precision': validation_df['Precision'].mean(),
            'Recall': validation_df['Recall'].mean(),
            'F1_Score': validation_df['F1_Score'].mean(),
            'Precision_Class0': validation_df['Precision_Class0'].mean(),
            'Precision_Class1': validation_df['Precision_Class1'].mean(),
            'Recall_Class0': validation_df['Recall_Class0'].mean(),
            'Recall_Class1': validation_df['Recall_Class1'].mean(),
            'F1_Class0': validation_df['F1_Class0'].mean(),
            'F1_Class1': validation_df['F1_Class1'].mean(),
            'Train_Loss': validation_df['Train_Loss'].mean(),
            'Train_Accuracy': validation_df['Train_Accuracy'].mean(),
            'Train_Precision': validation_df['Train_Precision'].mean(),
            'Train_Recall': validation_df['Train_Recall'].mean(),
            'Train_F1_Score': validation_df['Train_F1_Score'].mean()
        }
        
        df = pd.concat([df, pd.DataFrame([avg_row])], ignore_index=True)
    
    df.to_excel(filename, index=False)
    print(f"\n✓ Results saved to {filename}")
    
    print("\n" + "="*80)
    print("Summary of Results:")
    print("="*80)
    if not validation_df.empty:
        print(f"5-fold cross validation average validation accuracy: {validation_df['Accuracy'].mean():.4f}")
    print(f"Final training set accuracy: {final_train_results['accuracy']:.4f}")
    print(f"Test set accuracy: {test_results['accuracy']:.4f}")
    print(f"Test set F1 score: {test_results['f1']:.4f}")
    
    return df

def main():
    immature_dir = r"E:\TSG\jupyterlab\machine learning image\augmented_dataset\immature"
    mature_dir = r"E:\TSG\jupyterlab\machine learning image\augmented_dataset\mature"
    
    print("Loading data...")
    all_paths, all_labels = load_data(immature_dir, mature_dir)
    
    print("\nSplitting data into train and test sets...")
    train_paths, test_paths, train_labels, test_labels = train_test_split(
        all_paths, all_labels, test_size=0.2, random_state=42, stratify=all_labels
    )
    
    print(f"Train set size: {len(train_paths)}")
    print(f"Test set size: {len(test_paths)}")
    
    train_transform, val_transform = get_transforms()
    
    train_dataset = CustomDataset(train_paths, train_labels, train_transform)
    test_dataset = CustomDataset(test_paths, test_labels, val_transform)
    
    device = torch.device("cuda")
    print(f"\nUsing device: {device}")
    
    print("\nStarting 5-fold cross validation...")
    kfold = KFold(n_splits=5, shuffle=True, random_state=42)
    fold_results = []
    
    for fold, (train_idx, val_idx) in enumerate(kfold.split(train_dataset)):
        print(f"\n{'='*60}")
        print(f"Fold {fold+1}/5")
        print(f"{'='*60}")
        
        train_subsampler = SubsetRandomSampler(train_idx)
        val_subsampler = SubsetRandomSampler(val_idx)
        
        train_loader = DataLoader(train_dataset, batch_size=32, sampler=train_subsampler)
        val_loader = DataLoader(train_dataset, batch_size=32, sampler=val_subsampler)
        
        model = create_vgg16_model(num_classes=2)
        model = model.to(device)
        
        criterion = nn.CrossEntropyLoss()
        optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-4)
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', patience=3)
        
        num_epochs = 20
        best_val_acc = 0
        best_model_state = None
        best_train_metrics = None
        best_val_metrics = None
        best_train_loss = None
        
        for epoch in range(num_epochs):
            print(f"\nEpoch {epoch+1}/{num_epochs}")
            
            train_loss, train_metrics = train_epoch(model, train_loader, criterion, optimizer, device)
            
            val_loss, val_metrics = evaluate_model(model, val_loader, criterion, device, "Validation")
            
            scheduler.step(val_loss)
            
            print(f"Train - Loss: {train_loss:.4f}, Acc: {train_metrics['accuracy']:.4f}, "
                  f"F1: {train_metrics['f1']:.4f}")
            print(f"Val   - Loss: {val_loss:.4f}, Acc: {val_metrics['accuracy']:.4f}, "
                  f"F1: {val_metrics['f1']:.4f}")
            
            if val_metrics['accuracy'] > best_val_acc:
                best_val_acc = val_metrics['accuracy']
                best_model_state = model.state_dict().copy()
                best_train_metrics = train_metrics
                best_val_metrics = val_metrics
                best_train_loss = train_loss
        
        print_detailed_metrics(best_train_metrics, f"Fold {fold+1} - Best Training Set")
        print_detailed_metrics(best_val_metrics, f"Fold {fold+1} - Best Validation Set")
        
        fold_results.append({
            'fold': fold + 1,
            'best_val_acc': best_val_acc,
            'val_loss': best_val_metrics['loss'],
            'val_accuracy': best_val_metrics['accuracy'],
            'val_precision': best_val_metrics['precision'],
            'val_recall': best_val_metrics['recall'],
            'val_f1': best_val_metrics['f1'],
            'val_precision_per_class': best_val_metrics['precision_per_class'],
            'val_recall_per_class': best_val_metrics['recall_per_class'],
            'val_f1_per_class': best_val_metrics['f1_per_class'],
            'train_loss': best_train_loss,
            'train_accuracy': best_train_metrics['accuracy'],
            'train_precision': best_train_metrics['precision'],
            'train_recall': best_train_metrics['recall'],
            'train_f1': best_train_metrics['f1'],
            'model_state': best_model_state
        })
    
    print("\n" + "="*60)
    print("Cross Validation Results Summary:")
    print("="*60)
    for result in fold_results:
        print(f"Fold {result['fold']}: "
              f"Val Acc = {result['best_val_acc']:.4f}, "
              f"Val F1 = {result['val_f1']:.4f}, "
              f"Val Loss = {result['val_loss']:.4f}")
    
    avg_val_acc = np.mean([r['best_val_acc'] for r in fold_results])
    avg_val_f1 = np.mean([r['val_f1'] for r in fold_results])
    avg_val_loss = np.mean([r['val_loss'] for r in fold_results])
    print(f"\nAverage Validation Accuracy: {avg_val_acc:.4f}")
    print(f"Average Validation F1 Score: {avg_val_f1:.4f}")
    print(f"Average Validation Loss: {avg_val_loss:.4f}")
    
    print("\n" + "="*60)
    print("Evaluating Final Model on Test Set...")
    print("="*60)
    
    print("\nTraining final model on entire training set...")
    final_train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)
    
    final_model = create_vgg16_model(num_classes=2)
    final_model = final_model.to(device)
    
    final_criterion = nn.CrossEntropyLoss()
    final_optimizer = optim.Adam(final_model.parameters(), lr=0.001)
    final_scheduler = optim.lr_scheduler.ReduceLROnPlateau(final_optimizer, mode='min', patience=3)
    
    num_final_epochs = 15
    best_test_acc = 0
    best_test_metrics = None
    best_final_train_metrics = None
    best_final_train_loss = None
    
    for epoch in range(num_final_epochs):
        print(f"\nFinal Model - Epoch {epoch+1}/{num_final_epochs}")
        
        train_loss, train_metrics = train_epoch(final_model, final_train_loader, final_criterion, final_optimizer, device)
        
        test_loss, test_metrics = evaluate_model(final_model, test_loader, final_criterion, device, "Test")
        
        final_scheduler.step(test_loss)
        
        print(f"Training Set - Loss: {train_loss:.4f}, Acc: {train_metrics['accuracy']:.4f}, "
              f"F1: {train_metrics['f1']:.4f}")
        print(f"Test Set - Loss: {test_loss:.4f}, Acc: {test_metrics['accuracy']:.4f}, "
              f"F1: {test_metrics['f1']:.4f}")
        
        if test_metrics['accuracy'] > best_test_acc:
            best_test_acc = test_metrics['accuracy']
            best_test_metrics = test_metrics
            best_final_train_metrics = train_metrics
            best_final_train_loss = train_loss
            torch.save(final_model.state_dict(), 'best_vgg16_model.pth')
    
    print("\n" + "="*60)
    print("Final Training Set Detailed Metrics:")
    print("="*60)
    print_detailed_metrics(best_final_train_metrics, "Final Training Set")
    
    print("\n" + "="*60)
    print("Test Set Detailed Metrics:")
    print("="*60)
    print_detailed_metrics(best_test_metrics, "Test Set")
    
    export_results_to_excel(fold_results, best_test_metrics, best_final_train_metrics, 'vgg16_model_training_results.xlsx')
    
    def predict_single_image(image_path, model_path='best_vgg16_model.pth'):
        model = create_vgg16_model(num_classes=2)
        model.load_state_dict(torch.load(model_path, map_location=device))
        model = model.to(device)
        model.eval()
        
        image = Image.open(image_path).convert('RGB')
        transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                               std=[0.229, 0.224, 0.225])
        ])
        
        image_tensor = transform(image).unsqueeze(0).to(device)
        
        with torch.no_grad():
            outputs = model(image_tensor)
            probabilities = torch.softmax(outputs, dim=1)
            _, predicted = torch.max(outputs, 1)
            
            class_names = ['immature', 'mature']
            result = class_names[predicted.item()]
            confidence = probabilities[0][predicted.item()].item()
            
        return result, confidence
    
    print("\n" + "="*60)
    print("Model is ready for prediction!")
    print("Use predict_single_image('path/to/image.jpg') to classify new images.")
    print("="*60)
    
    with open('vgg16_classifier_info.pkl', 'wb') as f:
        pickle.dump({
            'train_paths': train_paths,
            'test_paths': test_paths,
            'train_labels': train_labels,
            'test_labels': test_labels,
            'class_names': ['immature', 'mature'],
            'normalization_mean': [0.485, 0.456, 0.406],
            'normalization_std': [0.229, 0.224, 0.225],
            'fold_results': fold_results,
            'test_results': best_test_metrics,
            'final_train_results': best_final_train_metrics
        }, f)
    
    return final_model, best_test_metrics, best_final_train_metrics

if __name__ == "__main__":
    model, test_results, train_results = main()

✓ GPU available: NVIDIA GeForce RTX 5070 Ti
  Memory: 17.09 GB
  CUDA version: 11.8
Loading data...
Immature images: 2980
Mature images: 1260
Total images: 4240

Splitting data into train and test sets...
Train set size: 3392
Test set size: 848

Using device: cuda

Starting 5-fold cross validation...

Fold 1/5

Epoch 1/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:46<00:00,  3.37s/it, Loss=0.666, Acc=0.8]


Train - Loss: 0.6658, Acc: 0.6992, F1: 0.6039
Val   - Loss: 0.5984, Acc: 0.6819, F1: 0.5529

Epoch 2/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:39<00:00,  3.29s/it, Loss=0.582, Acc=0.48]


Train - Loss: 0.5819, Acc: 0.6963, F1: 0.6164
Val   - Loss: 0.6907, Acc: 0.4536, F1: 0.4697

Epoch 3/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:37<00:00,  3.27s/it, Loss=0.604, Acc=0.68]


Train - Loss: 0.6042, Acc: 0.7044, F1: 0.5899
Val   - Loss: 0.6091, Acc: 0.6819, F1: 0.5529

Epoch 4/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:32<00:00,  3.21s/it, Loss=0.672, Acc=0.64]


Train - Loss: 0.6721, Acc: 0.6952, F1: 0.6048
Val   - Loss: 0.6409, Acc: 0.6819, F1: 0.5529

Epoch 5/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:36<00:00,  3.26s/it, Loss=0.633, Acc=0.64]


Train - Loss: 0.6325, Acc: 0.7059, F1: 0.5951
Val   - Loss: 0.6078, Acc: 0.6819, F1: 0.5529

Epoch 6/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:33<00:00,  3.22s/it, Loss=0.576, Acc=0.88]


Train - Loss: 0.5765, Acc: 0.7081, F1: 0.5871
Val   - Loss: 0.5872, Acc: 0.6819, F1: 0.5529

Epoch 7/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.19s/it, Loss=0.571, Acc=0.68]


Train - Loss: 0.5713, Acc: 0.7081, F1: 0.5871
Val   - Loss: 0.5781, Acc: 0.6819, F1: 0.5529

Epoch 8/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.19s/it, Loss=0.569, Acc=0.8]


Train - Loss: 0.5687, Acc: 0.7081, F1: 0.5871
Val   - Loss: 0.5633, Acc: 0.6819, F1: 0.5529

Epoch 9/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:33<00:00,  3.21s/it, Loss=0.573, Acc=0.68]


Train - Loss: 0.5734, Acc: 0.7081, F1: 0.5871
Val   - Loss: 0.5908, Acc: 0.6819, F1: 0.5529

Epoch 10/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:32<00:00,  3.21s/it, Loss=0.561, Acc=0.72]


Train - Loss: 0.5610, Acc: 0.7081, F1: 0.5871
Val   - Loss: 0.5614, Acc: 0.6819, F1: 0.5529

Epoch 11/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.19s/it, Loss=0.557, Acc=0.68]


Train - Loss: 0.5569, Acc: 0.7081, F1: 0.5871
Val   - Loss: 0.5593, Acc: 0.6819, F1: 0.5529

Epoch 12/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:36<00:00,  3.25s/it, Loss=0.555, Acc=0.56]


Train - Loss: 0.5554, Acc: 0.7081, F1: 0.5871
Val   - Loss: 0.5526, Acc: 0.6819, F1: 0.5529

Epoch 13/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:36<00:00,  3.26s/it, Loss=0.546, Acc=0.48]


Train - Loss: 0.5460, Acc: 0.7081, F1: 0.5871
Val   - Loss: 0.5553, Acc: 0.6819, F1: 0.5529

Epoch 14/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:32<00:00,  3.21s/it, Loss=0.545, Acc=0.6]


Train - Loss: 0.5453, Acc: 0.7081, F1: 0.5871
Val   - Loss: 0.5582, Acc: 0.6819, F1: 0.5529

Epoch 15/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:32<00:00,  3.20s/it, Loss=0.546, Acc=0.72]


Train - Loss: 0.5456, Acc: 0.7081, F1: 0.5871
Val   - Loss: 0.5426, Acc: 0.6819, F1: 0.5529

Epoch 16/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:33<00:00,  3.22s/it, Loss=0.537, Acc=0.68]


Train - Loss: 0.5372, Acc: 0.7081, F1: 0.5871
Val   - Loss: 0.5578, Acc: 0.6819, F1: 0.5529

Epoch 17/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:38<00:00,  3.28s/it, Loss=0.544, Acc=0.6]


Train - Loss: 0.5442, Acc: 0.7081, F1: 0.5871
Val   - Loss: 0.5603, Acc: 0.6819, F1: 0.5529

Epoch 18/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:33<00:00,  3.21s/it, Loss=0.543, Acc=0.84]


Train - Loss: 0.5430, Acc: 0.7081, F1: 0.5871
Val   - Loss: 0.5452, Acc: 0.6819, F1: 0.5529

Epoch 19/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:33<00:00,  3.22s/it, Loss=0.547, Acc=0.76]


Train - Loss: 0.5470, Acc: 0.7081, F1: 0.5871
Val   - Loss: 0.5488, Acc: 0.6819, F1: 0.5529

Epoch 20/20


Training: 100%|████████████████████████████████████████████████████| 85/85 [04:35<00:00,  3.24s/it, Loss=0.54, Acc=0.6]


Train - Loss: 0.5396, Acc: 0.7081, F1: 0.5871
Val   - Loss: 0.5501, Acc: 0.6819, F1: 0.5529

Fold 1 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.6658
Accuracy: 0.6992
Precision: 0.6121
Recall: 0.6992
F1-Score: 0.6039

Per-class Metrics:
  Immature (0): Precision=0.7110, Recall=0.9693, F1=0.8203
  Mature (1): Precision=0.3723, Recall=0.0442, F1=0.0790

Confusion Matrix:
[[1862   59]
 [ 757   35]]

Fold 1 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.5984
Accuracy: 0.6819
Precision: 0.4650
Recall: 0.6819
F1-Score: 0.5529

Per-class Metrics:
  Immature (0): Precision=0.6819, Recall=1.0000, F1=0.8109
  Mature (1): Precision=0.0000, Recall=0.0000, F1=0.0000

Confusion Matrix:
[[463   0]
 [216   0]]

Fold 2/5

Epoch 1/20


Training: 100%|████████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.20s/it, Loss=0.8, Acc=0.72]


Train - Loss: 0.7995, Acc: 0.6882, F1: 0.6054
Val   - Loss: 0.6105, Acc: 0.6922, F1: 0.5663

Epoch 2/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.19s/it, Loss=0.634, Acc=0.68]


Train - Loss: 0.6336, Acc: 0.7059, F1: 0.5845
Val   - Loss: 0.6120, Acc: 0.6922, F1: 0.5663

Epoch 3/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.19s/it, Loss=0.674, Acc=0.8]


Train - Loss: 0.6744, Acc: 0.7003, F1: 0.5864
Val   - Loss: 0.6448, Acc: 0.6922, F1: 0.5663

Epoch 4/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.18s/it, Loss=0.631, Acc=0.6]


Train - Loss: 0.6309, Acc: 0.7055, F1: 0.5857
Val   - Loss: 0.6152, Acc: 0.6922, F1: 0.5663

Epoch 5/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.19s/it, Loss=0.62, Acc=0.76]


Train - Loss: 0.6203, Acc: 0.7055, F1: 0.5837
Val   - Loss: 0.6003, Acc: 0.6922, F1: 0.5663

Epoch 6/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.19s/it, Loss=0.723, Acc=0.8]


Train - Loss: 0.7234, Acc: 0.6978, F1: 0.5882
Val   - Loss: 0.6457, Acc: 0.6922, F1: 0.5663

Epoch 7/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.20s/it, Loss=0.633, Acc=0.68]


Train - Loss: 0.6329, Acc: 0.7055, F1: 0.5837
Val   - Loss: 0.6334, Acc: 0.6922, F1: 0.5663

Epoch 8/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.19s/it, Loss=0.621, Acc=0.68]


Train - Loss: 0.6208, Acc: 0.7055, F1: 0.5837
Val   - Loss: 0.6210, Acc: 0.6922, F1: 0.5663

Epoch 9/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.18s/it, Loss=0.623, Acc=0.76]


Train - Loss: 0.6227, Acc: 0.7055, F1: 0.5837
Val   - Loss: 0.6198, Acc: 0.6922, F1: 0.5663

Epoch 10/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.18s/it, Loss=0.611, Acc=0.72]


Train - Loss: 0.6114, Acc: 0.7055, F1: 0.5837
Val   - Loss: 0.6157, Acc: 0.6922, F1: 0.5663

Epoch 11/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.18s/it, Loss=0.61, Acc=0.56]


Train - Loss: 0.6101, Acc: 0.7055, F1: 0.5837
Val   - Loss: 0.6250, Acc: 0.6922, F1: 0.5663

Epoch 12/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.19s/it, Loss=0.608, Acc=0.72]


Train - Loss: 0.6081, Acc: 0.7055, F1: 0.5837
Val   - Loss: 0.6129, Acc: 0.6922, F1: 0.5663

Epoch 13/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.19s/it, Loss=0.608, Acc=0.68]


Train - Loss: 0.6078, Acc: 0.7055, F1: 0.5837
Val   - Loss: 0.6290, Acc: 0.6922, F1: 0.5663

Epoch 14/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.19s/it, Loss=0.609, Acc=0.56]


Train - Loss: 0.6086, Acc: 0.7055, F1: 0.5837
Val   - Loss: 0.6126, Acc: 0.6922, F1: 0.5663

Epoch 15/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.19s/it, Loss=0.607, Acc=0.64]


Train - Loss: 0.6074, Acc: 0.7055, F1: 0.5837
Val   - Loss: 0.6208, Acc: 0.6922, F1: 0.5663

Epoch 16/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.19s/it, Loss=0.608, Acc=0.68]


Train - Loss: 0.6076, Acc: 0.7055, F1: 0.5837
Val   - Loss: 0.6208, Acc: 0.6922, F1: 0.5663

Epoch 17/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.18s/it, Loss=0.608, Acc=0.72]


Train - Loss: 0.6078, Acc: 0.7055, F1: 0.5837
Val   - Loss: 0.6167, Acc: 0.6922, F1: 0.5663

Epoch 18/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.20s/it, Loss=0.608, Acc=0.68]


Train - Loss: 0.6077, Acc: 0.7055, F1: 0.5837
Val   - Loss: 0.6249, Acc: 0.6922, F1: 0.5663

Epoch 19/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.20s/it, Loss=0.606, Acc=0.88]


Train - Loss: 0.6060, Acc: 0.7055, F1: 0.5837
Val   - Loss: 0.6085, Acc: 0.6922, F1: 0.5663

Epoch 20/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.19s/it, Loss=0.606, Acc=0.64]


Train - Loss: 0.6058, Acc: 0.7055, F1: 0.5837
Val   - Loss: 0.6126, Acc: 0.6922, F1: 0.5663

Fold 2 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.7995
Accuracy: 0.6882
Precision: 0.6026
Recall: 0.6882
F1-Score: 0.6054

Per-class Metrics:
  Immature (0): Precision=0.7088, Recall=0.9472, F1=0.8108
  Mature (1): Precision=0.3484, Recall=0.0676, F1=0.1132

Confusion Matrix:
[[1813  101]
 [ 745   54]]

Fold 2 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.6105
Accuracy: 0.6922
Precision: 0.4791
Recall: 0.6922
F1-Score: 0.5663

Per-class Metrics:
  Immature (0): Precision=0.6922, Recall=1.0000, F1=0.8181
  Mature (1): Precision=0.0000, Recall=0.0000, F1=0.0000

Confusion Matrix:
[[470   0]
 [209   0]]

Fold 3/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.19s/it, Loss=0.679, Acc=0.885]


Train - Loss: 0.6792, Acc: 0.6813, F1: 0.5812
Val   - Loss: 0.6359, Acc: 0.7168, F1: 0.5986

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.19s/it, Loss=0.645, Acc=0.615]


Train - Loss: 0.6451, Acc: 0.6993, F1: 0.5763
Val   - Loss: 0.6086, Acc: 0.7168, F1: 0.5986

Epoch 3/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.19s/it, Loss=0.654, Acc=0.731]


Train - Loss: 0.6538, Acc: 0.6990, F1: 0.5754
Val   - Loss: 0.6249, Acc: 0.7168, F1: 0.5986

Epoch 4/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.20s/it, Loss=0.621, Acc=0.654]


Train - Loss: 0.6211, Acc: 0.6960, F1: 0.5780
Val   - Loss: 0.6259, Acc: 0.7168, F1: 0.5986

Epoch 5/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.20s/it, Loss=0.645, Acc=0.692]


Train - Loss: 0.6448, Acc: 0.6997, F1: 0.5765
Val   - Loss: 0.6110, Acc: 0.7168, F1: 0.5986

Epoch 6/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.19s/it, Loss=0.64, Acc=0.692]


Train - Loss: 0.6404, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.6228, Acc: 0.7168, F1: 0.5986

Epoch 7/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.20s/it, Loss=0.629, Acc=0.654]


Train - Loss: 0.6291, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.6159, Acc: 0.7168, F1: 0.5986

Epoch 8/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.18s/it, Loss=0.628, Acc=0.615]


Train - Loss: 0.6281, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.6174, Acc: 0.7168, F1: 0.5986

Epoch 9/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.17s/it, Loss=0.627, Acc=0.731]


Train - Loss: 0.6270, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.6162, Acc: 0.7168, F1: 0.5986

Epoch 10/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.17s/it, Loss=0.626, Acc=0.808]


Train - Loss: 0.6259, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.6121, Acc: 0.7168, F1: 0.5986

Epoch 11/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.18s/it, Loss=0.626, Acc=0.692]


Train - Loss: 0.6256, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.6149, Acc: 0.7168, F1: 0.5986

Epoch 12/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.18s/it, Loss=0.625, Acc=0.731]


Train - Loss: 0.6254, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.6178, Acc: 0.7168, F1: 0.5986

Epoch 13/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.17s/it, Loss=0.625, Acc=0.846]


Train - Loss: 0.6252, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.6177, Acc: 0.7168, F1: 0.5986

Epoch 14/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.17s/it, Loss=0.625, Acc=0.692]


Train - Loss: 0.6253, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.6146, Acc: 0.7168, F1: 0.5986

Epoch 15/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.17s/it, Loss=0.625, Acc=0.731]


Train - Loss: 0.6252, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.6206, Acc: 0.7168, F1: 0.5986

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.17s/it, Loss=0.625, Acc=0.654]


Train - Loss: 0.6253, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.6146, Acc: 0.7168, F1: 0.5986

Epoch 17/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.17s/it, Loss=0.625, Acc=0.692]


Train - Loss: 0.6252, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.6146, Acc: 0.7168, F1: 0.5986

Epoch 18/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.17s/it, Loss=0.625, Acc=0.615]


Train - Loss: 0.6253, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.6145, Acc: 0.7168, F1: 0.5986

Epoch 19/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.17s/it, Loss=0.625, Acc=0.692]


Train - Loss: 0.6252, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.6176, Acc: 0.7168, F1: 0.5986

Epoch 20/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.18s/it, Loss=0.625, Acc=0.654]


Train - Loss: 0.6253, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.6145, Acc: 0.7168, F1: 0.5986

Fold 3 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.6792
Accuracy: 0.6813
Precision: 0.5621
Recall: 0.6813
F1-Score: 0.5812

Per-class Metrics:
  Immature (0): Precision=0.6974, Recall=0.9615, F1=0.8084
  Mature (1): Precision=0.2474, Recall=0.0294, F1=0.0526

Confusion Matrix:
[[1825   73]
 [ 792   24]]

Fold 3 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.6359
Accuracy: 0.7168
Precision: 0.5138
Recall: 0.7168
F1-Score: 0.5986

Per-class Metrics:
  Immature (0): Precision=0.7168, Recall=1.0000, F1=0.8351
  Mature (1): Precision=0.0000, Recall=0.0000, F1=0.0000

Confusion Matrix:
[[486   0]
 [192   0]]

Fold 4/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:36<00:00,  3.25s/it, Loss=0.748, Acc=0.808]


Train - Loss: 0.7475, Acc: 0.6957, F1: 0.5817
Val   - Loss: 0.6399, Acc: 0.7006, F1: 0.5772

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:38<00:00,  3.28s/it, Loss=0.605, Acc=0.654]


Train - Loss: 0.6050, Acc: 0.7034, F1: 0.5809
Val   - Loss: 0.5892, Acc: 0.7006, F1: 0.5772

Epoch 3/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.608, Acc=0.769]


Train - Loss: 0.6083, Acc: 0.7034, F1: 0.5969
Val   - Loss: 0.6614, Acc: 0.7006, F1: 0.5772

Epoch 4/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.18s/it, Loss=0.645, Acc=0.769]


Train - Loss: 0.6446, Acc: 0.7034, F1: 0.5816
Val   - Loss: 0.6382, Acc: 0.7006, F1: 0.5772

Epoch 5/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.652, Acc=0.577]


Train - Loss: 0.6522, Acc: 0.6979, F1: 0.5841
Val   - Loss: 0.5903, Acc: 0.7006, F1: 0.5772

Epoch 6/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:32<00:00,  3.20s/it, Loss=0.618, Acc=0.692]


Train - Loss: 0.6181, Acc: 0.7030, F1: 0.5807
Val   - Loss: 0.6122, Acc: 0.7006, F1: 0.5772

Epoch 7/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:37<00:00,  3.26s/it, Loss=0.616, Acc=0.615]


Train - Loss: 0.6161, Acc: 0.7034, F1: 0.5809
Val   - Loss: 0.6215, Acc: 0.7006, F1: 0.5772

Epoch 8/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.19s/it, Loss=0.612, Acc=0.846]


Train - Loss: 0.6117, Acc: 0.7034, F1: 0.5809
Val   - Loss: 0.6121, Acc: 0.7006, F1: 0.5772

Epoch 9/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.616, Acc=0.769]


Train - Loss: 0.6157, Acc: 0.7034, F1: 0.5809
Val   - Loss: 0.6077, Acc: 0.7006, F1: 0.5772

Epoch 10/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.614, Acc=0.808]


Train - Loss: 0.6144, Acc: 0.7034, F1: 0.5809
Val   - Loss: 0.6123, Acc: 0.7006, F1: 0.5772

Epoch 11/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.19s/it, Loss=0.614, Acc=0.731]


Train - Loss: 0.6143, Acc: 0.7034, F1: 0.5809
Val   - Loss: 0.6077, Acc: 0.7006, F1: 0.5772

Epoch 12/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.17s/it, Loss=0.612, Acc=0.538]


Train - Loss: 0.6122, Acc: 0.7034, F1: 0.5809
Val   - Loss: 0.6075, Acc: 0.7006, F1: 0.5772

Epoch 13/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.17s/it, Loss=0.615, Acc=0.808]


Train - Loss: 0.6151, Acc: 0.7034, F1: 0.5809
Val   - Loss: 0.6076, Acc: 0.7006, F1: 0.5772

Epoch 14/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.614, Acc=0.731]


Train - Loss: 0.6138, Acc: 0.7034, F1: 0.5809
Val   - Loss: 0.6029, Acc: 0.7006, F1: 0.5772

Epoch 15/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.19s/it, Loss=0.612, Acc=0.654]


Train - Loss: 0.6116, Acc: 0.7034, F1: 0.5809
Val   - Loss: 0.6029, Acc: 0.7006, F1: 0.5772

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.18s/it, Loss=0.614, Acc=0.692]


Train - Loss: 0.6137, Acc: 0.7034, F1: 0.5809
Val   - Loss: 0.6122, Acc: 0.7006, F1: 0.5772

Epoch 17/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.612, Acc=0.692]


Train - Loss: 0.6120, Acc: 0.7034, F1: 0.5809
Val   - Loss: 0.6169, Acc: 0.7006, F1: 0.5772

Epoch 18/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.18s/it, Loss=0.612, Acc=0.692]


Train - Loss: 0.6122, Acc: 0.7034, F1: 0.5809
Val   - Loss: 0.6075, Acc: 0.7006, F1: 0.5772

Epoch 19/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.15s/it, Loss=0.613, Acc=0.692]


Train - Loss: 0.6133, Acc: 0.7034, F1: 0.5809
Val   - Loss: 0.6122, Acc: 0.7006, F1: 0.5772

Epoch 20/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.614, Acc=0.731]


Train - Loss: 0.6137, Acc: 0.7034, F1: 0.5809
Val   - Loss: 0.6122, Acc: 0.7006, F1: 0.5772

Fold 4 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.7475
Accuracy: 0.6957
Precision: 0.5532
Recall: 0.6957
F1-Score: 0.5817

Per-class Metrics:
  Immature (0): Precision=0.7021, Recall=0.9853, F1=0.8200
  Mature (1): Precision=0.2000, Recall=0.0087, F1=0.0167

Confusion Matrix:
[[1881   28]
 [ 798    7]]

Fold 4 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.6399
Accuracy: 0.7006
Precision: 0.4908
Recall: 0.7006
F1-Score: 0.5772

Per-class Metrics:
  Immature (0): Precision=0.7006, Recall=1.0000, F1=0.8239
  Mature (1): Precision=0.0000, Recall=0.0000, F1=0.0000

Confusion Matrix:
[[475   0]
 [203   0]]

Fold 5/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:25<00:00,  3.13s/it, Loss=0.695, Acc=0.769]


Train - Loss: 0.6955, Acc: 0.6916, F1: 0.5765
Val   - Loss: 0.5862, Acc: 0.7227, F1: 0.6064

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.663, Acc=0.577]


Train - Loss: 0.6634, Acc: 0.6971, F1: 0.5733
Val   - Loss: 0.6609, Acc: 0.7227, F1: 0.6064

Epoch 3/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.17s/it, Loss=0.658, Acc=0.731]


Train - Loss: 0.6575, Acc: 0.6982, F1: 0.5745
Val   - Loss: 0.6291, Acc: 0.7227, F1: 0.6064

Epoch 4/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:29<00:00,  3.17s/it, Loss=0.638, Acc=0.808]


Train - Loss: 0.6383, Acc: 0.6971, F1: 0.5753
Val   - Loss: 0.6207, Acc: 0.7227, F1: 0.6064

Epoch 5/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.628, Acc=0.692]


Train - Loss: 0.6278, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6152, Acc: 0.7227, F1: 0.6064

Epoch 6/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:28<00:00,  3.16s/it, Loss=0.624, Acc=0.615]


Train - Loss: 0.6236, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6144, Acc: 0.7227, F1: 0.6064

Epoch 7/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.623, Acc=0.654]


Train - Loss: 0.6229, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6070, Acc: 0.7227, F1: 0.6064

Epoch 8/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.14s/it, Loss=0.622, Acc=0.654]


Train - Loss: 0.6223, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6129, Acc: 0.7227, F1: 0.6064

Epoch 9/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.622, Acc=0.769]


Train - Loss: 0.6216, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6088, Acc: 0.7227, F1: 0.6064

Epoch 10/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.14s/it, Loss=0.621, Acc=0.615]


Train - Loss: 0.6215, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6121, Acc: 0.7227, F1: 0.6064

Epoch 11/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.13s/it, Loss=0.621, Acc=0.654]


Train - Loss: 0.6214, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6086, Acc: 0.7227, F1: 0.6064

Epoch 12/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.13s/it, Loss=0.621, Acc=0.692]


Train - Loss: 0.6213, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6017, Acc: 0.7227, F1: 0.6064

Epoch 13/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.621, Acc=0.808]


Train - Loss: 0.6211, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6085, Acc: 0.7227, F1: 0.6064

Epoch 14/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.20s/it, Loss=0.621, Acc=0.731]


Train - Loss: 0.6211, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6050, Acc: 0.7227, F1: 0.6064

Epoch 15/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:32<00:00,  3.20s/it, Loss=0.621, Acc=0.692]


Train - Loss: 0.6212, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6050, Acc: 0.7227, F1: 0.6064

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:31<00:00,  3.20s/it, Loss=0.621, Acc=0.731]


Train - Loss: 0.6211, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6085, Acc: 0.7227, F1: 0.6064

Epoch 17/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:30<00:00,  3.19s/it, Loss=0.621, Acc=0.692]


Train - Loss: 0.6212, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6050, Acc: 0.7227, F1: 0.6064

Epoch 18/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:26<00:00,  3.14s/it, Loss=0.621, Acc=0.654]


Train - Loss: 0.6212, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6084, Acc: 0.7227, F1: 0.6064

Epoch 19/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.14s/it, Loss=0.621, Acc=0.577]


Train - Loss: 0.6213, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6050, Acc: 0.7227, F1: 0.6064

Epoch 20/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:27<00:00,  3.15s/it, Loss=0.621, Acc=0.692]


Train - Loss: 0.6212, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6084, Acc: 0.7227, F1: 0.6064

Fold 5 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.6955
Accuracy: 0.6916
Precision: 0.5643
Recall: 0.6916
F1-Score: 0.5765

Per-class Metrics:
  Immature (0): Precision=0.6973, Recall=0.9863, F1=0.8170
  Mature (1): Precision=0.2571, Recall=0.0110, F1=0.0211

Confusion Matrix:
[[1868   26]
 [ 811    9]]

Fold 5 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.5862
Accuracy: 0.7227
Precision: 0.5223
Recall: 0.7227
F1-Score: 0.6064

Per-class Metrics:
  Immature (0): Precision=0.7227, Recall=1.0000, F1=0.8390
  Mature (1): Precision=0.0000, Recall=0.0000, F1=0.0000

Confusion Matrix:
[[490   0]
 [188   0]]

Cross Validation Results Summary:
Fold 1: Val Acc = 0.6819, Val F1 = 0.5529, Val Loss = 0.5984
Fold 2: Val Acc = 0.6922, Val F1 = 0.5663, Val Loss = 0.6105
Fold 3: Val Acc = 0.7168, Val F1 = 

Training: 100%|███████████████████████████████████████████████| 106/106 [06:24<00:00,  3.63s/it, Loss=0.718, Acc=0.688]


Training Set - Loss: 0.7184, Acc: 0.6952, F1: 0.5861
Test Set - Loss: 0.6432, Acc: 0.7028, F1: 0.5802

Final Model - Epoch 2/15


Training: 100%|████████████████████████████████████████████████| 106/106 [06:14<00:00,  3.53s/it, Loss=0.624, Acc=0.75]


Training Set - Loss: 0.6243, Acc: 0.7028, F1: 0.5802
Test Set - Loss: 0.6100, Acc: 0.7028, F1: 0.5802

Final Model - Epoch 3/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:14<00:00,  3.53s/it, Loss=0.617, Acc=0.656]


Training Set - Loss: 0.6169, Acc: 0.7028, F1: 0.5802
Test Set - Loss: 0.6097, Acc: 0.7028, F1: 0.5802

Final Model - Epoch 4/15


Training: 100%|████████████████████████████████████████████████| 106/106 [06:15<00:00,  3.54s/it, Loss=0.615, Acc=0.75]


Training Set - Loss: 0.6150, Acc: 0.7028, F1: 0.5802
Test Set - Loss: 0.6097, Acc: 0.7028, F1: 0.5802

Final Model - Epoch 5/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:15<00:00,  3.54s/it, Loss=0.614, Acc=0.688]


Training Set - Loss: 0.6136, Acc: 0.7028, F1: 0.5802
Test Set - Loss: 0.6123, Acc: 0.7028, F1: 0.5802

Final Model - Epoch 6/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:17<00:00,  3.56s/it, Loss=0.614, Acc=0.781]


Training Set - Loss: 0.6141, Acc: 0.7028, F1: 0.5802
Test Set - Loss: 0.6217, Acc: 0.7028, F1: 0.5802

Final Model - Epoch 7/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:13<00:00,  3.52s/it, Loss=0.614, Acc=0.656]


Training Set - Loss: 0.6141, Acc: 0.7028, F1: 0.5802
Test Set - Loss: 0.6159, Acc: 0.7028, F1: 0.5802

Final Model - Epoch 8/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:15<00:00,  3.55s/it, Loss=0.614, Acc=0.656]


Training Set - Loss: 0.6135, Acc: 0.7028, F1: 0.5802
Test Set - Loss: 0.6097, Acc: 0.7028, F1: 0.5802

Final Model - Epoch 9/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:13<00:00,  3.53s/it, Loss=0.612, Acc=0.688]


Training Set - Loss: 0.6123, Acc: 0.7028, F1: 0.5802
Test Set - Loss: 0.6097, Acc: 0.7028, F1: 0.5802

Final Model - Epoch 10/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:17<00:00,  3.56s/it, Loss=0.613, Acc=0.594]


Training Set - Loss: 0.6126, Acc: 0.7028, F1: 0.5802
Test Set - Loss: 0.6097, Acc: 0.7028, F1: 0.5802

Final Model - Epoch 11/15


Training: 100%|████████████████████████████████████████████████| 106/106 [06:18<00:00,  3.57s/it, Loss=0.611, Acc=0.75]


Training Set - Loss: 0.6107, Acc: 0.7028, F1: 0.5802
Test Set - Loss: 0.6097, Acc: 0.7028, F1: 0.5802

Final Model - Epoch 12/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:16<00:00,  3.55s/it, Loss=0.613, Acc=0.594]


Training Set - Loss: 0.6130, Acc: 0.7028, F1: 0.5802
Test Set - Loss: 0.6097, Acc: 0.7028, F1: 0.5802

Final Model - Epoch 13/15


Training: 100%|█████████████████████████████████████████████████| 106/106 [06:17<00:00,  3.56s/it, Loss=0.61, Acc=0.75]


Training Set - Loss: 0.6099, Acc: 0.7028, F1: 0.5802
Test Set - Loss: 0.6097, Acc: 0.7028, F1: 0.5802

Final Model - Epoch 14/15


Training: 100%|████████████████████████████████████████████████| 106/106 [06:19<00:00,  3.58s/it, Loss=0.61, Acc=0.594]


Training Set - Loss: 0.6104, Acc: 0.7028, F1: 0.5802
Test Set - Loss: 0.6097, Acc: 0.7028, F1: 0.5802

Final Model - Epoch 15/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:21<00:00,  3.60s/it, Loss=0.611, Acc=0.844]


Training Set - Loss: 0.6109, Acc: 0.7028, F1: 0.5802
Test Set - Loss: 0.6097, Acc: 0.7028, F1: 0.5802

Final Training Set Detailed Metrics:

Final Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.7184
Accuracy: 0.6952
Precision: 0.5822
Recall: 0.6952
F1-Score: 0.5861

Per-class Metrics:
  Immature (0): Precision=0.7028, Recall=0.9811, F1=0.8190
  Mature (1): Precision=0.2969, Recall=0.0188, F1=0.0354

Confusion Matrix:
[[2339   45]
 [ 989   19]]

Test Set Detailed Metrics:

Test Set Detailed Metrics:
--------------------------------------------------
Loss: 0.6432
Accuracy: 0.7028
Precision: 0.4940
Recall: 0.7028
F1-Score: 0.5802

Per-class Metrics:
  Immature (0): Precision=0.7028, Recall=1.0000, F1=0.8255
  Mature (1): Precision=0.0000, Recall=0.0000, F1=0.0000

Confusion Matrix:
[[596   0]
 [252   0]]

✓ Results saved to vgg16_model_training_results.xlsx

Summary of Results:
5-fold cross validation average validation accuracy: 0.7028
Final tra