In [2]:
import os
import sys
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset, SubsetRandomSampler
from torchvision import transforms
from torchvision.models import vit_b_16, ViT_B_16_Weights
from PIL import Image
import numpy as np
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
from tqdm import tqdm
import warnings
import pandas as pd
import pickle
warnings.filterwarnings('ignore')

def check_gpu_available():
    if not torch.cuda.is_available():
        print("Error: No available GPU device detected.")
        print("Please ensure:")
        print("1. CUDA and cuDNN are installed")
        print("2. PyTorch version with GPU support is installed")
        print("3. Graphics card driver is up to date")
        print("\nProgram requires GPU for training, exiting now...")
        sys.exit(1)

    print(f"✓ GPU available: {torch.cuda.get_device_name(0)}")
    print(f"  Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
    print(f"  CUDA version: {torch.version.cuda}")
    return True

check_gpu_available()

def set_seed(seed=42):
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

class CustomDataset(Dataset):
    def __init__(self, image_paths, labels, transform=None):
        self.image_paths = image_paths
        self.labels = labels
        self.transform = transform
        
    def __len__(self):
        return len(self.image_paths)
    
    def __getitem__(self, idx):
        image = Image.open(self.image_paths[idx]).convert('RGB')
        label = self.labels[idx]
        
        if self.transform:
            image = self.transform(image)
            
        return image, label

def load_data(immature_dir, mature_dir):
    immature_paths = []
    mature_paths = []
    
    for img_name in os.listdir(immature_dir):
        if img_name.lower().endswith(('.jpg', '.jpeg', '.png')):
            immature_paths.append(os.path.join(immature_dir, img_name))
    
    for img_name in os.listdir(mature_dir):
        if img_name.lower().endswith(('.jpg', '.jpeg', '.png')):
            mature_paths.append(os.path.join(mature_dir, img_name))
    
    all_paths = immature_paths + mature_paths
    all_labels = [0] * len(immature_paths) + [1] * len(mature_paths)
    
    print(f"Immature images: {len(immature_paths)}")
    print(f"Mature images: {len(mature_paths)}")
    print(f"Total images: {len(all_paths)}")
    
    return all_paths, all_labels

def get_transforms():
    train_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.RandomRotation(10),
        transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                           std=[0.229, 0.224, 0.225])
    ])
    
    val_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                           std=[0.229, 0.224, 0.225])
    ])
    
    return train_transform, val_transform

def create_vit_model(num_classes=2):
    model = vit_b_16(weights=ViT_B_16_Weights.IMAGENET1K_V1)
    
    num_features = model.heads.head.in_features
    model.heads.head = nn.Sequential(
        nn.Dropout(0.5),
        nn.Linear(num_features, 256),
        nn.ReLU(),
        nn.Dropout(0.3),
        nn.Linear(256, num_classes)
    )
    
    return model

def calculate_metrics(all_labels, all_predictions):
    accuracy = np.mean(np.array(all_labels) == np.array(all_predictions))
    
    precision = precision_score(all_labels, all_predictions, average='weighted')
    recall = recall_score(all_labels, all_predictions, average='weighted')
    f1 = f1_score(all_labels, all_predictions, average='weighted')
    
    precision_per_class = precision_score(all_labels, all_predictions, average=None)
    recall_per_class = recall_score(all_labels, all_predictions, average=None)
    f1_per_class = f1_score(all_labels, all_predictions, average=None)
    
    cm = confusion_matrix(all_labels, all_predictions)
    
    report = classification_report(all_labels, all_predictions, 
                                  target_names=['immature', 'mature'], 
                                  output_dict=True)
    
    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'precision_per_class': precision_per_class,
        'recall_per_class': recall_per_class,
        'f1_per_class': f1_per_class,
        'confusion_matrix': cm,
        'classification_report': report
    }

def train_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    all_predictions = []
    all_labels = []
    
    progress_bar = tqdm(dataloader, desc='Training')
    for images, labels in progress_bar:
        images, labels = images.to(device), labels.to(device)
        
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        
        all_predictions.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
        
        batch_acc = (predicted == labels).sum().item() / labels.size(0)
        progress_bar.set_postfix({'Loss': running_loss/len(dataloader), 'Acc': batch_acc})
    
    epoch_loss = running_loss / len(dataloader)
    
    metrics = calculate_metrics(all_labels, all_predictions)
    metrics['loss'] = epoch_loss
    
    return epoch_loss, metrics

def evaluate_model(model, dataloader, criterion, device, dataset_name="Dataset"):
    model.eval()
    running_loss = 0.0
    all_predictions = []
    all_labels = []
    
    with torch.no_grad():
        for images, labels in dataloader:
            images, labels = images.to(device), labels.to(device)
            
            outputs = model(images)
            loss = criterion(outputs, labels)
            
            running_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            
            all_predictions.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    
    epoch_loss = running_loss / len(dataloader)
    
    metrics = calculate_metrics(all_labels, all_predictions)
    metrics['loss'] = epoch_loss
    
    return epoch_loss, metrics

def print_detailed_metrics(metrics, dataset_name="Dataset"):
    print(f"\n{dataset_name} Detailed Metrics:")
    print("-" * 50)
    print(f"Loss: {metrics['loss']:.4f}")
    print(f"Accuracy: {metrics['accuracy']:.4f}")
    print(f"Precision: {metrics['precision']:.4f}")
    print(f"Recall: {metrics['recall']:.4f}")
    print(f"F1-Score: {metrics['f1']:.4f}")
    
    print(f"\nPer-class Metrics:")
    print(f"  Immature (0): Precision={metrics['precision_per_class'][0]:.4f}, "
          f"Recall={metrics['recall_per_class'][0]:.4f}, F1={metrics['f1_per_class'][0]:.4f}")
    print(f"  Mature (1): Precision={metrics['precision_per_class'][1]:.4f}, "
          f"Recall={metrics['recall_per_class'][1]:.4f}, F1={metrics['f1_per_class'][1]:.4f}")
    
    print(f"\nConfusion Matrix:")
    print(metrics['confusion_matrix'])

def export_results_to_excel(fold_results, test_results, final_train_results, filename='training_results.xlsx'):
    all_results = []
    
    for fold_result in fold_results:
        fold_data = {
            'Fold': fold_result['fold'],
            'Dataset': 'Validation',
            'Loss': fold_result['val_loss'],
            'Accuracy': fold_result['val_accuracy'],
            'Precision': fold_result['val_precision'],
            'Recall': fold_result['val_recall'],
            'F1_Score': fold_result['val_f1'],
            'Precision_Class0': fold_result['val_precision_per_class'][0],
            'Precision_Class1': fold_result['val_precision_per_class'][1],
            'Recall_Class0': fold_result['val_recall_per_class'][0],
            'Recall_Class1': fold_result['val_recall_per_class'][1],
            'F1_Class0': fold_result['val_f1_per_class'][0],
            'F1_Class1': fold_result['val_f1_per_class'][1],
            'Train_Loss': fold_result['train_loss'],
            'Train_Accuracy': fold_result['train_accuracy'],
            'Train_Precision': fold_result['train_precision'],
            'Train_Recall': fold_result['train_recall'],
            'Train_F1_Score': fold_result['train_f1']
        }
        all_results.append(fold_data)
    
    final_train_data = {
        'Fold': 'Final',
        'Dataset': 'Train',
        'Loss': final_train_results['loss'],
        'Accuracy': final_train_results['accuracy'],
        'Precision': final_train_results['precision'],
        'Recall': final_train_results['recall'],
        'F1_Score': final_train_results['f1'],
        'Precision_Class0': final_train_results['precision_per_class'][0],
        'Precision_Class1': final_train_results['precision_per_class'][1],
        'Recall_Class0': final_train_results['recall_per_class'][0],
        'Recall_Class1': final_train_results['recall_per_class'][1],
        'F1_Class0': final_train_results['f1_per_class'][0],
        'F1_Class1': final_train_results['f1_per_class'][1],
        'Train_Loss': final_train_results['loss'],
        'Train_Accuracy': final_train_results['accuracy'],
        'Train_Precision': final_train_results['precision'],
        'Train_Recall': final_train_results['recall'],
        'Train_F1_Score': final_train_results['f1']
    }
    all_results.append(final_train_data)
    
    test_data = {
        'Fold': 'Final',
        'Dataset': 'Test',
        'Loss': test_results['loss'],
        'Accuracy': test_results['accuracy'],
        'Precision': test_results['precision'],
        'Recall': test_results['recall'],
        'F1_Score': test_results['f1'],
        'Precision_Class0': test_results['precision_per_class'][0],
        'Precision_Class1': test_results['precision_per_class'][1],
        'Recall_Class0': test_results['recall_per_class'][0],
        'Recall_Class1': test_results['recall_per_class'][1],
        'F1_Class0': test_results['f1_per_class'][0],
        'F1_Class1': test_results['f1_per_class'][1],
        'Train_Loss': final_train_results['loss'],
        'Train_Accuracy': final_train_results['accuracy'],
        'Train_Precision': final_train_results['precision'],
        'Train_Recall': final_train_results['recall'],
        'Train_F1_Score': final_train_results['f1']
    }
    all_results.append(test_data)
    
    df = pd.DataFrame(all_results)
    
    validation_df = df[df['Dataset'] == 'Validation']
    if not validation_df.empty:
        avg_row = {
            'Fold': 'Average',
            'Dataset': 'Validation',
            'Loss': validation_df['Loss'].mean(),
            'Accuracy': validation_df['Accuracy'].mean(),
            'Precision': validation_df['Precision'].mean(),
            'Recall': validation_df['Recall'].mean(),
            'F1_Score': validation_df['F1_Score'].mean(),
            'Precision_Class0': validation_df['Precision_Class0'].mean(),
            'Precision_Class1': validation_df['Precision_Class1'].mean(),
            'Recall_Class0': validation_df['Recall_Class0'].mean(),
            'Recall_Class1': validation_df['Recall_Class1'].mean(),
            'F1_Class0': validation_df['F1_Class0'].mean(),
            'F1_Class1': validation_df['F1_Class1'].mean(),
            'Train_Loss': validation_df['Train_Loss'].mean(),
            'Train_Accuracy': validation_df['Train_Accuracy'].mean(),
            'Train_Precision': validation_df['Train_Precision'].mean(),
            'Train_Recall': validation_df['Train_Recall'].mean(),
            'Train_F1_Score': validation_df['Train_F1_Score'].mean()
        }
        
        df = pd.concat([df, pd.DataFrame([avg_row])], ignore_index=True)
    
    df.to_excel(filename, index=False)
    print(f"\n✓ Results saved to {filename}")
    
    print("\n" + "="*80)
    print("Summary of Results:")
    print("="*80)
    if not validation_df.empty:
        print(f"5-fold cross validation average validation accuracy: {validation_df['Accuracy'].mean():.4f}")
    print(f"Final training set accuracy: {final_train_results['accuracy']:.4f}")
    print(f"Test set accuracy: {test_results['accuracy']:.4f}")
    print(f"Test set F1 score: {test_results['f1']:.4f}")
    
    return df

def main():
    immature_dir = r"E:\TSG\jupyterlab\machine learning image\augmented_dataset\immature"
    mature_dir = r"E:\TSG\jupyterlab\machine learning image\augmented_dataset\mature"
    
    print("Loading data...")
    all_paths, all_labels = load_data(immature_dir, mature_dir)
    
    print("\nSplitting data into train and test sets...")
    train_paths, test_paths, train_labels, test_labels = train_test_split(
        all_paths, all_labels, test_size=0.2, random_state=42, stratify=all_labels
    )
    
    print(f"Train set size: {len(train_paths)}")
    print(f"Test set size: {len(test_paths)}")
    
    train_transform, val_transform = get_transforms()
    
    train_dataset = CustomDataset(train_paths, train_labels, train_transform)
    test_dataset = CustomDataset(test_paths, test_labels, val_transform)
    
    device = torch.device("cuda")
    print(f"\nUsing device: {device}")
    
    print("\nStarting 5-fold cross validation...")
    kfold = KFold(n_splits=5, shuffle=True, random_state=42)
    fold_results = []
    
    for fold, (train_idx, val_idx) in enumerate(kfold.split(train_dataset)):
        print(f"\n{'='*60}")
        print(f"Fold {fold+1}/5")
        print(f"{'='*60}")
        
        train_subsampler = SubsetRandomSampler(train_idx)
        val_subsampler = SubsetRandomSampler(val_idx)
        
        train_loader = DataLoader(train_dataset, batch_size=32, sampler=train_subsampler)
        val_loader = DataLoader(train_dataset, batch_size=32, sampler=val_subsampler)
        
        model = create_vit_model(num_classes=2)
        model = model.to(device)
        
        criterion = nn.CrossEntropyLoss()
        optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-4)
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', patience=3)
        
        num_epochs = 20
        best_val_acc = 0
        best_model_state = None
        best_train_metrics = None
        best_val_metrics = None
        best_train_loss = None
        
        for epoch in range(num_epochs):
            print(f"\nEpoch {epoch+1}/{num_epochs}")
            
            train_loss, train_metrics = train_epoch(model, train_loader, criterion, optimizer, device)
            
            val_loss, val_metrics = evaluate_model(model, val_loader, criterion, device, "Validation")
            
            scheduler.step(val_loss)
            
            print(f"Train - Loss: {train_loss:.4f}, Acc: {train_metrics['accuracy']:.4f}, "
                  f"F1: {train_metrics['f1']:.4f}")
            print(f"Val   - Loss: {val_loss:.4f}, Acc: {val_metrics['accuracy']:.4f}, "
                  f"F1: {val_metrics['f1']:.4f}")
            
            if val_metrics['accuracy'] > best_val_acc:
                best_val_acc = val_metrics['accuracy']
                best_model_state = model.state_dict().copy()
                best_train_metrics = train_metrics
                best_val_metrics = val_metrics
                best_train_loss = train_loss
        
        print_detailed_metrics(best_train_metrics, f"Fold {fold+1} - Best Training Set")
        print_detailed_metrics(best_val_metrics, f"Fold {fold+1} - Best Validation Set")
        
        fold_results.append({
            'fold': fold + 1,
            'best_val_acc': best_val_acc,
            'val_loss': best_val_metrics['loss'],
            'val_accuracy': best_val_metrics['accuracy'],
            'val_precision': best_val_metrics['precision'],
            'val_recall': best_val_metrics['recall'],
            'val_f1': best_val_metrics['f1'],
            'val_precision_per_class': best_val_metrics['precision_per_class'],
            'val_recall_per_class': best_val_metrics['recall_per_class'],
            'val_f1_per_class': best_val_metrics['f1_per_class'],
            'train_loss': best_train_loss,
            'train_accuracy': best_train_metrics['accuracy'],
            'train_precision': best_train_metrics['precision'],
            'train_recall': best_train_metrics['recall'],
            'train_f1': best_train_metrics['f1'],
            'model_state': best_model_state
        })
    
    print("\n" + "="*60)
    print("Cross Validation Results Summary:")
    print("="*60)
    for result in fold_results:
        print(f"Fold {result['fold']}: "
              f"Val Acc = {result['best_val_acc']:.4f}, "
              f"Val F1 = {result['val_f1']:.4f}, "
              f"Val Loss = {result['val_loss']:.4f}")
    
    avg_val_acc = np.mean([r['best_val_acc'] for r in fold_results])
    avg_val_f1 = np.mean([r['val_f1'] for r in fold_results])
    avg_val_loss = np.mean([r['val_loss'] for r in fold_results])
    print(f"\nAverage Validation Accuracy: {avg_val_acc:.4f}")
    print(f"Average Validation F1 Score: {avg_val_f1:.4f}")
    print(f"Average Validation Loss: {avg_val_loss:.4f}")
    
    print("\n" + "="*60)
    print("Evaluating Final Model on Test Set...")
    print("="*60)
    
    print("\nTraining final model on entire training set...")
    final_train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)
    
    final_model = create_vit_model(num_classes=2)
    final_model = final_model.to(device)
    
    final_criterion = nn.CrossEntropyLoss()
    final_optimizer = optim.Adam(final_model.parameters(), lr=0.001)
    final_scheduler = optim.lr_scheduler.ReduceLROnPlateau(final_optimizer, mode='min', patience=3)
    
    num_final_epochs = 15
    best_test_acc = 0
    best_test_metrics = None
    best_final_train_metrics = None
    best_final_train_loss = None
    
    for epoch in range(num_final_epochs):
        print(f"\nFinal Model - Epoch {epoch+1}/{num_final_epochs}")
        
        train_loss, train_metrics = train_epoch(final_model, final_train_loader, final_criterion, final_optimizer, device)
        
        test_loss, test_metrics = evaluate_model(final_model, test_loader, final_criterion, device, "Test")
        
        final_scheduler.step(test_loss)
        
        print(f"Training Set - Loss: {train_loss:.4f}, Acc: {train_metrics['accuracy']:.4f}, "
              f"F1: {train_metrics['f1']:.4f}")
        print(f"Test Set - Loss: {test_loss:.4f}, Acc: {test_metrics['accuracy']:.4f}, "
              f"F1: {test_metrics['f1']:.4f}")
        
        if test_metrics['accuracy'] > best_test_acc:
            best_test_acc = test_metrics['accuracy']
            best_test_metrics = test_metrics
            best_final_train_metrics = train_metrics
            best_final_train_loss = train_loss
            torch.save(final_model.state_dict(), 'best_vit_model.pth')
    
    print("\n" + "="*60)
    print("Final Training Set Detailed Metrics:")
    print("="*60)
    print_detailed_metrics(best_final_train_metrics, "Final Training Set")
    
    print("\n" + "="*60)
    print("Test Set Detailed Metrics:")
    print("="*60)
    print_detailed_metrics(best_test_metrics, "Test Set")
    
    export_results_to_excel(fold_results, best_test_metrics, best_final_train_metrics, 'vit_model_training_results.xlsx')
    
    def predict_single_image(image_path, model_path='best_vit_model.pth'):
        model = create_vit_model(num_classes=2)
        model.load_state_dict(torch.load(model_path, map_location=device))
        model = model.to(device)
        model.eval()
        
        image = Image.open(image_path).convert('RGB')
        transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                               std=[0.229, 0.224, 0.225])
        ])
        
        image_tensor = transform(image).unsqueeze(0).to(device)
        
        with torch.no_grad():
            outputs = model(image_tensor)
            probabilities = torch.softmax(outputs, dim=1)
            _, predicted = torch.max(outputs, 1)
            
            class_names = ['immature', 'mature']
            result = class_names[predicted.item()]
            confidence = probabilities[0][predicted.item()].item()
            
        return result, confidence
    
    print("\n" + "="*60)
    print("Model is ready for prediction!")
    print("Use predict_single_image('path/to/image.jpg') to classify new images.")
    print("="*60)
    
    with open('vit_classifier_info.pkl', 'wb') as f:
        pickle.dump({
            'train_paths': train_paths,
            'test_paths': test_paths,
            'train_labels': train_labels,
            'test_labels': test_labels,
            'class_names': ['immature', 'mature'],
            'normalization_mean': [0.485, 0.456, 0.406],
            'normalization_std': [0.229, 0.224, 0.225],
            'fold_results': fold_results,
            'test_results': best_test_metrics,
            'final_train_results': best_final_train_metrics
        }, f)
    
    return final_model, best_test_metrics, best_final_train_metrics

if __name__ == "__main__":
    model, test_results, train_results = main()

✓ GPU available: NVIDIA GeForce RTX 5070 Ti
  Memory: 17.09 GB
  CUDA version: 11.8
Loading data...
Immature images: 2980
Mature images: 1260
Total images: 4240

Splitting data into train and test sets...
Train set size: 3392
Test set size: 848

Using device: cuda

Starting 5-fold cross validation...

Fold 1/5

Epoch 1/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:09<00:00,  3.64s/it, Loss=0.626, Acc=0.68]


Train - Loss: 0.6261, Acc: 0.7029, F1: 0.5967
Val   - Loss: 0.6233, Acc: 0.6819, F1: 0.5529

Epoch 2/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:08<00:00,  3.63s/it, Loss=0.615, Acc=0.56]


Train - Loss: 0.6146, Acc: 0.6963, F1: 0.5883
Val   - Loss: 0.6404, Acc: 0.6819, F1: 0.5529

Epoch 3/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:09<00:00,  3.64s/it, Loss=0.612, Acc=0.72]


Train - Loss: 0.6122, Acc: 0.7081, F1: 0.5871
Val   - Loss: 0.6202, Acc: 0.6819, F1: 0.5529

Epoch 4/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:09<00:00,  3.64s/it, Loss=0.557, Acc=0.76]


Train - Loss: 0.5565, Acc: 0.7291, F1: 0.6680
Val   - Loss: 0.5445, Acc: 0.7393, F1: 0.7440

Epoch 5/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:10<00:00,  3.65s/it, Loss=0.559, Acc=0.72]


Train - Loss: 0.5588, Acc: 0.7390, F1: 0.6918
Val   - Loss: 0.6216, Acc: 0.6819, F1: 0.5529

Epoch 6/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:08<00:00,  3.63s/it, Loss=0.595, Acc=0.72]


Train - Loss: 0.5951, Acc: 0.7081, F1: 0.5871
Val   - Loss: 0.6181, Acc: 0.6819, F1: 0.5529

Epoch 7/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:09<00:00,  3.64s/it, Loss=0.572, Acc=0.64]


Train - Loss: 0.5718, Acc: 0.7084, F1: 0.5906
Val   - Loss: 0.5335, Acc: 0.7629, F1: 0.7546

Epoch 8/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [05:08<00:00,  3.63s/it, Loss=0.521, Acc=0.8]


Train - Loss: 0.5208, Acc: 0.7431, F1: 0.7156
Val   - Loss: 0.5195, Acc: 0.7585, F1: 0.7593

Epoch 9/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:09<00:00,  3.64s/it, Loss=0.471, Acc=0.88]


Train - Loss: 0.4707, Acc: 0.7928, F1: 0.7792
Val   - Loss: 0.5026, Acc: 0.7732, F1: 0.7472

Epoch 10/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [05:06<00:00,  3.60s/it, Loss=0.47, Acc=0.92]


Train - Loss: 0.4705, Acc: 0.7951, F1: 0.7828
Val   - Loss: 0.4862, Acc: 0.7938, F1: 0.7728

Epoch 11/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:04<00:00,  3.58s/it, Loss=0.465, Acc=0.76]


Train - Loss: 0.4648, Acc: 0.7991, F1: 0.7853
Val   - Loss: 0.4895, Acc: 0.7673, F1: 0.7383

Epoch 12/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.465, Acc=0.8]


Train - Loss: 0.4648, Acc: 0.7958, F1: 0.7789
Val   - Loss: 0.4711, Acc: 0.7791, F1: 0.7728

Epoch 13/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:03<00:00,  3.57s/it, Loss=0.464, Acc=0.88]


Train - Loss: 0.4639, Acc: 0.7936, F1: 0.7811
Val   - Loss: 0.4782, Acc: 0.8115, F1: 0.7945

Epoch 14/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.464, Acc=0.64]


Train - Loss: 0.4638, Acc: 0.7899, F1: 0.7743
Val   - Loss: 0.4951, Acc: 0.7452, F1: 0.7511

Epoch 15/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:03<00:00,  3.57s/it, Loss=0.463, Acc=0.92]


Train - Loss: 0.4633, Acc: 0.7940, F1: 0.7793
Val   - Loss: 0.4664, Acc: 0.7776, F1: 0.7772

Epoch 16/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:04<00:00,  3.58s/it, Loss=0.454, Acc=0.76]


Train - Loss: 0.4535, Acc: 0.7980, F1: 0.7829
Val   - Loss: 0.4794, Acc: 0.7923, F1: 0.7870

Epoch 17/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:03<00:00,  3.58s/it, Loss=0.444, Acc=0.76]


Train - Loss: 0.4444, Acc: 0.8028, F1: 0.7880
Val   - Loss: 0.4688, Acc: 0.7806, F1: 0.7678

Epoch 18/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.459, Acc=0.8]


Train - Loss: 0.4587, Acc: 0.7947, F1: 0.7790
Val   - Loss: 0.4553, Acc: 0.7968, F1: 0.7833

Epoch 19/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.448, Acc=0.72]


Train - Loss: 0.4485, Acc: 0.8035, F1: 0.7893
Val   - Loss: 0.4937, Acc: 0.7629, F1: 0.7677

Epoch 20/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.55s/it, Loss=0.461, Acc=0.72]


Train - Loss: 0.4609, Acc: 0.7991, F1: 0.7826
Val   - Loss: 0.4545, Acc: 0.7865, F1: 0.7644

Fold 1 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4639
Accuracy: 0.7936
Precision: 0.7843
Recall: 0.7936
F1-Score: 0.7811

Per-class Metrics:
  Immature (0): Precision=0.8146, Recall=0.9172, F1=0.8629
  Mature (1): Precision=0.7109, Recall=0.4937, F1=0.5827

Confusion Matrix:
[[1762  159]
 [ 401  391]]

Fold 1 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4782
Accuracy: 0.8115
Precision: 0.8187
Recall: 0.8115
F1-Score: 0.7945

Per-class Metrics:
  Immature (0): Precision=0.8018, Recall=0.9611, F1=0.8743
  Mature (1): Precision=0.8548, Recall=0.4907, F1=0.6235

Confusion Matrix:
[[445  18]
 [110 106]]

Fold 2/5

Epoch 1/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.53s/it, Loss=0.637, Acc=0.76]


Train - Loss: 0.6366, Acc: 0.6900, F1: 0.5983
Val   - Loss: 0.6162, Acc: 0.6922, F1: 0.5663

Epoch 2/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:03<00:00,  3.57s/it, Loss=0.611, Acc=0.64]


Train - Loss: 0.6107, Acc: 0.7055, F1: 0.5837
Val   - Loss: 0.6128, Acc: 0.6922, F1: 0.5663

Epoch 3/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.54s/it, Loss=0.586, Acc=0.68]


Train - Loss: 0.5861, Acc: 0.6978, F1: 0.6212
Val   - Loss: 0.5118, Acc: 0.6922, F1: 0.5663

Epoch 4/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.622, Acc=0.6]


Train - Loss: 0.6218, Acc: 0.6941, F1: 0.5957
Val   - Loss: 0.6090, Acc: 0.6922, F1: 0.5663

Epoch 5/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.54s/it, Loss=0.538, Acc=0.84]


Train - Loss: 0.5376, Acc: 0.7243, F1: 0.6749
Val   - Loss: 0.5077, Acc: 0.7688, F1: 0.7301

Epoch 6/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.54s/it, Loss=0.497, Acc=0.8]


Train - Loss: 0.4975, Acc: 0.7726, F1: 0.7609
Val   - Loss: 0.4598, Acc: 0.7938, F1: 0.7640

Epoch 7/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.475, Acc=0.8]


Train - Loss: 0.4754, Acc: 0.7910, F1: 0.7773
Val   - Loss: 0.4646, Acc: 0.7879, F1: 0.7895

Epoch 8/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.491, Acc=0.76]


Train - Loss: 0.4906, Acc: 0.7811, F1: 0.7651
Val   - Loss: 0.4843, Acc: 0.7673, F1: 0.7725

Epoch 9/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.472, Acc=0.84]


Train - Loss: 0.4720, Acc: 0.7862, F1: 0.7720
Val   - Loss: 0.4669, Acc: 0.7673, F1: 0.7194

Epoch 10/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.471, Acc=0.84]


Train - Loss: 0.4712, Acc: 0.7962, F1: 0.7786
Val   - Loss: 0.4588, Acc: 0.7938, F1: 0.7745

Epoch 11/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:03<00:00,  3.57s/it, Loss=0.478, Acc=0.64]


Train - Loss: 0.4777, Acc: 0.7873, F1: 0.7746
Val   - Loss: 0.6157, Acc: 0.6627, F1: 0.6724

Epoch 12/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.471, Acc=0.92]


Train - Loss: 0.4709, Acc: 0.7858, F1: 0.7708
Val   - Loss: 0.4713, Acc: 0.7806, F1: 0.7854

Epoch 13/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.462, Acc=0.92]


Train - Loss: 0.4618, Acc: 0.7962, F1: 0.7810
Val   - Loss: 0.4530, Acc: 0.7968, F1: 0.7696

Epoch 14/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.474, Acc=0.72]


Train - Loss: 0.4742, Acc: 0.7917, F1: 0.7764
Val   - Loss: 0.4583, Acc: 0.7938, F1: 0.7802

Epoch 15/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.458, Acc=0.8]


Train - Loss: 0.4581, Acc: 0.8021, F1: 0.7869
Val   - Loss: 0.4455, Acc: 0.8100, F1: 0.8054

Epoch 16/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.55s/it, Loss=0.461, Acc=0.64]


Train - Loss: 0.4612, Acc: 0.7965, F1: 0.7764
Val   - Loss: 0.4582, Acc: 0.8056, F1: 0.7960

Epoch 17/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.466, Acc=0.92]


Train - Loss: 0.4656, Acc: 0.7940, F1: 0.7749
Val   - Loss: 0.4498, Acc: 0.8041, F1: 0.7910

Epoch 18/20


Training: 100%|████████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.46, Acc=0.6]


Train - Loss: 0.4604, Acc: 0.7976, F1: 0.7814
Val   - Loss: 0.4482, Acc: 0.8012, F1: 0.7829

Epoch 19/20


Training: 100%|███████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.54s/it, Loss=0.505, Acc=0.8]


Train - Loss: 0.5053, Acc: 0.7722, F1: 0.7431
Val   - Loss: 0.4821, Acc: 0.7747, F1: 0.7784

Epoch 20/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.451, Acc=0.76]


Train - Loss: 0.4511, Acc: 0.8054, F1: 0.7929
Val   - Loss: 0.4621, Acc: 0.7909, F1: 0.7719

Fold 2 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4581
Accuracy: 0.8021
Precision: 0.7963
Recall: 0.8021
F1-Score: 0.7869

Per-class Metrics:
  Immature (0): Precision=0.8120, Recall=0.9363, F1=0.8697
  Mature (1): Precision=0.7589, Recall=0.4806, F1=0.5885

Confusion Matrix:
[[1792  122]
 [ 415  384]]

Fold 2 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4455
Accuracy: 0.8100
Precision: 0.8047
Recall: 0.8100
F1-Score: 0.8054

Per-class Metrics:
  Immature (0): Precision=0.8403, Recall=0.8957, F1=0.8671
  Mature (1): Precision=0.7247, Recall=0.6172, F1=0.6667

Confusion Matrix:
[[421  49]
 [ 80 129]]

Fold 3/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [04:58<00:00,  3.51s/it, Loss=0.634, Acc=0.654]


Train - Loss: 0.6340, Acc: 0.6945, F1: 0.5884
Val   - Loss: 0.5912, Acc: 0.7168, F1: 0.5986

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.54s/it, Loss=0.623, Acc=0.769]


Train - Loss: 0.6234, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.5906, Acc: 0.7168, F1: 0.5986

Epoch 3/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.622, Acc=0.731]


Train - Loss: 0.6216, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.5976, Acc: 0.7168, F1: 0.5986

Epoch 4/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.62, Acc=0.654]


Train - Loss: 0.6198, Acc: 0.6993, F1: 0.5756
Val   - Loss: 0.6000, Acc: 0.7168, F1: 0.5986

Epoch 5/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.54s/it, Loss=0.618, Acc=0.615]


Train - Loss: 0.6182, Acc: 0.6912, F1: 0.5756
Val   - Loss: 0.5817, Acc: 0.7168, F1: 0.5986

Epoch 6/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.55s/it, Loss=0.601, Acc=0.731]


Train - Loss: 0.6014, Acc: 0.6957, F1: 0.5835
Val   - Loss: 0.5723, Acc: 0.7168, F1: 0.5986

Epoch 7/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.55s/it, Loss=0.581, Acc=0.731]


Train - Loss: 0.5812, Acc: 0.6990, F1: 0.5821
Val   - Loss: 0.5243, Acc: 0.7168, F1: 0.5986

Epoch 8/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.513, Acc=0.808]


Train - Loss: 0.5130, Acc: 0.7472, F1: 0.7270
Val   - Loss: 0.4633, Acc: 0.7832, F1: 0.7886

Epoch 9/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.489, Acc=0.769]


Train - Loss: 0.4886, Acc: 0.7808, F1: 0.7672
Val   - Loss: 0.5173, Acc: 0.7965, F1: 0.7542

Epoch 10/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.54s/it, Loss=0.487, Acc=0.885]


Train - Loss: 0.4867, Acc: 0.7845, F1: 0.7703
Val   - Loss: 0.4245, Acc: 0.8068, F1: 0.7829

Epoch 11/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.54s/it, Loss=0.477, Acc=0.692]


Train - Loss: 0.4770, Acc: 0.7856, F1: 0.7693
Val   - Loss: 0.4367, Acc: 0.8186, F1: 0.8047

Epoch 12/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.54s/it, Loss=0.475, Acc=0.769]


Train - Loss: 0.4747, Acc: 0.7804, F1: 0.7651
Val   - Loss: 0.4527, Acc: 0.8156, F1: 0.7851

Epoch 13/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.54s/it, Loss=0.463, Acc=0.808]


Train - Loss: 0.4628, Acc: 0.7915, F1: 0.7721
Val   - Loss: 0.5247, Acc: 0.7920, F1: 0.7928

Epoch 14/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.471, Acc=0.885]


Train - Loss: 0.4711, Acc: 0.7896, F1: 0.7714
Val   - Loss: 0.4394, Acc: 0.8127, F1: 0.7817

Epoch 15/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.54s/it, Loss=0.457, Acc=0.885]


Train - Loss: 0.4572, Acc: 0.8069, F1: 0.7928
Val   - Loss: 0.4266, Acc: 0.8215, F1: 0.8157

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.448, Acc=0.808]


Train - Loss: 0.4482, Acc: 0.7988, F1: 0.7867
Val   - Loss: 0.4197, Acc: 0.8112, F1: 0.7903

Epoch 17/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.54s/it, Loss=0.458, Acc=0.885]


Train - Loss: 0.4584, Acc: 0.7903, F1: 0.7725
Val   - Loss: 0.4227, Acc: 0.8260, F1: 0.8091

Epoch 18/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.54s/it, Loss=0.45, Acc=0.769]


Train - Loss: 0.4503, Acc: 0.7933, F1: 0.7765
Val   - Loss: 0.4133, Acc: 0.8142, F1: 0.7942

Epoch 19/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.54s/it, Loss=0.443, Acc=0.923]


Train - Loss: 0.4427, Acc: 0.8007, F1: 0.7843
Val   - Loss: 0.4159, Acc: 0.7965, F1: 0.7754

Epoch 20/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.44, Acc=0.923]


Train - Loss: 0.4400, Acc: 0.8066, F1: 0.7917
Val   - Loss: 0.3969, Acc: 0.8171, F1: 0.7994

Fold 3 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4584
Accuracy: 0.7903
Precision: 0.7847
Recall: 0.7903
F1-Score: 0.7725

Per-class Metrics:
  Immature (0): Precision=0.7989, Recall=0.9357, F1=0.8619
  Mature (1): Precision=0.7515, Recall=0.4522, F1=0.5647

Confusion Matrix:
[[1776  122]
 [ 447  369]]

Fold 3 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4227
Accuracy: 0.8260
Precision: 0.8275
Recall: 0.8260
F1-Score: 0.8091

Per-class Metrics:
  Immature (0): Precision=0.8239, Recall=0.9630, F1=0.8880
  Mature (1): Precision=0.8364, Recall=0.4792, F1=0.6093

Confusion Matrix:
[[468  18]
 [100  92]]

Fold 4/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.632, Acc=0.577]


Train - Loss: 0.6325, Acc: 0.6942, F1: 0.5883
Val   - Loss: 0.6578, Acc: 0.7006, F1: 0.5772

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.55s/it, Loss=0.616, Acc=0.692]


Train - Loss: 0.6164, Acc: 0.7019, F1: 0.5829
Val   - Loss: 0.5368, Acc: 0.7006, F1: 0.5772

Epoch 3/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:03<00:00,  3.57s/it, Loss=0.61, Acc=0.692]


Train - Loss: 0.6097, Acc: 0.7015, F1: 0.5879
Val   - Loss: 0.5794, Acc: 0.7006, F1: 0.5772

Epoch 4/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.601, Acc=0.731]


Train - Loss: 0.6013, Acc: 0.7034, F1: 0.5823
Val   - Loss: 0.5971, Acc: 0.7006, F1: 0.5772

Epoch 5/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.575, Acc=0.462]


Train - Loss: 0.5752, Acc: 0.7041, F1: 0.5973
Val   - Loss: 0.5434, Acc: 0.7006, F1: 0.5772

Epoch 6/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.524, Acc=0.769]


Train - Loss: 0.5242, Acc: 0.7506, F1: 0.7332
Val   - Loss: 0.4690, Acc: 0.7817, F1: 0.7772

Epoch 7/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.495, Acc=0.692]


Train - Loss: 0.4955, Acc: 0.7837, F1: 0.7728
Val   - Loss: 0.4500, Acc: 0.7906, F1: 0.7791

Epoch 8/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.47, Acc=0.731]


Train - Loss: 0.4702, Acc: 0.7948, F1: 0.7801
Val   - Loss: 0.4186, Acc: 0.8112, F1: 0.8092

Epoch 9/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.474, Acc=0.885]


Train - Loss: 0.4736, Acc: 0.7970, F1: 0.7858
Val   - Loss: 0.5074, Acc: 0.7832, F1: 0.7395

Epoch 10/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.486, Acc=0.654]


Train - Loss: 0.4857, Acc: 0.7808, F1: 0.7623
Val   - Loss: 0.4931, Acc: 0.8038, F1: 0.7764

Epoch 11/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.461, Acc=0.885]


Train - Loss: 0.4611, Acc: 0.8062, F1: 0.7938
Val   - Loss: 0.4995, Acc: 0.7817, F1: 0.7394

Epoch 12/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.46, Acc=0.846]


Train - Loss: 0.4595, Acc: 0.8007, F1: 0.7855
Val   - Loss: 0.4338, Acc: 0.8068, F1: 0.7813

Epoch 13/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:03<00:00,  3.57s/it, Loss=0.454, Acc=0.692]


Train - Loss: 0.4541, Acc: 0.8010, F1: 0.7837
Val   - Loss: 0.4464, Acc: 0.8024, F1: 0.7858

Epoch 14/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.442, Acc=0.769]


Train - Loss: 0.4424, Acc: 0.8095, F1: 0.7962
Val   - Loss: 0.4229, Acc: 0.8142, F1: 0.7991

Epoch 15/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.443, Acc=0.654]


Train - Loss: 0.4429, Acc: 0.8102, F1: 0.7952
Val   - Loss: 0.3948, Acc: 0.8274, F1: 0.8142

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.442, Acc=0.808]


Train - Loss: 0.4424, Acc: 0.8143, F1: 0.8013
Val   - Loss: 0.4081, Acc: 0.8156, F1: 0.7982

Epoch 17/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:03<00:00,  3.57s/it, Loss=0.442, Acc=0.846]


Train - Loss: 0.4415, Acc: 0.8007, F1: 0.7843
Val   - Loss: 0.3966, Acc: 0.8156, F1: 0.7976

Epoch 18/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.438, Acc=0.808]


Train - Loss: 0.4383, Acc: 0.8032, F1: 0.7882
Val   - Loss: 0.4192, Acc: 0.8097, F1: 0.7924

Epoch 19/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.446, Acc=0.885]


Train - Loss: 0.4455, Acc: 0.8007, F1: 0.7857
Val   - Loss: 0.4188, Acc: 0.7935, F1: 0.7724

Epoch 20/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:03<00:00,  3.57s/it, Loss=0.438, Acc=0.769]


Train - Loss: 0.4378, Acc: 0.8069, F1: 0.7893
Val   - Loss: 0.4145, Acc: 0.8215, F1: 0.8063

Fold 4 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4429
Accuracy: 0.8102
Precision: 0.8073
Recall: 0.8102
F1-Score: 0.7952

Per-class Metrics:
  Immature (0): Precision=0.8151, Recall=0.9445, F1=0.8750
  Mature (1): Precision=0.7888, Recall=0.4919, F1=0.6060

Confusion Matrix:
[[1803  106]
 [ 409  396]]

Fold 4 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3948
Accuracy: 0.8274
Precision: 0.8286
Recall: 0.8274
F1-Score: 0.8142

Per-class Metrics:
  Immature (0): Precision=0.8255, Recall=0.9558, F1=0.8859
  Mature (1): Precision=0.8359, Recall=0.5271, F1=0.6465

Confusion Matrix:
[[454  21]
 [ 96 107]]

Fold 5/5

Epoch 1/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.54s/it, Loss=0.628, Acc=0.577]


Train - Loss: 0.6278, Acc: 0.6920, F1: 0.5882
Val   - Loss: 0.5950, Acc: 0.7227, F1: 0.6064

Epoch 2/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.621, Acc=0.692]


Train - Loss: 0.6210, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6072, Acc: 0.7227, F1: 0.6064

Epoch 3/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.619, Acc=0.846]


Train - Loss: 0.6189, Acc: 0.6982, F1: 0.5745
Val   - Loss: 0.5964, Acc: 0.7227, F1: 0.6064

Epoch 4/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:03<00:00,  3.56s/it, Loss=0.622, Acc=0.538]


Train - Loss: 0.6216, Acc: 0.6964, F1: 0.5763
Val   - Loss: 0.5997, Acc: 0.7227, F1: 0.6064

Epoch 5/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.635, Acc=0.654]


Train - Loss: 0.6352, Acc: 0.6927, F1: 0.5833
Val   - Loss: 0.5843, Acc: 0.7227, F1: 0.6064

Epoch 6/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.623, Acc=0.769]


Train - Loss: 0.6226, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6032, Acc: 0.7227, F1: 0.6064

Epoch 7/20


Training: 100%|██████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.54s/it, Loss=0.62, Acc=0.615]


Train - Loss: 0.6204, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.5921, Acc: 0.7227, F1: 0.6064

Epoch 8/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.618, Acc=0.692]


Train - Loss: 0.6182, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6048, Acc: 0.7227, F1: 0.6064

Epoch 9/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.619, Acc=0.769]


Train - Loss: 0.6189, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.5854, Acc: 0.7227, F1: 0.6064

Epoch 10/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.618, Acc=0.769]


Train - Loss: 0.6176, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.5960, Acc: 0.7227, F1: 0.6064

Epoch 11/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.56s/it, Loss=0.614, Acc=0.692]


Train - Loss: 0.6141, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6058, Acc: 0.7227, F1: 0.6064

Epoch 12/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.54s/it, Loss=0.618, Acc=0.692]


Train - Loss: 0.6182, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.5891, Acc: 0.7227, F1: 0.6064

Epoch 13/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.613, Acc=0.692]


Train - Loss: 0.6134, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.5872, Acc: 0.7227, F1: 0.6064

Epoch 14/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.54s/it, Loss=0.613, Acc=0.731]


Train - Loss: 0.6133, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.5875, Acc: 0.7227, F1: 0.6064

Epoch 15/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:02<00:00,  3.55s/it, Loss=0.615, Acc=0.769]


Train - Loss: 0.6152, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6026, Acc: 0.7227, F1: 0.6064

Epoch 16/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.54s/it, Loss=0.614, Acc=0.538]


Train - Loss: 0.6136, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.5826, Acc: 0.7227, F1: 0.6064

Epoch 17/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.54s/it, Loss=0.615, Acc=0.731]


Train - Loss: 0.6145, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.5879, Acc: 0.7227, F1: 0.6064

Epoch 18/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.54s/it, Loss=0.612, Acc=0.692]


Train - Loss: 0.6122, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.5877, Acc: 0.7227, F1: 0.6064

Epoch 19/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:01<00:00,  3.55s/it, Loss=0.615, Acc=0.615]


Train - Loss: 0.6148, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.6028, Acc: 0.7227, F1: 0.6064

Epoch 20/20


Training: 100%|█████████████████████████████████████████████████| 85/85 [05:00<00:00,  3.53s/it, Loss=0.613, Acc=0.731]


Train - Loss: 0.6127, Acc: 0.6979, F1: 0.5737
Val   - Loss: 0.5928, Acc: 0.7227, F1: 0.6064

Fold 5 - Best Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.6278
Accuracy: 0.6920
Precision: 0.6062
Recall: 0.6920
F1-Score: 0.5882

Per-class Metrics:
  Immature (0): Precision=0.7002, Recall=0.9768, F1=0.8157
  Mature (1): Precision=0.3889, Recall=0.0341, F1=0.0628

Confusion Matrix:
[[1850   44]
 [ 792   28]]

Fold 5 - Best Validation Set Detailed Metrics:
--------------------------------------------------
Loss: 0.5950
Accuracy: 0.7227
Precision: 0.5223
Recall: 0.7227
F1-Score: 0.6064

Per-class Metrics:
  Immature (0): Precision=0.7227, Recall=1.0000, F1=0.8390
  Mature (1): Precision=0.0000, Recall=0.0000, F1=0.0000

Confusion Matrix:
[[490   0]
 [188   0]]

Cross Validation Results Summary:
Fold 1: Val Acc = 0.8115, Val F1 = 0.7945, Val Loss = 0.4782
Fold 2: Val Acc = 0.8100, Val F1 = 0.8054, Val Loss = 0.4455
Fold 3: Val Acc = 0.8260, Val F1 = 

Training: 100%|███████████████████████████████████████████████| 106/106 [06:17<00:00,  3.56s/it, Loss=0.627, Acc=0.781]


Training Set - Loss: 0.6273, Acc: 0.6969, F1: 0.5846
Test Set - Loss: 0.5780, Acc: 0.7028, F1: 0.5802

Final Model - Epoch 2/15


Training: 100%|████████████████████████████████████████████████| 106/106 [06:17<00:00,  3.57s/it, Loss=0.542, Acc=0.75]


Training Set - Loss: 0.5420, Acc: 0.7391, F1: 0.7004
Test Set - Loss: 0.4491, Acc: 0.8078, F1: 0.8079

Final Model - Epoch 3/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:17<00:00,  3.56s/it, Loss=0.478, Acc=0.812]


Training Set - Loss: 0.4784, Acc: 0.7863, F1: 0.7745
Test Set - Loss: 0.4604, Acc: 0.8054, F1: 0.7767

Final Model - Epoch 4/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:25<00:00,  3.64s/it, Loss=0.472, Acc=0.844]


Training Set - Loss: 0.4715, Acc: 0.8010, F1: 0.7856
Test Set - Loss: 0.4010, Acc: 0.8290, F1: 0.8223

Final Model - Epoch 5/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:30<00:00,  3.68s/it, Loss=0.459, Acc=0.844]


Training Set - Loss: 0.4590, Acc: 0.7978, F1: 0.7830
Test Set - Loss: 0.3941, Acc: 0.8408, F1: 0.8303

Final Model - Epoch 6/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:25<00:00,  3.64s/it, Loss=0.462, Acc=0.844]


Training Set - Loss: 0.4620, Acc: 0.7916, F1: 0.7711
Test Set - Loss: 0.4251, Acc: 0.8208, F1: 0.8005

Final Model - Epoch 7/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:27<00:00,  3.66s/it, Loss=0.461, Acc=0.656]


Training Set - Loss: 0.4615, Acc: 0.8007, F1: 0.7865
Test Set - Loss: 0.4759, Acc: 0.7748, F1: 0.7226

Final Model - Epoch 8/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:26<00:00,  3.65s/it, Loss=0.447, Acc=0.844]


Training Set - Loss: 0.4474, Acc: 0.8016, F1: 0.7860
Test Set - Loss: 0.4359, Acc: 0.7936, F1: 0.7528

Final Model - Epoch 9/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:26<00:00,  3.65s/it, Loss=0.441, Acc=0.875]


Training Set - Loss: 0.4413, Acc: 0.8078, F1: 0.7933
Test Set - Loss: 0.3977, Acc: 0.8267, F1: 0.8109

Final Model - Epoch 10/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:26<00:00,  3.64s/it, Loss=0.435, Acc=0.812]


Training Set - Loss: 0.4352, Acc: 0.8028, F1: 0.7895
Test Set - Loss: 0.4110, Acc: 0.8125, F1: 0.7854

Final Model - Epoch 11/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:27<00:00,  3.66s/it, Loss=0.431, Acc=0.812]


Training Set - Loss: 0.4310, Acc: 0.8107, F1: 0.7971
Test Set - Loss: 0.4012, Acc: 0.8219, F1: 0.8030

Final Model - Epoch 12/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:27<00:00,  3.66s/it, Loss=0.436, Acc=0.844]


Training Set - Loss: 0.4359, Acc: 0.8084, F1: 0.7955
Test Set - Loss: 0.3970, Acc: 0.8255, F1: 0.8085

Final Model - Epoch 13/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:26<00:00,  3.65s/it, Loss=0.437, Acc=0.844]


Training Set - Loss: 0.4368, Acc: 0.8040, F1: 0.7888
Test Set - Loss: 0.4027, Acc: 0.8196, F1: 0.7984

Final Model - Epoch 14/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:26<00:00,  3.65s/it, Loss=0.421, Acc=0.781]


Training Set - Loss: 0.4214, Acc: 0.8152, F1: 0.8010
Test Set - Loss: 0.4020, Acc: 0.8196, F1: 0.7984

Final Model - Epoch 15/15


Training: 100%|███████████████████████████████████████████████| 106/106 [06:26<00:00,  3.64s/it, Loss=0.427, Acc=0.844]


Training Set - Loss: 0.4268, Acc: 0.8134, F1: 0.7998
Test Set - Loss: 0.4037, Acc: 0.8196, F1: 0.7968

Final Training Set Detailed Metrics:

Final Training Set Detailed Metrics:
--------------------------------------------------
Loss: 0.4590
Accuracy: 0.7978
Precision: 0.7912
Recall: 0.7978
F1-Score: 0.7830

Per-class Metrics:
  Immature (0): Precision=0.8096, Recall=0.9312, F1=0.8662
  Mature (1): Precision=0.7477, Recall=0.4821, F1=0.5862

Confusion Matrix:
[[2220  164]
 [ 522  486]]

Test Set Detailed Metrics:

Test Set Detailed Metrics:
--------------------------------------------------
Loss: 0.3941
Accuracy: 0.8408
Precision: 0.8415
Recall: 0.8408
F1-Score: 0.8303

Per-class Metrics:
  Immature (0): Precision=0.8395, Recall=0.9564, F1=0.8941
  Mature (1): Precision=0.8462, Recall=0.5675, F1=0.6793

Confusion Matrix:
[[570  26]
 [109 143]]

✓ Results saved to vit_model_training_results.xlsx

Summary of Results:
5-fold cross validation average validation accuracy: 0.7995
Final train